Ensure all fields are available for conditions/validation on Save
directus/directus pull request #10106
Opened 2021-11-28 04:22 UTC by t7tran

Given the following fields in a collection with conditions:

- Field `Name`: optional
- Field `Age`: optional
- Field `Phone`: required with condition - optional when `id` is null

On creation load, all fields are rendered optional. However, required error is rendered against `Phone` field on Save.

![image](https://user-images.githubusercontent.com/76130324/143729435-23d3d836-3db8-4a23-a727-c7ee4bc2e361.png)

This is due to the fact that not all fields values are provided to the validation call during Save.

The above scenario is only for illustration. The fix covers update scenarios where conditions may also include rule on other un-edited fields.

2021-12-25 00:27 UTC, rijkvanzanten commented
I think we should handle this API-side rather than app-side, as that's where the validation happens. The app simply shows the error returned by the API.

2021-12-25 00:27 UTC, rijkvanzanten requested changes
I think we should handle this API-side rather than app-side, as that's where the validation happens. The app simply shows the error returned by the API.

2022-01-04 00:29 UTC, t7tran commented
I guess the situation wasn't clearly explained. I believe the `conditions` is the app thing which sounds nice but impossible to support on the server side out-of-the-box. In the example above, A server side hook is already implemented to take care of the required phone number on subsequent saves. It is the app that stops the submission on the initial save because the conditions weren't picked up.

This is just an example of incorrect condition selection evaluation during creation. We also run into other situations during subsequent saves. The simple fix is confirmed to work for all scenarios which is currently being used in our forked version.

2022-03-19 08:34 UTC, t7tran commented
Mostly fixed in #9593.

2022-03-19 08:41 UTC, t7tran commented
I'm now uncertain about this bug. Conditions include ID field as in the example above still fail. @rijkvanzanten any comment?

2022-03-19 23:35 UTC, t7tran commented
I've put together a replication sample using docker-compose in [issue-10106.zip](https://github.com/directus/directus/files/8310297/issue-10106.zip).

The fix in #9593 only makes all values available at form validation, not on Save ([source](https://github.com/directus/directus/blob/v9.7.0/app/src/composables/use-item/use-item.ts#L113)). This creates the inconsistent behaviour.

2022-03-21 15:57 UTC, rijkvanzanten commented
> I'm now uncertain about this bug. Conditions include ID field as in the example above still fail. @rijkvanzanten any comment?

I'll have to find some time to really dive into the deep end of the conditions checking. People are also generally confused around setting up conditional fields for relational fields as well, so I think it's worth doing a full iteration on that setup 🤔

2022-04-25 20:43 UTC, t7tran commented
This is now obsolete by #12933 and #12991.

2022-04-25 20:43 UTC, closed without merging