Serve app at `/` and api at `/api`
directus/directus pull request #10641
Opened 2021-12-22 18:00 UTC by Oreilles

The new share feature will add a new route to the app, and having it at `/admin/shared` seems a bit silly.
So instead, we'll move the whole app from `/admin` to `/`, and the api from `/` to `/api`.
This also makes Directus more in line with other platforms as having an `/api` endpoint is a very common practice.

2021-12-22 18:06 UTC, Oreilles commented on app/vite.config.js
> +			allow: [searchForWorkspaceRoot(process.cwd())],
Not sure about that one ?

2021-12-22 19:35 UTC, rijkvanzanten requested changes
We have to figure out how to make this configurable. We can't just flip the switch like this without it being a massive breaking change for every project that relies on Directus.

We should be able to introduce a set of environment variables (maybe "API_PATH" and "APP_PATH"?) that allow you to configure where the app and api live, which we can then default to the current state (eg `API_PATH="/"` and `APP_PATH="/admin"`) to make it backwards compatible. (We should also have a check to make sure that there's no naming conflicts; you should never be able to use the same value for both).

cc @benhaynes

2021-12-22 19:45 UTC, danieljwestman commented
I like this a lot!

A configurable app path is something I wanted for a long time 🙏🏼

2021-12-22 19:56 UTC, benhaynes commented
This is awesome and gets my approval (once we have the ability to configure for backward compatibility). Could we maintain CSVs of root API endpoints and App routes, and throw an error on startup if there are conflicts? If custom endpoints/routes are scoped in a root "folder", then that should cover the issue of duplicate keys, right?

2021-12-22 19:58 UTC, rijkvanzanten commented
> Could we maintain CSVs of root API endpoints and App routes, and throw an error on startup if there are conflicts? If custom endpoints/routes are scoped in a root "folder", then that should cover the issue of duplicate keys, right?

That'll be fairly tricky, as there's no real way to know all the paths, as custom modules get a path scope, as do custom endpoints. Those names are user provided 🤔

2021-12-26 18:08 UTC, julbd commented
I'm not sure about the `/admin` -> `/` move. One could want to reduce the `/admin` exposition with IP-filtering or others hosting settings for security purpose.

2021-12-27 15:19 UTC, rijkvanzanten commented
@julbd That's why we wanna make it configurable 🙂

2022-01-07 14:59 UTC, keesvanbemmel commented
I agree with @julbd :) we have our instance exposed at: api.example.com adding another /api sounds redundant to me ;)

2022-01-07 15:12 UTC, rijkvanzanten commented
> I agree with @julbd :) we have our instance exposed at: api.example.com adding another /api sounds redundant to me ;)

That was the use case we had in mind when coming up with the current structure as well 🙂 That being said, there's an argument to be made for the other approach too, so making it configurable makes the most sense to me

2022-03-22 04:32 UTC, danieljwestman commented
@Oreilles Done any more thinking of this much wanted improvement?

2022-06-30 17:00 UTC, rijkvanzanten commented
We're not currently planning on moving ahead with this.

2022-06-30 17:00 UTC, closed without merging

2022-06-30 17:16 UTC, benhaynes commented
Note: I really did like this idea, and would be fine with it as a Discussion 😉