Installation guide for Google Cloud Platform
directus/directus pull request #10936
Opened 2022-01-09 16:30 UTC by keesvanbemmel

2022-01-09 23:18 UTC, benhaynes commented
Thank you!!! 💯

2022-01-10 02:48 UTC, azrikahar requested changes
Thanks for the detailed guide! 👍 Just some minor localhost links & typos to update.

2022-01-10 02:48 UTC, azrikahar commented on docs/getting-started/installation/gcp.md
> +   `https://console.cloud.google.com/billing/linkedaccount?project=<your-project-id>`. Since the database and storace
```suggestion
   `https://console.cloud.google.com/billing/linkedaccount?project=<your-project-id>`. Since the database and storage
```

2022-01-10 02:48 UTC, azrikahar commented on docs/getting-started/installation/gcp.md
> +- You could setup [caching](http://localhost:8080/configuration/config-options/#cache) using
```suggestion
- You could setup [caching](/configuration/config-options/#cache) using
```

2022-01-10 02:48 UTC, azrikahar commented on docs/getting-started/installation/gcp.md
> +  [Schedule hooks](http://localhost:8080/extensions/hooks/#schedule) since there is no container to handle those
```suggestion
  [Schedule hooks](/extensions/hooks/#schedule) since there is no container to handle those
```

2022-01-10 02:48 UTC, azrikahar commented on docs/getting-started/installation/gcp.md
> +  shedules / cron jobs. Again you have two options: Set the minimum number of instances to 1, this will definitely
```suggestion
  schedules / cron jobs. Again you have two options: Set the minimum number of instances to 1, this will definitely
```

2022-01-10 09:44 UTC, azrikahar approved these changes

2022-01-10 09:49 UTC, keesvanbemmel commented
Thanks @azrikahar 

Just to be sure, this documentation also references functionality from https://github.com/directus/directus/pull/10911 so that needs to be merged as well (or removed from these docs)

2022-01-10 13:03 UTC, keesvanbemmel commented
Forgot to ask @azrikahar do you want me to add the contents of this

2022-01-10 13:19 UTC, azrikahar commented
>Forgot to ask do you want me to add the contents of this 

by that do you perhaps mean table of contents? Not quite sure which contents are referred here 😅

2022-01-10 14:01 UTC, benhaynes commented
I think @keesvanbemmel is talking about adding the Env Vars to the docs... which would indeed be really helpful. 👍

2022-01-10 14:11 UTC, keesvanbemmel commented
No I pressed send before completing my comment. Edited original comment!

2022-01-10 15:14 UTC, rijkvanzanten commented
> do you want me to add the contents of my own public repo to a directus repo?

Yeah lets do that! We can put it on the directus-community org 👍🏻 

Looking at it, it seems to be an "empty" installation. Do we even need to have a repo for that? 🤔

2022-01-10 17:12 UTC, rijkvanzanten commented
Makes sense! Yeah lets move that repo into directus-community then. Wondering if we can make it a more generic repo, as the setup is "plain" (not really google cloud specific 🤔).

2022-01-10 17:31 UTC, keesvanbemmel commented
> Makes sense! Yeah lets move that repo into directus-community then. Wondering if we can make it a more generic repo, as the setup is "plain" (not really google cloud specific 🤔).

Sure! How?

2022-01-11 22:05 UTC, rijkvanzanten commented
@keesvanbemmel I've setup https://github.com/directus-community/gcp-example and sent you an invite for maintainer access 🙂 

Lets put the example code there, and then update this doc to reference that

2022-01-11 22:05 UTC, keesvanbemmel commented
Awesome, will do so tomorrow!

2022-01-12 08:48 UTC, keesvanbemmel commented
Yes, example repo moved/copied to directus-community and ammended documentation. Also added the Google Cloud deploy button to the readme next to the others.

WOOOP!

2022-01-12 12:12 UTC, benhaynes commented
I'll leave it up to @rijkvanzanten to confirm... but wanted to say thank you for this!! 💯

2022-01-12 15:35 UTC, rijkvanzanten approved these changes
Looks good to me! Thanks @keesvanbemmel ❤️

2022-01-12 15:35 UTC, merged