Enable end-to-end tests for Oracle and SQLite
directus/directus pull request #11094
Opened 2022-01-17 11:09 UTC by Oreilles

Minor tweak: had to replace occurrences of:
```ts
expect(something).toStrictEqual([]);
```
by:
```ts
expect(something).toMatchObject([]);
```
Because tests were failing for SQLite with jest error:
```
Expected: []
Received: serializes to the same string
```

2022-01-17 12:56 UTC, aidenfoxx commented
Just a heads up with Oracle: If your `DB_POOL_MAX` exceeds or matches your `UV_THREADPOOL_SIZE` (default: 4) then the `node-oracledb` library will flood the threadpool and lock up the process. This is really stupid and the `node-oracledb` maintainers don't care to fix it even though no other DB library does this... 😩

More info here: https://github.com/oracle/node-oracledb/blob/main/doc/api.md#-162-connections-threads-and-parallelism

2022-01-17 12:59 UTC, Oreilles commented
@aidenfoxx does that mean we should force [`pool.max = 4`](https://knexjs.org/#Installation-pooling) for oracle clients ?

2022-01-17 13:10 UTC, aidenfoxx commented
@Oreilles I think the better workaround is to set the `pool.max` to something like:

```
Math.min(
  pool.max,
  Math.max(1, pool.max, process.env.UV_THREADPOOL_MAX - 2)
)
```

That way if sufficient threads are available we use `pool.max`, otherwise we fallback to the thread count minus 2, with a minimum limit of 1.

Always leaves sufficient headroom while still letting the user set their pool limits.

2022-01-17 15:18 UTC, Oreilles commented
@rijkvanzanten tests run fine on my machine, it's likely just a memory/cpu issue. 🙂
Finding a way around it.

2022-01-17 15:19 UTC, rijkvanzanten commented
@Oreilles Also wondering: Should we run every database test in the same CI process, or try to spin up a copy of the CI for every supported database (using the matrix) so they can run in parallel?

2022-01-17 15:24 UTC, Oreilles commented
I'd like to do that, executing the tests in a matrix would solve this performance issue, problem is that it implies seven times checkout + install + build, which even in parallel is long as you have to wait for available instances. I was trying to cache the whole build repo the other day, an back at it rn.

2022-01-17 18:30 UTC, Oreilles commented
So, all tests a properly configured and running. :)
They still fail though, because of date issues with Oracle. @aidenfoxx could you help with that ?
```
  ● /items › /:collection GET › "oracle" retrieves artists and events for each entry in artists_events

    insert into "events" ("cost", "created_at", "description", "id", "tags", "time") values (:1, :2, :3, :4, :5, :6) - ORA-01843: not a valid month
```

2022-01-17 20:13 UTC, aidenfoxx commented
@Oreilles I've not experienced that one myself. I can look into it tomorrow. 👍

2022-01-17 21:01 UTC, rijkvanzanten commented
My guess is that:

https://github.com/directus/directus/blob/aacf92eee6ecb6adc13d0e60e21db981511ff05a/tests/e2e/api/items/many-to-many.test.ts#L29

calls 

https://github.com/directus/directus/blob/aacf92eee6ecb6adc13d0e60e21db981511ff05a/tests/e2e/setup/utils/factories.ts#L143

which is in the wrong value / format / whatever for (node-)oracle?

2022-01-17 21:23 UTC, aidenfoxx commented
@rijkvanzanten Yeah, but you'd hope that'd be something knex would handle since I believe it just sends a standard Date object. 🤷

2022-01-18 12:33 UTC, Oreilles commented
Why not use Directus itself to seed data ? (and, by extension, also create the schema ?)

2022-01-18 14:19 UTC, aidenfoxx commented
I'm with @Oreilles on this one. Feels like it would be way more thorough to run the whole flow as an end user would.

2022-01-18 14:50 UTC, rijkvanzanten commented
> Why not use Directus itself to seed data ? (and, by extension, also create the schema ?)

We can! Just gotta be aware at that point that you're using the thing you're testing to prepare the tests, so if there's a bug in that database preparation logic thing, you get a lot of false negatives in the other tests.

2022-01-19 16:39 UTC, rijkvanzanten requested changes

2022-01-19 16:39 UTC, rijkvanzanten commented on .github/workflows/ci.yml
> +    uses: directus/directus/.github/workflows/lint.yml@add-e2e-tests-vendors
Should this be changed back to `main`?

2022-01-19 17:57 UTC, Oreilles commented on .github/workflows/ci.yml
> +    uses: directus/directus/.github/workflows/lint.yml@add-e2e-tests-vendors
Yes, same problem as before 👍

2022-01-19 18:00 UTC, rijkvanzanten approved these changes

2022-01-19 18:00 UTC, merged

2022-01-19 18:01 UTC, rijkvanzanten commented on .github/workflows/ci.yml
> +    uses: directus/directus/.github/workflows/lint.yml@add-e2e-tests-vendors
Renamed it to `main` on `main` 👍🏻