Disable login form when AUTH_DISABLE_DEFAULT is enabled
directus/directus pull request #11116
Opened 2022-01-17 18:53 UTC by diegoleme

When the AUTH_DISABLE_DEFAULT setting is enabled, the login form should not appear.

issue: #11114

2022-01-17 20:29 UTC, aidenfoxx commented
I'm not sure how this is supposed to work, but it seems incomplete. Isn't this already solved in this PR anyway? https://github.com/directus/directus/pull/8997/files

2022-01-18 10:48 UTC, azrikahar requested changes

2022-01-18 15:19 UTC, diegoleme commented on app/src/routes/login/login.vue
> +		const disableDefault = ref<boolean>(false);
👍🏻

2022-01-19 03:55 UTC, azrikahar approved these changes

2022-01-19 18:51 UTC, rijkvanzanten approved these changes

2022-01-19 18:51 UTC, merged