Fix not being able to delete folder in data-model
directus/directus pull request #11432
Opened 2022-02-04 14:13 UTC by Nitwel

Due to folders not being represented as a collection in the DB, the request would fail as it would try to delete a non existing collection.

2022-02-04 14:20 UTC, rijkvanzanten approved these changes

2022-02-04 14:31 UTC, rijkvanzanten requested changes
@Nitwel thanks! Mind adding a e2e test case for deleting collections? That way we can make sure this doesn't happen again 🙂

2022-02-04 14:31 UTC, rijkvanzanten commented on api/src/services/collections.ts
> +			}
Lets use the same check as below on 397

```suggestion
			if (collectionToBeDeleted!.schema) {
				await trx.schema.dropTable(collectionKey);
			}
```

2022-02-04 16:31 UTC, rijkvanzanten commented
@Nitwel
<img width="757" alt="CleanShot 2022-02-04 at 11 30 45@2x" src="https://user-images.githubusercontent.com/9141017/152566126-4bc164af-003f-4248-8e49-1b9f591c6dc5.png">

easy fix here is to use `toEqual` instead of `toBe` 👍🏻

2022-02-04 18:13 UTC, rijkvanzanten approved these changes

2022-02-04 18:13 UTC, merged

2022-02-14 08:31 UTC, onordgren commented
Is there any way to force delete a folder pending this to be released? I don't have (easy) direct access to the database so using the app/API would be ideal.

2022-02-14 16:38 UTC, onordgren commented
> > Is there any way to force delete a folder pending this to be released? I don't have (easy) direct access to the database so using the app/API would be ideal.
> 
> 
> 
> You should be able to use the folders endpoint to delete it still:
> 
> 
> 
> https://docs.directus.io/reference/system/folders/#delete-a-folder

I tried this last week but got a similar error as in the app. I however solved it by accessing the database directly for now.