Docs: Data Sharing
directus/directus pull request #11579
Opened 2022-02-11 00:37 UTC by erondpowell

Data Sharing Draft. Areas to Note:

- [ ] Checkout the `tip` under "What's a Share?". Is it legit enough?
- [ ] @benhaynes Checkout "How it Works" for copy, especially step 9. I like the copy but could be too casual.
- [ ] @rijkvanzanten Check the `warning` in "How it Works"
- [ ] Limit Sharing for Specific Collections, Limit Sharing to Specific Items, Limit Sharing of item Fields.... I have debated slashing these, adding a hyperlink to permissions, or expanding into step-by-step instructions. Any ideas?
- [ ] Extensibility Options: Still thinking about some boilerplate text for this.
- [ ] Tutorial will be slashed for this first initial final draft... _(a boy can dream!)_
- [ ] @rijkvanzanten More Help boilerplate... Should we just use same copy as on Azrael's example docs? I feel like this uses

2022-02-14 20:00 UTC, benhaynes requested changes
Looks really good! Just a few things I pointed out...

2022-02-17 17:24 UTC, erondpowell commented on docs/app/data-sharing.md
> +## New User Options
It is out of context... But it was an option available in **Data Share Options > Create Role > Users in Role** and Users, Roles, and Permissions was slightly under-developed. I will cut it and save it for Users, Roles, Permissions.

2022-02-17 17:27 UTC, erondpowell commented on docs/app/data-sharing.md
> +> to view that Item.
Incredible! 💪

2022-03-09 20:16 UTC, erondpowell commented
@benhaynes @rijkvanzanten 
Take a look at this one guys. 
Seems done.

2022-03-23 22:43 UTC, erondpowell commented
@rijkvanzanten Bumping this PR to your attention

2022-04-04 14:18 UTC, rijkvanzanten requested changes

2022-04-04 14:18 UTC, rijkvanzanten commented on docs/app/data-sharing.md
> +As mentioned several times before, when you create a Share on some Item, you associate a Role _(and thus the Role's
```suggestion
When you create a Share on some Item, you associate a Role _(and thus the Role's
```

Lets avoid "As mentioned several times before" type of language across the docs as it has a bit of a negative connotation. It reads to me like "Like we told you many times before you dummy, ..."

2022-04-04 14:18 UTC, rijkvanzanten commented on docs/app/data-sharing.md
> +[Community on Discord](https://discord.com/invite/directus).
Lets not include this in the page content. If we want to have a consistent footer for every page, it should be on the theme level, not the individual content of the pages.

Besides, for the context of Shares, extensions don't really come into play, so it doesn't have to be on this page regardless.

```suggestion
```

2022-04-04 14:30 UTC, rijkvanzanten approved these changes

2022-04-04 14:30 UTC, merged