fix: flex > inline-block
directus/directus pull request #12153
Opened 2022-03-14 19:21 UTC by yassilah

Resolves https://github.com/directus/directus/discussions/10867.

Currently, translations on a related field are not visible because `.display-translations` element is displayed as `flex` and its preceding sibling `.vertical-aligner` has a height of 100%. I just changed `flex` to `inline-block` to get the expected result.

### Before

<img width="1315" alt="Capture d’écran 2022-03-14 à 20 20 49" src="https://user-images.githubusercontent.com/13403295/158245409-eae41d72-b870-4b93-aff1-d03fc5d8c8a2.png">

### After

<img width="1315" alt="Capture d’écran 2022-03-14 à 20 21 20" src="https://user-images.githubusercontent.com/13403295/158245474-1aa6a29e-099e-4eb3-b07d-499e2c89bd8e.png">

2022-03-14 19:45 UTC, rijkvanzanten requested changes

2022-03-15 06:06 UTC, yassilah commented on app/src/displays/translations/translations.vue
> +
of course, makes much more sense

2022-03-15 06:08 UTC, yassilah commented on app/src/displays/translations/translations.vue
> +
and there's no need for this extra class 🙂

2022-03-15 14:48 UTC, rijkvanzanten approved these changes

2022-03-15 14:54 UTC, merged