Fix Invalid foreign key when applying schema snapshot
directus/directus pull request #12198
Opened 2022-03-16 17:42 UTC by PeeraJ

Fix #9723 
it's my first time contributing back to Directus community please let me know if something needs to be changed. 
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/12496997/158652367-bd190e83-281d-4daf-8e3f-9d8eef6e0abb.png">

as of before if you have data models as shown when you try to apply schema it will throw an error like this
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/12496997/158653005-989dc79e-5187-4898-86a6-0f1c25ccfd26.png">

after fix
<img width="535" alt="image" src="https://user-images.githubusercontent.com/12496997/158653221-4aa84613-903e-4383-af50-3a027f67c967.png">

2022-04-22 07:13 UTC, eyecatchup commented
This is a real deal breaker. @rijkvanzanten Could you gimme a rough estimate when you will have time to review this PR? Thanks.

2022-04-25 08:04 UTC, azrikahar requested changes

2022-04-25 08:04 UTC, azrikahar commented on api/src/utils/apply-snapshot.ts
> +				for (const item of collections) {
```suggestion
				for (const { collection, diff } of collections) {
```

More of a nitpick but let's keep the original destructuring to keep things similar as before 👍 (unless of course there's a naming collision that I'm missing here)

2022-04-25 08:04 UTC, azrikahar commented on api/src/utils/apply-snapshot.ts
> +				for (const item of collections) {
```suggestion
				for (const { collection, diff } of collections) {
```

2022-04-28 17:37 UTC, eyecatchup commented
I've added a [PR](https://github.com/PeeraJ/directus/pull/1/commits) to the patch branch to fix the deconstructing.

2022-05-03 05:15 UTC, eyecatchup commented
I see there're some unanswered questions from your initial review. @azrikahar could you please clarify if you're waiting for further specific answers from @PeeraJ or if you just not had the time to review the updates to this PR?

2022-05-03 09:15 UTC, azrikahar commented
> could you please clarify if you're waiting for further specific answers from @PeeraJ or if you just not had the time to review the updates to this PR?

Honestly both! If PeeraJ is still busy and time permits on my end, I'll try to add the remaining tweaks and merge conflict before the next planned release. Though ultimately it can be rather hard to give any certainty with other things taking priority at the moment. Hope that's understandable. 👍

2022-05-03 10:34 UTC, eyecatchup commented
Sure thing, understandable. Thanks for the quick reply! I've [moved the type declaration to the top](https://github.com/PeeraJ/directus/pull/2), hopefully @PeeraJ can merge this soon. Are there any remaining "tweaks" you would need? Otherwise I could take care of resolving the merge conflicts after my PR was merged to get this fixed asap, without blocking your time.

2022-05-03 11:22 UTC, PeeraJ commented
> Sure thing, understandable. Thanks for the quick reply! I've [moved the type declaration to the top](https://github.com/PeeraJ/directus/pull/2), hopefully @PeeraJ can merge this soon. Are there any remaining "tweaks" you would need? Otherwise I could take care of resolving the merge conflicts after my PR was merged to get this fixed asap, without blocking your time.

I'm so sorry to leave this unattended, I just came back from a long vacation and am unable to fix those problems right away. Thanks a lot for the pr though.🙏

2022-05-03 11:34 UTC, PeeraJ commented on api/src/utils/apply-snapshot.ts
> +			if (!isEmpty(collections)) {
removed.

2022-05-03 14:58 UTC, eyecatchup commented
Great. Thanks @PeeraJ for merging my change and removing the unnecessary empty check. That being done, it only needs to resolve the merge conflicts. Since I can not do it on this PR, I needed to create a duplicate. This PR https://github.com/directus/directus/pull/13096 includes all the changes from PeeraJ and me and resolves the merge conflict. @azrikahar anything else I can assist with to get this merged?

2022-05-03 17:00 UTC, azrikahar commented
@PeeraJ no worries! Thanks for updating promptly. I'll take it from here if that's okay with you 👍

> anything else I can assist with to get this merged?

@eyecatchup all good. I'd like to lean on to the safer side and do some tests on my end just to prevent any oversight here. I've resolved the merge conflict for now, and I'll add on any changes if needed before wrapping this up. Thanks again for helping out.

2022-05-04 09:25 UTC, azrikahar approved these changes

2022-05-09 20:49 UTC, merged