Fix CORS origin in CSV format
directus/directus pull request #12265
Opened 2022-03-21 06:54 UTC by licitdev

Closes #12259.

2022-03-21 13:10 UTC, rijkvanzanten commented
@licitdev Express' cors module should already support this by default:

> Array - set origin to an array of valid origins. Each origin can be a String or a RegExp. For example ["http://example1.com", /\.example2\.com$/] will accept any request from “http://example1.com” or from a subdomain of “example2.com”.

I think the problem is that the CSV isn't cast as an array properly in the env reading, causing it to be recognized as a string, rather than an array of strings

2022-03-21 13:18 UTC, licitdev commented
@rijkvanzanten I've tested it by passing a plain array, it didn't work as expected. When provided with an array, if not in the list, the origin is set to '*'. Thus I've used the `toArray()` util for parsing, similar to other env variables that allows CSV input.

This current PR sets the origin as...
'*' when `CORS_ORIGIN` is not set.
'matching origin' when matches any item in `CORS_ORIGIN`
'first origin' when no match is found

2022-03-21 13:19 UTC, rijkvanzanten commented
> @rijkvanzanten I've tested it by passing a plain array, it didn't work as expected. When provided with an array, if not in the list, the origin is set to '*'. Thus I've used the `toArray()` util for parsing, similar to other env variables that allows CSV input.
> 
> This current PR sets the origin as... '*' when `CORS_ORIGIN` is not set. 'matching origin' when matches any item in `CORS_ORIGIN` 'first origin' when no match is found

Odd! Thanks for confirming that 👍🏻

2022-03-21 13:20 UTC, rijkvanzanten requested changes

2022-03-21 13:26 UTC, licitdev commented on api/src/middleware/cors.ts
> +				callback(null, true);
In my tests, when setting to `true`, the origin will be set as `*`.
Will change it to increase clarity. Thanks!

2022-03-21 13:29 UTC, rijkvanzanten commented on api/src/middleware/cors.ts
> +				callback(null, true);
Huh! Are the express docs misleading then, or am I missing something here? 🤔 

https://expressjs.com/en/resources/middleware/cors.html#configuration-options

> The origin argument to the callback can be any value allowed for the origin option of the middleware, except a function. See the [configuration options](https://expressjs.com/en/resources/middleware/cors.html#configuration-options) section for more information on all the possible value types.

> Configuration Options
origin: Configures the Access-Control-Allow-Origin CORS header. Possible values:
>  - Boolean - set origin to true to reflect the [request origin](http://tools.ietf.org/html/draft-abarth-origin-09), as defined by req.header('Origin'), or set it to false to disable CORS.
>  - String - set origin to a specific origin. For example if you set it to "http://example.com" only requests from “http://example.com” will be allowed.

2022-03-21 13:29 UTC, rijkvanzanten commented on api/src/middleware/cors.ts
> +				callback(null, true);
Maybe express defaults to `*` when the Origin header is missing? Did you test it from a browser or from an API tool?

2022-03-21 14:06 UTC, licitdev commented on api/src/middleware/cors.ts
> +				callback(null, true);
@rijkvanzanten I am not sure why. Tested in the admin app, [test-cors.org](https://www.test-cors.org/) and also through an API tool (without origin). 
![Screenshot 2022-03-21 at 10 02 13 PM](https://user-images.githubusercontent.com/26413686/159277791-69c639da-bf2c-4d6c-8e7a-dc3fa9c5d007.png)
<img width="469" alt="Screenshot 2022-03-21 at 10 02 29 PM" src="https://user-images.githubusercontent.com/26413686/159277812-fa918e74-51b4-4c8c-96cc-c69af2aad908.png">

2022-03-23 15:28 UTC, rijkvanzanten commented on api/src/middleware/cors.ts
> +				callback(null, true);
It does seem to work as expected on my end. The Origin you're requesting doesn't exist in the `origin` configuration you used in the last screenshot, so the header isn't returned. When I configure `origin: ['http://localhost:8055', 'https://rijks.website'],` and set the Origin header to `https://rijks.website`, I'm correctly getting `Access-Control-Allow-Origin: https://rijks.website` returned

2022-03-23 15:36 UTC, licitdev commented on api/src/middleware/cors.ts
> +				callback(null, true);
But if you access from a third party website, a `*` gets returned. Which should not be the case as we are limiting the origins to be from our whitelist only?

2022-03-23 15:54 UTC, licitdev commented on api/src/middleware/cors.ts
> +				callback(null, true);
Note: I was testing through the Vite development server on `:8080`, thus encountered the above issue.

2022-03-23 15:54 UTC, rijkvanzanten commented
Allllllll this confusion stemmed from the fact that we were testing against the _dev proxy_ provided by Vite, which injects some custom magic in the CORS header. Besides the auto-casting of array like values in the .env (https://github.com/directus/directus/pull/12330), everything is actually working as expected

2022-03-23 15:54 UTC, closed without merging