Implement support for total counter on relationship fields
directus/directus pull request #12711
Opened 2022-04-12 18:32 UTC by u12206050

![related-count](https://user-images.githubusercontent.com/6641242/163029897-6d4a1f2f-3d8d-4268-a7cd-2153e6d1ade0.gif)

Had to find a way to include the display even though the field itself didn't have a value, therefore adding `item`
Also, had to skip prefixing of the function field which resulted in `relation.count(key)` which is obviously wrong.

2022-04-13 01:21 UTC, benhaynes commented
Love it! Thank you for the PR!! ❤️

2022-04-13 07:43 UTC, u12206050 commented on app/src/views/private/components/render-display/render-display.vue
> +		:item="item"
Fixed by renaming to rootItem

2022-05-02 09:14 UTC, u12206050 commented
@rijkvanzanten I know this question is frowned upon, but :) Any timeline when this might be released?

2022-05-02 13:53 UTC, benhaynes commented
Nothing official, but we're trying to get as many PRs reviewed and merged as possible. That said, we've been focusing on ones that resolve issues so far... but hopefully someone on the @directus/team can give it a lok!

2022-05-27 15:33 UTC, rijkvanzanten requested changes

2022-05-27 16:22 UTC, u12206050 commented
Ah cool I didn't even know about the fields property. How does it work?

On Fri, 27 May 2022, 17:33 Rijk van Zanten, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In app/src/displays/related-count/index.ts
> <https://github.com/directus/directus/pull/12711#discussion_r883726100>:
>
> > +			meta: {
>
> +				width: 'half',
>
> +				interface: 'system-input-translated-string',
>
> +				options: {
>
> +					label: '$t:displays.formatted-value.suffix_label',
>
> +					trim: false,
>
> +				},
>
> +			},
>
> +			schema: {
>
> +				default_value: '$t:items',
>
> +			},
>
> +		},
>
> +	],
>
> +	types: ['alias'],
>
> +	localTypes: ['m2m', 'o2m', 'translations', 'm2a', 'file', 'files'],
>
> +	fields: ['count()'],
>
>
> Lets update this to use a function style fields property that actually
> returns the current field name wrapped in the count() function, rather than
> overriding the adjust-fields-for-displays with custom logic based on the
> existence of () 👍🏻
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/directus/directus/pull/12711#pullrequestreview-987671487>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABSVMWSZMQEEWLQ7RHMFGZTVMDTMXANCNFSM5TIFRXQA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-05-27 16:45 UTC, rijkvanzanten commented
> Ah cool I didn't even know about the fields property. How does it work?
> […](#)

Instead of setting an array of fields, it can be a function get gets some context around the current configured field that's called, so you can do something like:

```js
fields: () => {
  return ['id'];
}
```

or in more practical sense:

```js
fields: (options, { field }) => [`count(${field.field})`]
```

2022-05-27 17:40 UTC, u12206050 commented on app/src/displays/related-count/index.ts
> +	fields: ['count()'],
That is why I had to override the adjust-fields-for-displays

2022-05-27 17:40 UTC, u12206050 commented on app/src/displays/related-count/index.ts
> +	fields: ['count()'],
That is why I had to override the adjust-fields-for-displays

2022-05-28 18:46 UTC, u12206050 commented
> > Ah cool I didn't even know about the fields property. How does it work?
> > […](#)
> 
> Instead of setting an array of fields, it can be a function get gets some context around the current configured field that's called, so you can do something like:
> 
> ```js
> fields: () => {
>   return ['id'];
> }
> ```
> 
> or in more practical sense:
> 
> ```js
> fields: (options, { field }) => [`count(${field.field})`]
> ```

So I've tried this, seems like I already made use of is, and had to override `adjust-fields-for-display` otherwise the field just gets prepended making the query invalid. ie. `relationship.count()` it needs to be `count(relationship)`

2022-06-19 07:35 UTC, u12206050 commented
@azrikahar Would be nice to get this in the next release. Small PR but very nice functionality :)

2022-06-19 12:25 UTC, benhaynes commented
I'm so surprised we don't have this "count" display yet. I defer to the engineers on if the PR is ready... but here are a few quick thoughts.

-  We should use the existing "Singular Unit" and "Plural Unit" settings within collection translations. @rijkvanzanten thoughts on adding these two fields to the main collection page too? They'd be more visible and easier to configure when not multilingual. Also, when _not_ configured let's ensure "Item" and "Items" is used as a fall back.
- This display should mention/show that the singular/plural names configured above are used (perhaps as a notice or placeholders) and perhaps offer overrides for each.
- Could we broaden this to work with JSON, arrays and CSVs too?
- Many of the formatting options available within "Format Value" display would be nice (which would always be true)... @rijkvanzanten I wonder if we should make those global for the field so they work with every display... or should we merge this display into that... or should we add those options to this display? 🤔

2022-06-20 05:29 UTC, azrikahar commented
> @azrikahar Would be nice to get this in the next release. Small PR but very nice functionality :)

Granted I'm not opposed to it per se, I believe this is currently not slated for the next release based on our internal tracker (my understanding would be fixes takes precedence over new features as of now), so I'll have to defer to @rijkvanzanten for this. 👍

2022-06-20 15:13 UTC, rijkvanzanten commented
> We should use the existing "Singular Unit" and "Plural Unit" settings within collection translations. @rijkvanzanten thoughts on adding these two fields to the main collection page too? They'd be more visible and easier to configure when not multilingual. Also, when not configured let's ensure "Item" and "Items" is used as a fall back.

Yeah, and the collection translations setup needs to use the updated translations inputs, rather than the older repeater style config it's still using currently 👍🏻 

> Many of the formatting options available within "Format Value" display would be nice (which would always be true)... @rijkvanzanten I wonder if we should make those global for the field so they work with every display... or should we merge this display into that... or should we add those options to this display? 

While some displays could benefit from some of those shared options, I definitely don't think it applies to most of them. Lets not convolute the field configuration setup by trying to configure display information on both the field _and_ display level 👍🏻

2022-06-20 18:23 UTC, benhaynes commented
> Yeah, and the collection translations setup needs to use the updated translations inputs, rather than the older repeater style config it's still using currently 👍🏻

Beautiful!! I didn't think about that, but it really simplifies this and solves both those issues.

> While some displays could benefit from some of those shared options, I definitely don't think it applies to most of them. Lets not convolute the field configuration setup by trying to configure display information on both the field and display level 👍🏻

Hmm, ok! So then we'd want to recreate the "Conditional Styles" option from within the "Formatted Value" Display. We should at least be consistent with that GUI across different Displays.

2022-06-21 05:50 UTC, u12206050 commented
I'm a bit unsure of changes to actually implement or are the things @benhaynes and @rijkvanzanten are talking about something that is done while merging in?

2022-06-21 14:42 UTC, benhaynes commented
> I'm a bit unsure of changes to actually implement or are the things @benhaynes and @rijkvanzanten are talking about something that is done while merging in?

We have "Conditional Formatting" on other Displays which allows you to change the style (color, etc) of the display output based on the value (in this case, a count). It's useful here too, as you  might need to show `0 Items` in **red**, or when you have `10+ items` in **green**, etc.

Should be easy to copy from this other display. The main applicable style options here are color and icon.

https://github.com/directus/directus/blob/main/app/src/displays/formatted-value/index.ts#L158

2022-06-22 17:14 UTC, u12206050 commented
Done. Hope it is ok that we always show a value even if it is 0. Logically it just makes sense in most scenarios.

2022-06-22 18:41 UTC, u12206050 commented
Sorry was struggling getting eslint to work on my local machine so had to fix the errors manually.
Should be all good now.

2022-08-10 20:05 UTC, u12206050 commented
@benhaynes @rijkvanzanten I have cleaned this PR up as well, reusing the formatted field display to actually display the options instead of duplicating it.

![o2mcounter](https://user-images.githubusercontent.com/6641242/184009717-d2bc6df9-581c-4d2b-aac6-a4d94178cb0a.gif)

2022-11-15 14:05 UTC, u12206050 commented
@benhaynes would the latest aggregation query and functions on fields be able to solve this if just exposed as being selectable in columns or is this still the way we would want it?

2022-11-15 14:29 UTC, benhaynes commented
> @benhaynes would the latest aggregation query and functions on fields be able to solve this if just exposed as being selectable in columns or is this still the way we would want it?

Oooh, I like that! I defer to @rijkvanzanten on the technical feasibility of this (how we track fields versus aliases)... but I like the idea, just like how it's displayed in the filters.

2022-11-15 14:58 UTC, rijkvanzanten commented
Aggregations run on a set of data, not single rows, so this would be exclusive to function support 👍🏻

2022-11-16 07:28 UTC, u12206050 commented
> 

Ok, nice. So do we close this PR in favour of using functions as columns instead or? @rijkvanzanten

2022-11-16 16:29 UTC, rijkvanzanten commented
Yeah lets do it 👍🏻

2022-11-16 16:29 UTC, closed without merging