Docs: Self-Hosted Section + Updated Quickstart Guide
directus/directus pull request #13005
Opened 2022-04-26 04:33 UTC by erondpowell

TODO:
- [ ] Create Self Hosted Section
- [ ] Move Installation and Localhost Quickstart Guide into Self Hosted
- [ ] Re-edit getting-started > quickstart for the Cloud
- [ ] Update Media

- [ ] Request Manager Review + Comments
- [ ] Apply Manager's Suggested Edits
- [ ] Final Proofread
- [ ] Request For Lori's Proofread

2022-04-26 19:19 UTC, lmaupas commented on docs/getting-started/quickstart.md
> +_It should take around 90 seconds for the Cloud Project to build out. During this time, a link will be sent to the email
g

2022-04-27 21:19 UTC, erondpowell commented
@rijkvanzanten @benhaynes It's time to take a look at this bad boi.

2022-05-02 17:41 UTC, erondpowell commented
@benhaynes
Another thing to note: on the quickstart guide, I would like to add a conclusion.
It will point out several right tracks users can follow to keep learning.
- bite-size tutorials to learn how to build directus from scratch
- bite-size tutorials starting with demo data
- crashcourse
- contact us for enterprise info
- community
- etc.

2022-05-13 16:17 UTC, erondpowell commented
@rijkvanzanten I'm not 100% sure why this is throwing a merge conflict. `quickstart` was simply edited and `plesk` was moved to self-hosted with no edits (along with 11 other self-hosted start guides which don't appear here).

I haven't seen this before and I am not 100% how to merge the conflict properly. Any tips??

2022-05-26 16:22 UTC, erondpowell commented
@rijkvanzanten Do you mind "reviewing" this branch so it can get merged?

2022-05-26 16:31 UTC, erondpowell commented
@rijkvanzanten You mind "reviewing" this or assign me as a reviewer so I can merge it?

2022-05-26 17:49 UTC, rijkvanzanten requested changes
Couple tiny tweaks. Other than that, LGTM!

2022-05-26 17:49 UTC, rijkvanzanten commented on docs/getting-started/quickstart.md
> +don't have a Github account or prefer not to use this login method, email-and-password login is available as well.
```suggestion
life easier by giving you the option to create and log in to your free Cloud Account automatically with GitHub. If you
don't have a GitHub account or prefer not to use this login method, email-and-password login is available as well.
```

2022-05-26 17:49 UTC, rijkvanzanten commented on docs/getting-started/quickstart.md
> +4. Leave the other settings at default and click <span mi btn>arrow*forward</span> and the **"Optional System Fields"**
```suggestion
4. Leave the other settings at default and click <span mi btn>arrow_forward</span> and the **"Optional System Fields"**
```

2022-05-27 18:09 UTC, erondpowell commented
> Couple tiny tweaks. Other than that, LGTM!

Ok. It's good. I'm still blocked from hitting the big red button.

2022-05-27 19:00 UTC, rijkvanzanten approved these changes

2022-05-27 20:34 UTC, merged