backing-directus first draft
directus/directus pull request #13122
Opened 2022-05-04 17:03 UTC by erondpowell

TODO: 

- [ ] First Draft
- [ ] Submit for editor review
- [ ] Apply all edits
- [ ] Final Proofread
- [ ] Convert Draft PR to PR to signal ready for merge

2022-05-28 00:53 UTC, erondpowell commented
@benhaynes @rijkvanzanten 
I just proof-edited this. I think it is p much good enough to go live for now.
I will update it as we update the github sponsors program and launch the swag shop, etc.

2022-06-03 22:02 UTC, rijkvanzanten requested changes
LGTM! The only thing I'd like to update is the merchandise bit, which reminds me @benhaynes we should update the sponsor tiers now that we're looking at a more dedicated merch store 👍🏻

2022-06-06 15:06 UTC, erondpowell commented on docs/getting-started/backing-directus.md
> +Buy some of our _totally sweet_ merchandise! This is a great way to support Directus. You get some swag, and we get some
mhmm! Just pre-writing it since I'm in the doc. I am HTML commenting it out for now. Sound Good?

2022-06-06 15:09 UTC, rijkvanzanten commented on docs/getting-started/backing-directus.md
> +Buy some of our _totally sweet_ merchandise! This is a great way to support Directus. You get some swag, and we get some
That works!

2022-06-06 15:17 UTC, erondpowell commented
Swell, one last pass to proofread now. Can you approve this for a merge?

2022-06-06 15:19 UTC, erondpowell commented
Swell. Proofreading then merging. @rijkvanzanten can you mark as reviewed and approved?

2022-06-06 15:33 UTC, rijkvanzanten approved these changes

2022-06-06 15:33 UTC, rijkvanzanten commented
The linter CI crapping out is resolved in https://github.com/directus/directus/pull/13755, so don't worry about that in this PR 👍🏻

2022-06-06 16:21 UTC, merged