Fix form field label responsiveness
directus/directus pull request #13141
Opened 2022-05-05 14:38 UTC by azrikahar

Fixes #13138 

## Before

The form field label is not wrapping in lower width:

![chrome_03mSXe9wkr](https://user-images.githubusercontent.com/42867097/166947438-d652f338-4097-4cfc-adb7-c51102d8f38f.png)

This is due to the `width: max-content` forcing it to at least be as wide as itself and not wrap. However if we just remove this, the `.ctx-arrow` will be almost out of view since it has `position: absolute`:

![chrome_Ukz6gAAUST](https://user-images.githubusercontent.com/42867097/166947457-e648a343-a85b-40ac-8dff-367f03968f45.png)

So we'll need to tweak it as well.

## After

![chrome_BOsW1af0xL](https://user-images.githubusercontent.com/42867097/166947308-458c0fbf-9b44-407c-b4f5-cd180df9343e.png)

2022-05-05 15:12 UTC, benhaynes commented
My only comment would be that on _Desktop_ we can still use the tooltip to show longer labels (without upsetting the form flow). Happy to discuss, as I know some care less about design and just want to see the labels without hovering, but it's good to think about, especially if we [adopt a new form gird that allows 3/4+ side-by-side fields](https://github.com/directus/directus/discussions/9161).

2022-05-06 05:34 UTC, azrikahar commented
> My only comment would be that on _Desktop_ we can still use the tooltip to show longer labels (without upsetting the form flow). Happy to discuss, as I know some care less about design and just want to see the labels without hovering, but it's good to think about, especially if we [adopt a new form gird that allows 3/4+ side-by-side fields](https://github.com/directus/directus/discussions/9161).
> 
> So my question: is this update only for mobile... or any time there isn't enough room?

This update currently will apply any time there isn't enough room! So this is a very a good point here. Here are the comparisons:

- A: Before this PR

   https://user-images.githubusercontent.com/42867097/167069769-c93835b5-3dcc-4f3f-8149-1fcbb598ff6e.mp4

- B: This PR before the desktop-only suggested change

   https://user-images.githubusercontent.com/42867097/167069792-dbcb28f5-2d68-43c6-a221-1651463f0dd7.mp4

- C: This PR after the desktop-only suggested change

   https://user-images.githubusercontent.com/42867097/167072732-2a797560-d21b-417f-a5f6-43f39a8e5f89.mp4

---

Definitely can see how B is disrupting the flow right of the bat as mentioned 👍 

Does C fit the tooltip + not upsetting form flow design? One slight "issue" is just the `Value Edited` tooltip that shows when a value is edited will be "overridden" by the `<v-text-overflow>`'s tooltip. Do we want to tweak it to prevent this as well? If yes, any suggestions? 🤔

2022-05-06 16:28 UTC, benhaynes commented
Awesome work @azrikahar! Option C for sure.

For the tooltip, I think we could try to combine the two, as needed. So:

```
Value Edited: A Very Long Field Name Goes Here
```

Or...

```
A Very Long Field Name Goes Here (Value Edited)
```

2022-05-10 13:22 UTC, azrikahar commented
Updated and went with the first suggestion:

```
Value Edited: A Very Long Field Name Goes Here
```

Initially was gravitating to the second suggestion, but I think the first one may be better in the sense  that the "Value Edited" is more readily readable if it's in the beginning.

https://user-images.githubusercontent.com/42867097/167636407-cb24e550-0b61-489d-aa83-3f388cdfc366.mp4

---

On second thought, opted to use a new translation key `edited_field` rather than simple string concatenation so that RTL languages can move it to the end (which is their beginning).

2022-05-10 13:48 UTC, rijkvanzanten requested changes
v-text-overflow already renders a tooltip when the ellipsis are rendered. Instead of emitting an event to the parent, and having a "double tooltip", lets add props to v-text-overflow for a "prefix" and "suffix" to the tooltip it renders 👍🏻

2022-05-10 14:48 UTC, azrikahar commented
Added props `tooltipPrefix` and `tooltipSuffix` (used `tooltip` prefix to reduce confusion), though still had to keep the v-tooltip on the span wrapping the v-text-overflow, or else there won't be any tooltip when the text never overflows.

2022-05-10 14:59 UTC, rijkvanzanten commented
On third thought: Does it make more sense to show the "Edited" on hover of the dot, rather than the whole field name? That also greatly reduces this complexity in trying to merge two different tooltips but only at certain times 🤔

2022-06-07 13:39 UTC, azrikahar commented
> Is that last suggested change something you can add? 🙂

Done 👍 now uses a span, and propagated the same change to group detail and accordion (which were added in #10147):

https://user-images.githubusercontent.com/42867097/172394574-f052a144-e053-4b18-b21d-4d758e578bd4.mp4

2022-06-08 11:05 UTC, br41nslug approved these changes

2022-06-08 14:39 UTC, rijkvanzanten approved these changes

2022-06-08 14:39 UTC, merged