Fix clear value for relational interfaces
directus/directus pull request #13224
Opened 2022-05-11 10:17 UTC by azrikahar

Fixes #12854

## Problem

Currently "to many" relational interfaces (or ones using `useRelationMultiple`) requires the initial payload to at least be an empty array. When the `props.value` is undefined, it is defaulted to an empty array as well.

However when we use Clear Value, it emits `null` value (not undefined), which breaks them:

https://user-images.githubusercontent.com/42867097/167824367-6f134567-4b13-451d-985d-aee486eee713.mp4

## Solution

Now useRelationMultiple will clear the value properly, and ensure it being `undefined` or `[]` depending on the initial value to not stage any edits. 

However if there are any existing values (not newly created or updated ones, those will still be cleared), we will stage them for deletion instead.

https://user-images.githubusercontent.com/42867097/167826057-7a18fdee-3a1f-4836-a251-dbc85b208aa7.mp4

2022-05-11 10:22 UTC, azrikahar commented on app/src/interfaces/list-o2m/list-o2m.vue
> +import { Filter } from '@directus/shared/types';
Only removing an unused variable here 👍

2022-05-11 13:45 UTC, rijkvanzanten commented
> However if there are any existing values (not newly created or updated ones, those will still be cleared), we will stage them for deletion instead.

I'm wondering if this is needed. The API will also clear everything if `null` is submitted IIRC, so we might be able to just have the app handle `null` as `[]`, and be done 🤔

2022-05-11 13:45 UTC, rijkvanzanten requested changes
However if there are any existing values (not newly created or updated ones, those will still be cleared), we will stage them for deletion instead.
I'm wondering if this is needed. The API will also clear everything if null is submitted IIRC, so we might be able to just have the app handle null as [], and be done 🤔

2022-05-13 13:08 UTC, azrikahar commented
> > However if there are any existing values (not newly created or updated ones, those will still be cleared), we will stage them for deletion instead.
> 
> I'm wondering if this is needed. The API will also clear everything if null is submitted IIRC, so we might be able to just have the app handle null as [], and be done 🤔

It was initially due to the existing items persisting visually after being cleared:

https://user-images.githubusercontent.com/42867097/168288421-f8a4563c-5f51-4522-a2a2-6e0a48d57492.mp4

hence I opted to use the current approach. I do agree it'll feel more like the previous interaction if we fully clear the items, so I tried to implement it here but there's a slight issue where the Add Existing drawer will still filter out existing items:

https://user-images.githubusercontent.com/42867097/168289439-ef8f3276-bbf8-457a-969b-48b1ec2b667f.mp4

It's due to the following filter to exclude an existing entry's relational items:

https://github.com/directus/directus/blob/c30b041654af1111b8bb3cbdf2200c790032958d/app/src/interfaces/list-m2m/list-m2m.vue#L291-L299

So not sure how to "toggle" this off after a user clears the value to full empty to ensure they can select the existing items again, at least without even more changes I presume 🤔 (and will need to "toggle" this on back again when user uses Undo Value)

2022-06-07 20:01 UTC, rijkvanzanten commented on app/src/composables/use-relation/use-relation-multiple.ts
> +			target.value.delete = fetchedItems.value.map((item) => item[pkField]);
Should clear stage every item for deletion, or should this be `[]` as well with a call elsewhere to refresh the fetched items?

2022-06-08 14:15 UTC, rijkvanzanten approved these changes

2022-06-08 14:16 UTC, merged