Improve extension create onboarding
directus/directus pull request #14475
Opened 2022-07-16 20:56 UTC by u12206050

## Description

Update default build path to match better where the built file should be copied to.
Add a `npm run dev` script useful during development
Add a hint to change the `dist` part in the package.json file to the extensions file to automatically move the built or developing extension to.

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [x] Refactor / codestyle updates
- [ ] Other, please describe:

2022-07-18 16:31 UTC, rijkvanzanten requested changes

2022-07-20 20:04 UTC, rijkvanzanten requested changes

2022-07-20 20:04 UTC, rijkvanzanten commented on packages/extensions-sdk/src/cli/commands/create.ts
> +			path: `dist/${type}s/${name}/index.js`,
I don't think this is accurate. The default `build` command renders to `dist/index.js`, not `dist/panels/my-panel/index.js` for example

2022-07-20 20:05 UTC, rijkvanzanten commented
I've undone the proprietary / (I believe) wrong changes so we can merge the enhancement that is the dev command. Happy to keep discussing the other changes in a separate discussion/pr :)

2022-07-20 20:05 UTC, rijkvanzanten approved these changes

2022-07-20 20:06 UTC, merged

2022-07-20 20:07 UTC, u12206050 commented
Ok no problem. Yeh I guess in the end it might be different how each developer develops their extension.