Always transform rollup-styles plugin.
directus/directus pull request #14740
Opened 2022-07-29 08:51 UTC by u12206050

Fixes styles not updating during watch.

At first I thought it was a tailwind/postcss issue, but found out in the end it that the styles-plugin was being cached and not being transformed again on every change.

![beforeFix14739](https://user-images.githubusercontent.com/6641242/181722127-e0bfbd52-2b55-4939-b241-fec0fb030419.gif)

![afterFix](https://user-images.githubusercontent.com/6641242/181721951-eb019afd-81cf-445a-b295-b57ed43bc2cb.gif)

Fixes #14739 

## Type of Change

- [x] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [ ] Performed a self-review of the submitted code

2022-07-29 15:14 UTC, nickrum requested changes
Rather than disabling rollups transform cache, I feel like we should find out why rollup doesn't invalidate the cache. As far as I understand, when the html changes and this affects one of tailwinds util classes, it will regenerate the css file imported by your extensions. Shouldn't this also change the source transformed by the styles plugin and thus invalidate the cache?

2022-07-29 15:19 UTC, rijkvanzanten commented
@nickrum Feels like we were on the same train of thought: https://github.com/directus/directus/issues/14739#issuecomment-1199511980

> If this issue happens only with Tailwind, I'd like to keep investigating the original source, as stylesPlugin.shouldTransformCachedModule = () => true; will slow down every use, not just fix the Tailwind problem 🤔

2022-07-29 15:20 UTC, rijkvanzanten commented
> it will regenerate the css file imported by your extensions

I'm wondering if this is where it's falling apart. The css file isn't imported by the extension, but forced in through the postcss plugin if I understand #14739 correctly. That might mean that the update in the component html/js itself doesn't trigger the css file rebuild 🤔

2022-07-29 15:28 UTC, nickrum commented
That could be 🤔 I was under the impression that the css file has to at least be imported _somewhere_. But this could very well be related to postcss doing some import magic and rollup not catching that.

2022-07-29 16:04 UTC, rijkvanzanten commented
> That could be 🤔 I was under the impression that the css file has to at least be imported _somewhere_. But this could very well be related to postcss doing some import magic and rollup not catching that.

I'm wondering if the simple fix here could be to use a 

```html
<style>
@include './path/to/tailwind.css';
</style>
```

in the vue component to ensure the changes are caught 🤔

2022-07-29 16:59 UTC, u12206050 commented
> 

That doesn't seem to even load tailwind at all. so unfortunately not.

2022-07-29 17:02 UTC, u12206050 commented
> Rather than disabling rollups transform cache, I feel like we should find out why rollup doesn't invalidate the cache. As far as I understand, when the html changes and this affects one of tailwinds util classes, it will regenerate the css file imported by your extensions. Shouldn't this also change the source transformed by the styles plugin and thus invalidate the cache?

This isn't disabling rollup's transforms cache btw, only for the one plugin. Since the tailwind plugin is the only plugin with knowledge of wether or not a new style has been added or not.

2022-07-29 17:04 UTC, u12206050 commented
Interesting though, applying tailwind styles via `@apply` inside the style tags does work.
```
<style>
.test {
	@apply bg-blue-300;
}
</style>
```
to
```
<style>
.test {
	@apply bg-red-300;
}
</style>
```
WORKS.

BUT

```
<template>
  <div class="bg-blue-500">{{ value }}</div>
</template>
```  
to this
```
<template>
  <div class="bg-red-500">{{ value }}</div>
</template>
```
Doesn't work.

2023-04-10 20:50 UTC, rijkvanzanten commented
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

2023-04-10 20:50 UTC, closed without merging