Made DrawerItem, DrawerBatch global components
directus/directus pull request #14751
Opened 2022-07-30 08:08 UTC by j0hnfl0w

## Description

It is very comfortable to use this private views in custom extensions, like custom modules, created a different way of looking at collections, but use the same drawers for editing. Are there will be some breaking changes with this views for extensions?
Like was said here? https://github.com/directus/directus/discussions/13139
Tested it with my custom npm package for "@directus/app".

Fixes #

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

2022-08-01 16:41 UTC, rijkvanzanten requested changes

2022-08-01 16:41 UTC, rijkvanzanten commented on app/src/views/register.ts
> +	app.component('DrawerBatch', DrawerBatch);
I think we might want to register these under `/app/src/components/register.ts` for consistency's sake 👍🏻

2022-08-02 08:46 UTC, j0hnfl0w commented
@rijkvanzanten Moved registration to /src/components/register, but before they were async
const DrawerItem = defineAsyncComponent(() => import('./private/components/drawer-item.vue'));
Now they are not async, will it impact perfomance ?
And also I tried locally to use them not async and they wont work.

2022-08-02 13:53 UTC, rijkvanzanten approved these changes

2022-08-02 13:55 UTC, rijkvanzanten commented
> Now they are not async, will it impact perfomance ?

Only slightly. It will make the initial load of the app's login page a hair slower, but it will also make the load performance after login a hair faster. At the end of the day, initial loading time of the app isn't as important[^1] as a smooth UX while using the app, so it doesn't matter too much.

[^1]: This is a big difference between "regular websites" and "backend admin apps" like the Directus studio 🙂

2022-08-02 13:55 UTC, merged