Missed Kurdish languages
directus/directus pull request #14858
Opened 2022-08-04 21:44 UTC by halwesit

The Kurdish language has 2 main dialects (Sorani - Iraq, Kurmanji - Turkey) that are so different based on the typography and the meaning of the words. for example the Kurdish Sorani is an RTL language, based on the Arabic script. The Kurdish Kurmanji is LTR, based on the Latin script.

## Description

Fixes #

## Type of Change

- [ ] Bugfix
- [+] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [+] New / updated tests are included
- [ ] All tests are passing locally
- [ ] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

2022-08-05 19:30 UTC, rijkvanzanten commented
@halwesit Are you planning on providing the translations for these dialects as well? I'm a tad worried that this will add the language to the platform, but that nobody will actually contribute the correct translations 🤔 The current Kurdish (which I believe is Sorani) is only at 4%, so I'm a little worried this will add another untranslated language 👀

2022-08-05 19:35 UTC, halwesit commented
Actually, my dialect is Sorani Kurdish ku-IQ, and that 4% was translated by me, I did it because I thought it is Sorani Kurdish, but when I realized that its for Kurmanji Kurdish ku-TR, I stopped doing it. 
I'm unable to translate Kurdish Kurmanji ku-IQ because it's far different from my dialect Kurdish Sorani.

2022-08-05 20:08 UTC, rijkvanzanten commented
Ah gotcha! I've updated Crowdin (https://locales.directus.io/project/directus) to now show Kurmanji and Sorani separate 🙂 Thanks!

2022-08-05 20:14 UTC, halwesit commented
thank you so much.

2022-08-05 20:17 UTC, rijkvanzanten requested changes

2022-08-05 20:17 UTC, rijkvanzanten commented on app/src/lang/available-languages.yaml
> +ku-IQ: Kurdish Sorani (Iraq)
```suggestion
kmr-TR: Kurdish Kurmanji (Turkey)
ckb-IR: Kurdish Sorani (Iraq)
```

2022-08-05 20:18 UTC, rijkvanzanten commented
I've updated the locale codes to match what our translations provider relies on: https://github.com/directus/directus/pull/14889/files

2022-08-05 20:18 UTC, rijkvanzanten approved these changes

2022-08-05 20:18 UTC, merged

2023-04-18 01:56 UTC, roj1512 commented
@halwesit These codes are not very appealing. I Kurdish should either not have a country code.