Don't show circular field when creating new item
directus/directus pull request #15054
Opened 2022-08-12 19:34 UTC by u12206050

## Description

Just a refactor fix of the issue.

Turns out the issue is only on create, and since it will anyways be empty, we don't need to show the field during creation.

Fixes #15053

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [x] Refactor / codestyle updates
- [ ] Other, please describe:

2022-08-15 20:31 UTC, u12206050 commented
@rijkvanzanten Could you do a hot fix release on this one? It is stopping all our users from creating new items since the field is required.

2022-08-17 12:02 UTC, br41nslug requested changes
When testing this branch im still getting the "missing required field error" when i tick the `required` toggle. 

![image](https://user-images.githubusercontent.com/9389634/185113275-735af925-e241-40f1-b00c-740d6718c75a.png)

I believe this is due to the change to a `filter` function instead of a `map` without moving the `set(field, 'meta.readonly', true);` outside of the `filter` loop.

2022-08-18 10:48 UTC, u12206050 commented on app/src/views/private/components/drawer-item.vue
>  						set(field, 'meta.readonly', true);
map and filter both returned the same references ie. field.
Map simply modified the field before returning it, and filter is also modifying it, but it is also filtering out the one field that is the circularField when creating, else during update it sets the field to readonly

2022-08-18 10:51 UTC, u12206050 commented
> When testing this branch im still getting the "missing required field error" when i tick the `required` toggle.
> 
> ![image](https://user-images.githubusercontent.com/9389634/185113275-735af925-e241-40f1-b00c-740d6718c75a.png)
> 
> I believe this is due to the change to a `filter` function instead of a `map` without moving the `set(field, 'meta.readonly', true);` outside of the `filter` loop.

The error you are getting regarding the ID field, might be due to another issue I believe. Is the ID there an auto-increment ID field?

2022-08-18 11:10 UTC, br41nslug commented on app/src/views/private/components/drawer-item.vue
>  						set(field, 'meta.readonly', true);
It does work damn, gotta love JS 🤔 It does feel semantically wrong but was definitely more of a "how i think it should work" comment 😇

2022-08-18 11:11 UTC, br41nslug commented
Can it not be an auto increment? i didnt get that from the linked ticket 😬

2022-08-18 11:13 UTC, u12206050 commented
> 

It probably can, that was just a question I asked, in regards to why you got that error. Not really anything more to do with this PR.

2022-09-04 10:06 UTC, Nitwel commented
This PR will be closed as the underlying issue should be resolved by #15386.

2022-09-04 10:06 UTC, closed without merging