#1311 check existing email before user creation
directus/directus pull request #1551
Opened 2017-06-08 12:20 UTC by Toothless1118

I fixed #1311 issue, please check

2017-06-08 16:15 UTC, wellingguzman requested changes
This is looking good, would be awesome if time exists, that you could add it to API 1.1 and Directus 6.4, otherwise let me know so I could merge it

2017-06-08 16:15 UTC, WellingGuzman commented on api/api.php
> +            if ($table == 'directus_users') {
Also this looks good.

Can you check https://github.com/directus/directus/blob/master/api/routes/A1/Entries.php#L23 and implement it as well for **API 1.1 for 6.4 on version/6.4 branch**

2017-06-08 16:27 UTC, Toothless1118 commented on .gitignore
> +bin/composer
These files created when installing composer.
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

2017-06-08 16:35 UTC, WellingGuzman commented on .gitignore
> +bin/composer
Thanks, it won't hurt, but we shouldn't be tracking (in this case untracking) those, the person installing should clean the directory after installation, and I believe the composer-setup clean all this.

2017-06-08 16:41 UTC, Toothless1118 commented on api/api.php
> +            if ($table == 'directus_users') {
I have implemented it on Entries.php and pushed it again. Please check.

2017-06-14 00:40 UTC, WellingGuzman commented
Hey @Toothless1118 thanks for the contribution.

I'm wondering if you are going to complete the whole issue from https://github.com/directus/directus/issues/1311 or are just going to complete the server-side creating the update or create approach?

2017-07-08 19:07 UTC, closed without merging