Added support for Supabase Storage
directus/directus pull request #15631
Opened 2022-09-18 02:04 UTC by jawngee

## Description

- [x] Adds support for using Supabase Storage as a storage location.

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

2022-09-19 09:55 UTC, jawngee commented
Added fixes for linting and tests.

2022-10-11 20:42 UTC, rijkvanzanten requested changes
Thanks @jawngee! 

Lets move the CSV delimiter changes to a separate PR to not conflate the features here. Other than that, this is really exciting 🙂

2022-10-11 20:42 UTC, rijkvanzanten commented on api/package.json
> +    "@directus/drive-supabase": "workspace:*",
Indentation inconsistency

2022-10-11 20:42 UTC, rijkvanzanten commented on api/src/middleware/respond.ts
> +				);
Lets do any non-supabase related features / enhancement in separate PRs 👍🏻

2022-12-23 21:05 UTC, rijkvanzanten commented
Closing this as the PR became stale. #16830 is a great follow up, we're tracking final implementation in #16903

2022-12-23 21:05 UTC, closed without merging