Fix empty form info on translations
directus/directus pull request #15757
Opened 2022-09-26 12:48 UTC by Nitwel

## After

![grafik](https://user-images.githubusercontent.com/22577866/192280388-a9b72bf3-9ca4-483f-a930-baa8db857304.png)

![grafik](https://user-images.githubusercontent.com/22577866/192280444-86430beb-93a6-463e-bb4a-885f1045efd8.png)

Fixes #15751

2022-09-26 13:41 UTC, Nitwel commented
We can hide the circle with some css for sure!

2022-09-26 13:43 UTC, Nitwel commented
Would look like this.

![grafik](https://user-images.githubusercontent.com/22577866/192292179-70201574-58aa-4374-860d-7f20e32e29b6.png)

![grafik](https://user-images.githubusercontent.com/22577866/192292226-cdde9a62-37e6-458b-9a91-4c8ea11058a3.png)

2022-09-26 15:20 UTC, benhaynes commented
Looks good!

2022-10-14 08:59 UTC, br41nslug approved these changes
LGTM 👍

2022-10-14 18:46 UTC, rijkvanzanten requested changes

2022-10-14 18:46 UTC, rijkvanzanten commented on app/src/interfaces/translations/translations.vue
> +		}
LBTM! 

Lets instead use a prop on v-info to enable/disable the icon

2022-10-14 18:50 UTC, rijkvanzanten commented on app/src/interfaces/translations/translations.vue
> +		}
I'll take care of this now 👍🏻

2022-10-14 22:59 UTC, rijkvanzanten approved these changes

2022-10-14 23:18 UTC, merged