Add 'loading' field to images in wysiwyg editor
directus/directus pull request #15791
Opened 2022-09-28 15:32 UTC by izoukhai

## Description

<img width="855" alt="Capture d’écran 2022-09-28 à 17 30 57" src="https://user-images.githubusercontent.com/44984965/192821588-ae150b46-decb-4d1a-a816-d7128b5b093e.png">

Add an `loading` field when uploading images with wysiwyg

Fixes #15790

## Type of Change

- [ ] Bugfix
- [X] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [   ] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

2022-09-28 16:52 UTC, benhaynes commented
Thank you! I wonder why URL wasn't capitalized per our Title Formatter. Also, I think one of those first two fields should be full with and we move the loading field up so the form feels more balanced.

2022-10-02 16:59 UTC, izoukhai commented
> 

yep good idea, I pushed the modification :)

2022-10-04 09:56 UTC, br41nslug requested changes
Thanks for your contribution 😄 lets remove [api/directus-sqlite](https://github.com/directus/directus/pull/15791/files#diff-c60ba541cc749f58d89ea2f574aaad7dcf7120d4cb8ee824c3efedd09a044bf9) however which im assuming is an accidentally committed SQLite database.

2022-10-04 09:56 UTC, br41nslug commented on app/src/interfaces/input-rich-text-html/input-rich-text-html.vue
> +import SelectDropdown from '../select-dropdown/select-dropdown.vue';
These are not needed as `v-select` is registered globally.
```suggestion
```

2022-10-04 09:56 UTC, br41nslug commented on app/src/interfaces/input-rich-text-html/input-rich-text-html.vue
> +	components: { Editor, VSelect },
```suggestion
	components: { Editor },
```

2022-10-04 09:56 UTC, br41nslug commented on packages/shared/src/types/settings.ts
> +	loading: string | null;
```suggestion
	loading: 'lazy' | 'eager' | null;
```

2023-04-10 21:30 UTC, rijkvanzanten commented
Closing this for now, as the review has gone ignored

2023-04-10 21:30 UTC, closed without merging