fix (display-filesize): adjust handler argument to be read as `value`
directus/directus pull request #15840
Opened 2022-09-30 22:22 UTC by abernh

## Description

Fixes https://github.com/directus/directus/issues/15837

Adjust handler argument to be read as `value`; before it was read as an object from which the key `value` was tried to be extracted (the expected way how the arguments for the `component` function are to be read; suspecting a simple copy/paste mistake as origin of this bug).

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

2022-10-03 10:30 UTC, br41nslug requested changes, later dismissed
I don't think this solves the underlying issue as the object the display should be receiving is formatted like so: 
```json
{
  "value": "170575",
  "interface": null,
  "interface-options": null,
  "type": "bigInteger",
  "collection": "directus_files",
  "field": "filesize"
}
```
If the export is only receiving the `value` then that will need to be fixed on that end. https://github.com/directus/directus/blob/main/app/src/utils/save-as-csv.ts#L58 Seems to be the place where this could have gone wrong.

2022-10-03 14:46 UTC, abernh commented
When I compared the `filesize` `handler` method with the other display `handler` methods they all seemed to receive directly the `value` as first argument and sometimes an `options` object as second.
Though the `component` method seems to use the mentioned structure that you mention here.

The type definition also seems to fit my adjustment

https://github.com/directus/directus/blob/0a5ff6d12a77deb5cdc2d740cc9d643ee44c692e/packages/shared/src/types/displays.ts#L22-L27

Also making the adjustment in https://github.com/directus/directus/blob/main/app/src/utils/save-as-csv.ts#L58 would mean that 
 - either all other (currently working) display handlers would need to be adjusted to handle values 
  - or it would need to be a specific adjustment so that the `filesize` display handler gets values differently formatted than other display handlers

2022-10-04 11:23 UTC, br41nslug approved these changes

2022-10-04 13:53 UTC, azrikahar approved these changes
LGTM!

2022-10-04 14:22 UTC, merged