Import file from local drive
directus/directus pull request #16028
Opened 2022-10-17 12:36 UTC by blocus

## Description

This PR is about the discussion [15972](https://github.com/directus/directus/discussions/15972#discussioncomment-3864789) where I suggested scanning the upload folder and adding the new files to the database. 

## Changes:
- A new file view button asks the API to scan the upload folder. 
- A new file service method `sync` to check if the file exists on the database and add it
- A new endpoint `/files/scan` which runs the sync method of the file service to all files in the upload folder

## Type of Change

- [ ] Bugfix
- [ ] Improvement
- [x] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

2022-10-17 14:48 UTC, rijkvanzanten requested changes
Great idea @blocus! There's a couple points we need to address to make this production ready for the core codebase:

- Make sure it works for every storage adapter instead of just the one called `local` (and for the case where you have multiple adapters configured)
- Make sure we don't ingest directus-generated thumbnails, as that would cause duplicate records
- Add unit/e2e tests
- Add docs

2022-10-17 14:48 UTC, rijkvanzanten commented on api/src/controllers/files.ts
> +		const storageFolder = storage.disk('local');
We can't rely on a hardcoded storage adapter named `local`. `local` is just the default name, but seeing its user created, we can't rely on that name alone

2022-10-17 14:48 UTC, rijkvanzanten commented on api/src/services/files.ts
> +
Wondering if we can make this bit reusable from the regular upload functionality. All the parsing and saving should be the same.

2022-10-17 14:48 UTC, rijkvanzanten commented on api/src/services/files.ts
> +				storage: 'local',
hardcoded `local`

2022-10-17 14:48 UTC, rijkvanzanten commented on api/src/services/files.ts
> +	async sync(relativePath: string): Promise<any> {
Little worried about the performance downside of doing this one at a time 🤔 Wondering if we should maybe try doing this in batches of `n` to improve import performance

2022-10-17 20:45 UTC, blocus commented on app/src/modules/files/routes/collection.vue
> +				<scan-folder :parent="folder" :disabled="createFolderAllowed !== true" />
I will remove the disabled props until we figure out what permission it should have

2022-10-18 14:00 UTC, blocus commented
> * Make sure it works for every storage adapter instead of just the one called `local` (and for the case where you have multiple adapters configured)
> * Make sure we don't ingest directus-generated thumbnails, as that would cause duplicate records
> * Add unit/e2e tests
> * Add docs

I'm not sure I can make the unit/e2e tests 😥 and for docs where should I make it ?

2022-10-20 18:39 UTC, erondpowell commented
> and for docs where should I make it ?

Hey there @blocus ! 
I'm Eron, the technical writer. Welcome to Docs Land!
https://github.com/directus/docs

I'll let you get started by "looking and copying" the styles of the other relevant docs.
Once drafted, I'll take a look and provide any revisions feedback, then takeover for the merge.
Feel free to ping me if you get stuck on anything!

> I'm not sure I can make the unit/e2e tests

@licitdev Weren't you doing a ton of unit tests project recently 🤔  Got any tips?

2022-10-21 02:20 UTC, licitdev commented
> I'm not sure I can make the unit/e2e tests

You may add unit tests for the file controller and service in the follow files respectively.

https://github.com/directus/directus/blob/dbfedb56fe2efe44187abfd31165faaa79ae7780/api/src/controllers/files.test.ts#L1-L8

https://github.com/directus/directus/blob/dbfedb56fe2efe44187abfd31165faaa79ae7780/api/src/services/files.test.ts#L1-L8

2023-04-03 21:36 UTC, rijkvanzanten commented
Heya! Thank you for your contribution. Unfortunately, we can't accept PRs for improvements/features that don't have a prior accepted Discussion and associated Issue (as per the [Contributing Guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests)). This is to ensure that PRs that are opened will actually get the chance to be reviewed, merged, and maintained by the core maintainers. We can reopen and continue this PR review once the requirements have been met. Thank you for your understanding!

2023-04-03 21:36 UTC, closed without merging