Allow form of drawer to show validation errors
directus/directus pull request #16092
Opened 2022-10-21 03:49 UTC by tenebrius

## Description

Fixes #16091

Setting `nested:true` for v-form inside drawer-item, was preventing validation errors was being show inside the drawer

I could not figure out sure why this value was set in #14778 because the fallback message still shows properly if `nested` is not set.

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [ ] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

2022-10-21 09:19 UTC, br41nslug requested changes
Just removing the `nested=true` here is not enough unfortunately. Next to surpressing the validation errors it also hides the empty form message which is popping through with this change

![image](https://user-images.githubusercontent.com/9389634/197161170-6eb9c763-6baf-4d2c-b0be-68e90348bc6f.png)

2022-10-21 10:01 UTC, tenebrius commented
> Just removing the `nested=true` here is not enough unfortunately. Next to surpressing the validation errors it also hides the empty form message which is popping through with this change
> 
> ![image](https://user-images.githubusercontent.com/9389634/197161170-6eb9c763-6baf-4d2c-b0be-68e90348bc6f.png)

2022-10-21 10:03 UTC, tenebrius commented
> Just removing the `nested=true` here is not enough unfortunately. Next to surpressing the validation errors it also hides the empty form message which is popping through with this change
> 
> ![image](https://user-images.githubusercontent.com/9389634/197161170-6eb9c763-6baf-4d2c-b0be-68e90348bc6f.png)

I could not find a way reproduce this. Can you tell me how?

2022-10-21 10:23 UTC, tenebrius commented
I could not get this 

> Just removing the `nested=true` here is not enough unfortunately. Next to surpressing the validation errors it also hides the empty form message which is popping through with this change
> 
> ![image](https://user-images.githubusercontent.com/9389634/197161170-6eb9c763-6baf-4d2c-b0be-68e90348bc6f.png)

I could not reproduce this problem. Can you show me how?

2022-10-21 10:46 UTC, br41nslug commented
This example was with the Files interface but seems to be happening for the m2m interfaces that use the side drawer.

https://user-images.githubusercontent.com/9389634/197178458-f9676b02-a1dc-4a9e-a066-455e01a640f7.mp4

2023-02-07 11:06 UTC, Nitwel commented
I will close this in favor of #17423 . Still thank you a lot for your contribution. ❤️

2023-02-07 11:06 UTC, closed without merging