Issue/16063 replace jest vitest
directus/directus pull request #16146
Opened 2022-10-24 17:48 UTC by DorianCBrwn

## Description
Update tests in api from jest to vitest. 
- Update package.json test scripts to run vitest 
- 81/ 108 tests  are passing

I'm having some trouble finding equivalents for some jest methods/implementations to implement vittest in the remaining 20 tests fully. 
 
Fixes #16063

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

2022-10-24 18:18 UTC, rijkvanzanten commented
Looks like this is partially failing because it's trying to compile the vitest config using `tsc` in the API's build step 🤔 

```
error TS6059: File '/home/runner/work/directus/directus/api/vitest.config.ts' is not under 'rootDir' '/home/runner/work/directus/directus/api/src'. 'rootDir' is expected to contain all source files.
```

2022-10-25 00:28 UTC, paescuj commented
> Looks like this is partially failing because it's trying to compile the vitest config using `tsc` in the API's build step 🤔
> 
> ```
> error TS6059: File '/home/runner/work/directus/directus/api/vitest.config.ts' is not under 'rootDir' '/home/runner/work/directus/directus/api/src'. 'rootDir' is expected to contain all source files.
> ```

The easiest solution to this would be to just use the `js` extension for the config file. This is also what I'm doing in my projects (intellisense still available).

2022-10-25 00:38 UTC, rijkvanzanten commented
@paescuj It's also what we're doing for the app folder itself 🙂

2022-10-25 00:40 UTC, paescuj commented
> @paescuj It's also what we're doing for the app folder itself 🙂

Well, in that case it cannot be wrong 😄

2022-10-27 00:40 UTC, freekrai requested changes
Posted some findings that may help fix some things, looking good.

2022-10-27 00:40 UTC, freekrai commented on api/src/cli/index.test.ts
> +		...actual,
this throws an error and should be `...(actual as object)`

2022-10-27 00:40 UTC, freekrai commented on api/src/cli/index.test.ts
> +beforeEach(vi.clearAllMocks);
also throws an error, but is fine if changed to:

```
beforeEach(() => {
	vi.clearAllMocks();
});
```

2022-10-27 00:40 UTC, freekrai commented on api/vitest.config.ts
> +import { defineConfig } from 'vitest/config';
this file is duplicated and throws an error when both files exist, this one should be removed in favour of the file in `api/src/vitest.config.ts` I think?

2022-10-27 00:40 UTC, freekrai commented on api/src/utils/apply-snapshot.test.ts
> +			const createOneCollectionSpy = vi.spyOn(CollectionsService.prototype, 'createOne').mockImplementation(vi.fn());
this should be `vi.fn().mockReturnValue([])` rather than simply `vi.fn()`

2022-10-27 00:40 UTC, freekrai commented on api/src/utils/apply-snapshot.test.ts
> +			const createFieldSpy = vi.spyOn(FieldsService.prototype, 'createField').mockImplementation(vi.fn());
this should be `vi.fn().mockReturnValue([])` rather than simply `vi.fn()`?

2022-10-27 00:40 UTC, freekrai commented on api/src/utils/apply-snapshot.test.ts
> +			const createOneCollectionSpy = vi.spyOn(CollectionsService.prototype, 'createOne').mockImplementation(vi.fn());
this should be `vi.fn().mockReturnValue([])` rather than simply `vi.fn()`

2022-10-27 00:40 UTC, freekrai commented on api/src/utils/apply-snapshot.test.ts
> +			const createFieldSpy = vi.spyOn(FieldsService.prototype, 'createField').mockImplementation(vi.fn());
this should be `vi.fn().mockReturnValue([])` rather than simply `vi.fn()`

2022-10-27 00:40 UTC, freekrai commented on api/src/utils/apply-snapshot.test.ts
> +			const deleteOneCollectionSpy = vi.spyOn(CollectionsService.prototype, 'deleteOne').mockImplementation(vi.fn());
this should be `vi.fn().mockReturnValue([])` rather than simply `vi.fn()`

2022-10-28 23:23 UTC, DorianCBrwn commented
I have 10 tests left that aren't passing so I wrote up which ones were failing and possible reasons why. There are also some typescript issues I'm having some issues with. I think I should used the [vitest mocked api](https://vitest.dev/api/#vi-mocked) but I'm not really sure why it's not working as expected. 


### Failing Tests
- **env.test.ts**
	- Tests
		- Number value casted as string should be a String
			- **AssertionError**: expected `[ '\'string=1234\'', '' ] to strictly equal '1234'``]`
		- Value casted as regex 
			- **AssertionError**: expected `[ '\'regex=\\.example\\.com$\'', '' ]` to be an instance of RegExp.
		- CSV value should be an array 
			- **AssertionError**: expected `[ '\'one', 'two', 'three', …(2) ]` to strictly equal `[ 'one', 'two', 'three', 'four' ]`
		- CSV value casted as string should be a string  
			- **AssertionError**: expected [ Array(5) ] to strictly equal `'one,two,three,four'`
		- Multiple type cast  
			- **AssertionError**: expected `[ …(3) ] `to strictly equal `[ 'https://example.com', …(1) ]`
- **exec/index.test.ts**
	- Tests
		- Rejects when code contains syntax errors 
			- **AssertionError**: expected SyntaxError: Unexpected end of input to deeply equal Error: Couldn't compile code: Unexpected
- **/migrations/run.test.ts**
	- Tests 
		- All tests in this file are failing because 'default is not a function.'
- **get-config-from-env.test.ts**
	- Tests 
		- Keys with double underscore should be an [[Object]] 
			- **Error**: [vitest] No "default" export is defined on the "/src/env.ts"
		- Keys with double underscore should be an object with camelCase keys 
			- **Error**: [vitest] No "default" export is defined on the "/src/env.ts"
	- Reason: I'm not really sure, get-config-from-env has a named export already.
- **src/cli/index.test.ts** 
	- Tests
		- **Error**: Missing "./utils/node/get-extensions" export in "@directus/shared" package
	- Reason: I can't find the ./utils/node/get-extensions in the repo.
- **src/utils/get-auth-providers.test.ts**
	- Tests 
		- when no providers configured  
			- **Error**: [vitest] No "default" export is defined on the "/src/env.ts"
		- when no driver configured  
			- **Error**: [vitest] No "default" export is defined on the "/src/env.ts"
		- when single provider and driver are properly configured  
			- **Error**: [vitest] No "default" export is defined on the "/src/env.ts"
		- when multiple provider and driver are properly configured  
			- **Error**: [vitest] No "default" export is defined on the "/src/env.ts"
	- Reason: Again I can't figure out why this needs a default export 
- **src/middleware/authenticate.test.ts**
	- Tests
		- **TypeError**: Cannot read properties of undefined (reading 'LOG_LEVEL')
	- Reason: Not really sure here
- **src/services/specifications.test.ts**
	- Tests 
		- returns untyped schema for json fields  
			- **TypeError**: default is not a function
	- Reason: So I believe the mocked return value is untyped but I'm having trouble getting the vitest mocked type helper to work in the beginning of the describe block. 
```js
	  	//TODO: replace with correct vitest api call
	let db: vi.Mocked<Knex>;
	let tracker: Tracker;

	beforeAll(async () => {
		//TODO: replace with correct vitest api call
			db = knex({ client: Client_PG }) as vi.Mocked<Knex>;
		tracker = getTracker();
	});
```
- src/services/payload.test.ts1
	- Tests 
		- processes dates with typical values  
		- **AssertionError**: expected `[ { date_field: '2022-01-09', …(2) } ] to match object [ { date_field: '2022-01-10', …(2) } ]`
	- Reason: The day is being shifted 1 day.

2022-10-28 23:53 UTC, paescuj commented on api/src/cli/index.test.ts
> +		...(actual as object),
Not sure if we're overriding the values, but let's keep it the same as before:

```suggestion
		...(actual as object),
		EXTENSIONS_PATH: '',
		SERVE_APP: false,
		DB_CLIENT: 'pg',
		DB_HOST: 'localhost',
		DB_PORT: 5432,
		DB_DATABASE: 'directus',
		DB_USER: 'postgres',
		DB_PASSWORD: 'psql1234',
```

2022-10-29 00:20 UTC, paescuj commented on api/src/cli/index.test.ts
> +	getLocalExtensions: vi.fn(() => Promise.resolve([customCliExtension])),
This should probably look something like this:
```ts
vi.mock('@directus/shared/utils/node', async () => {
	const actual = await vi.importActual('@directus/shared/utils/node');

	const customCliExtension: Extension = {
		path: `/hooks/custom-cli`,
		name: 'custom-cli',
		type: 'hook',
		entrypoint: 'index.js',
		local: true,
	};

	return {
		...(actual as object),
		getPackageExtensions: vi.fn(() => Promise.resolve([])),
		getLocalExtensions: vi.fn(() => Promise.resolve([customCliExtension])),
	};
});
```

- `@directus/shared/utils/node` is exported in `@directus/shared` (sub-module `get-extensions` is not)
- However, with this I still get an error:
  
  ```console
  Caused by: Error: Error: Cannot find module /Users/pascal/Development/directus/api/Users/pascal/Development/directus/packages/shared/dist/esm/utils/node/index.js imported from file:///Users/pascal/Development/directus/api, file:///Users/pascal/Development/directus/, file:///Users/pascal/Development/directus/api/_index.js, file:///Users/pascal/Development/directus/node_modules
  ```
  
  Bug in `vitest`? Path looks wrong...

2022-10-29 00:25 UTC, paescuj commented on api/src/middleware/authenticate.test.ts
>  }));
You need to import the actual module as well, so the other env values will be available:
```suggestion
vi.mock('../../src/env', async () => {
	const actual = await vi.importActual('../../src/env');
	return {
		...(actual as object),
		SECRET: 'test',
	};
});
```

2022-10-29 00:34 UTC, paescuj commented on api/src/cli/index.test.ts
> +import { test, expect, vi, beforeEach } from 'vitest';
```suggestion
import { test, expect, vi, beforeEach, describe } from 'vitest';
```

Pro-tip: Temporarily remove the package `@type/jest` in the root, so the namespace in the IDE is not polluted and you will get a warning when an import from `vitest` is missing

2022-10-29 13:22 UTC, paescuj commented on api/src/services/specifications.test.ts
>  });
```suggestion
vi.mock('../../src/database/index', async () => {
	const actual = await vi.importActual('@directus/shared/utils/node');

	return {
		...(actual as object),
		getDatabaseClient: vi.fn().mockReturnValue('postgres'),
	};
});
```

2022-10-29 13:22 UTC, paescuj commented on api/src/services/specifications.test.ts
> +vi.mock('../../src/database/index');
Not required

```suggestion

```

2022-10-29 13:23 UTC, paescuj commented on api/src/services/specifications.test.ts
> +	let db: vi.Mocked<Knex>;
IMO, we can simply use `Knex` here:

```suggestion
	let db: Knex;
```

2022-10-29 13:23 UTC, paescuj commented on api/src/services/specifications.test.ts
> +		db = knex({ client: Client_PG }) as vi.Mocked<Knex>;
```suggestion
		db = knex({ client: Client_PG });
```

2022-10-29 13:30 UTC, paescuj commented on api/src/database/migrations/run.test.ts
>  import { getTracker, MockClient, Tracker } from 'knex-mock-client';
This might not work with Vitest...

2022-10-29 13:37 UTC, paescuj commented on api/src/operations/exec/index.test.ts
>  import { VMError } from 'vm2';
Line 33 can be changed to:
```ts
).rejects.toEqual(new Error("Unexpected end of input"));
```

2022-10-29 13:40 UTC, paescuj commented on api/src/utils/get-config-from-env.test.ts
> +vi.mock('../../src/env', () => ({
Should be:
```ts
vi.mock('../../src/env', async () => {
	const actual = await vi.importActual('../../src/env');

	return {
		...(actual as object),
		OBJECT_BRAND__COLOR: 'purple',
		OBJECT_BRAND__HEX: '#6644FF',
		CAMELCASE_OBJECT__FIRST_KEY: 'firstValue',
		CAMELCASE_OBJECT__SECOND_KEY: 'secondValue',
	};
});
```

2022-10-29 13:50 UTC, paescuj commented on api/src/cli/index.test.ts
> +});
```suggestion
vi.mock('../../src/env', async () => {
	const actual = await vi.importActual('../../src/env');

	return {
		default: {
			...(actual as object),
			EXTENSIONS_PATH: '',
			SERVE_APP: false,
			DB_CLIENT: 'pg',
			DB_HOST: 'localhost',
			DB_PORT: 5432,
			DB_DATABASE: 'directus',
			DB_USER: 'postgres',
			DB_PASSWORD: 'psql1234',
		},
	};
});
```

2022-10-30 09:21 UTC, paescuj commented on api/package.json
>  		"cleanup": "rimraf dist",
The dependency `@types/jest` is no longer required.

2022-10-30 09:22 UTC, paescuj commented on api/package.json
> +		"vitest": "0.24.3"
The dependency `@types/jest` is no longer required and can be removed.

2022-11-01 21:06 UTC, paescuj commented
Hey there 👋 
FYI: I've solved all issues locally and will submit a separate PR in a few minutes!

2022-11-01 21:07 UTC, rijkvanzanten commented
> Hey there 👋 FYI: I've solved all issues locally and will submit a separate PR in a few minutes!

🤯 look at the power of team work @DorianCBrwn 🚀

2022-11-01 21:10 UTC, paescuj commented
> 🤯 look at the power of team work @DorianCBrwn 🚀

And the power of open source 😄🚀❤️ 
Thank you very much @DorianCBrwn for your initial work on this!

2022-11-02 13:31 UTC, paescuj commented
Since the review has gotten a little out of hand and comments on unchanged lines / files are unfortunately not possible (looking at you, GitHub :octocat:), I've opened a new pull request based on the work from this one: #16263

2022-11-02 18:00 UTC, DorianCBrwn commented
> > 🤯 look at the power of team work @DorianCBrwn 🚀
> 
> And the power of open source 😄🚀❤️ Thank you very much @DorianCBrwn for your initial work on this!

Oh, thanks for finishing it. I wasn't getting far in my understanding of vi.mock and typescript errors tbh.

2022-11-08 01:11 UTC, DorianCBrwn commented
> > Oh, thanks for finishing it. I wasn't getting far in my understanding of vi.mock and typescript errors tbh.
> 
> Sure thing! If you're interested we can jump on a call on Discord to go through the errors that occurred and the possible solutions to them... Might be available on Saturday - just let me know on Discord!

Sorry, I've been busy with work but if the offer is still open I'd be happy to learn more to be able to finish migrating the rest of the package tests. @paescuj  What do you go by on discord? I couldn't find you, I go by DorianB.

2022-11-08 22:28 UTC, paescuj commented
> Sorry, I've been busy with work but if the offer is still open I'd be happy to learn more to be able to finish migrating the rest of the package tests. @paescuj What do you go by on discord? I couldn't find you, I go by DorianB.

No worries 😃 Quite busy too... Sure, let's do this! This weekend should go well 👍 Sorry, I've a different username there - just sent you a friend request.

2022-11-14 21:09 UTC, closed without merging