Fix operations output being undefined
directus/directus pull request #17181
Opened 2023-01-16 10:06 UTC by Nitwel

## Description

It fixes undefined being returned by an operation and replaces it with null instead. We have to do this as the applyOptionsData replaces all undefined values with a string "undefined" which doesn't make a lot of sense in the context of flows & operations.

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

2023-01-16 10:52 UTC, br41nslug requested changes
The `mapObjectDeep` function does not seem to take arrays into account. If i have an operation returning an array directly or indirectly this gets transformed to an object.
For the test is created a "Run Script" operator returning an array:
```js
module.exports = async function(data) {
    // return [undefined,1,2,3,undefined];
	return {test:[undefined,1,2,3,undefined]};
}
```
in both cases the array gets transformed to 
```json
{"0":null,"1":1,"2":2,"3":3,"4":null}
```

2023-01-16 11:44 UTC, Nitwel commented
Good catch! Updated it to work with arrays too. Thanks!

2023-01-16 12:24 UTC, br41nslug approved these changes

2023-01-18 20:00 UTC, rijkvanzanten approved these changes

2023-01-18 20:00 UTC, merged