Show validation errors in drawer-item
directus/directus pull request #17423
Opened 2023-02-07 11:04 UTC by Nitwel

By splitting up the `nested` prop into to separate, we can disable the `no visible fields` info but keep the validation errors.

Fixes #16091

2023-02-07 15:08 UTC, rijkvanzanten requested changes
Lets flip it from `hideX` to `showX` with the inversed default values to stay consistent with other props like this in other components

2023-02-07 15:31 UTC, Nitwel commented
Haha, had it that way and flipped it to hideX so their name matches their default value.
E.g. `<v-table hideX>` is more direct that `<v-table :showX="false">` and thus you might think `<v-table showX>` would imply that X is hidden by default. Thoughts?

2023-02-07 15:34 UTC, rijkvanzanten commented
@Nitwel I'd rather keep it consistent across the codebase 🙂 There's also that tiny opinionated code quality thing where you should prevent double negatives (eg "Do X = true" is easier to mentally parse than "Don't do X = false")

2023-02-07 16:01 UTC, rijkvanzanten approved these changes

2023-02-13 09:04 UTC, paescuj approved these changes
LGTM, besides a small clean-up due to flipped logic.

2023-02-13 09:04 UTC, paescuj commented on app/src/components/v-form/v-form.vue
> +			v-if="!showValidationErrors && validationErrors.length > 0"
```suggestion
			v-if="showValidationErrors && validationErrors.length > 0"
```

2023-02-13 09:04 UTC, paescuj commented on app/src/components/v-form/v-form.vue
> +			v-if="noVisibleFields && !showNoVisibleFields && !loading"
```suggestion
			v-if="noVisibleFields && showNoVisibleFields && !loading"
```

2023-02-13 09:04 UTC, paescuj commented on app/src/components/v-form/v-form.vue
> +		if (props.showValidationErrors) return;
```suggestion
		if (!props.showValidationErrors) return;
```

2023-03-06 10:47 UTC, merged