Throw validation error after authorization
directus/directus pull request #17499
Opened 2023-02-13 14:36 UTC by licitdev

## Description

Throw the validation error after authorization but before the mutation occurs, if any.

Fixes ENG-605

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [ ] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

2023-02-14 10:34 UTC, paescuj requested changes
Looks very good to me! Just wondering whether we should apply the same logic to `deleteMany` in `users` and maybe even other methods like `requestPasswordReset`? https://github.com/directus/directus/blob/ea1bc45fff2454d06aee32898cd862c4a2f52e01/api/src/services/users.ts#L283

2023-02-14 14:34 UTC, licitdev commented
@paescuj Great catch, thank you! Updated for `deleteMany`. 👍 
Also refactored for other usages for a consistent behaviour, for the whitelist URLs. 😄

2023-02-14 17:28 UTC, paescuj approved these changes
Great work!

2023-02-20 10:54 UTC, br41nslug approved these changes

2023-02-20 10:57 UTC, merged