Remove hardcoded package extension path
directus/directus pull request #17525
Opened 2023-02-15 08:20 UTC by nfjodor

## Description

Can't use Directus Flows with an electron wrapper.

Fixes [ENG-698](https://linear.app/directus/issue/ENG-698/add-package-extensions-path-to-env-variables)

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

2023-02-15 21:17 UTC, rijkvanzanten requested changes
I'm not sure if this is something we're looking to support at this time. Lets discuss the problem and potential solutions in https://github.com/directus/directus/issues/17524 first before going over to solutions and new features 👍🏻 

(f.e., this should probably be "PACKAGE_FILE_LOCATION" rather than something specific to extensions, as I'm sure there'll be other places / times we'll need to access package.json. I also have no clue if there's any other changes required to make Electron play nice, as that's not a target platform we've ever aimed to support in the app)

2023-02-16 08:45 UTC, nfjodor commented
Thank you for the suggestion. It is better than my idea for the env variable name. I don't know what will be the end of this PR but I modified the code.

2023-02-16 18:35 UTC, rijkvanzanten commented
> Thank you for the suggestion. It is better than my idea for the env variable name. I don't know what will be the end of this PR but I modified the code.

As per our discussions on the issue, lets find a minute to research if there's any other blockers for electron; if not, I'm more than happy to push this through to unlock that use case 🙂

2023-02-20 17:14 UTC, rijkvanzanten approved these changes

2023-02-21 14:19 UTC, br41nslug reviewed
The fix looks sensible. I am however notable to reproduce the original issue 🤔 Given the provided electron repo (removed the patch and tweaked some env vars) it builds and runs as expected without errors on Windows. is this a platform specific issue?

2023-02-21 14:57 UTC, nfjodor commented
> The fix looks sensible. I am however notable to reproduce the original issue 🤔 Given the provided electron repo (removed the patch and tweaked some env vars) it builds and runs as expected without errors on Windows. is this a platform specific issue?

Sorry for the patch file that I pushed since created the bug ticket.
Of course, it can run without any problem, but when you start the application from the console, an error message appears:
![image](https://user-images.githubusercontent.com/6689221/220373568-4c21d293-3f4e-4973-b990-75be01a58e91.png)

I checked again, I wondered because the `Flows` worked with `fs-extra` independently from this error message. I'm at loss why. But if somebody put some restrictions or checks in the future that Directus can use npm packages only from the package.json it can be a problem. So, I think, this PR request is still relevant.

Meanwhile, I edited the repro steps in the bug ticket to use the initial commit. I'm really sorry for my changes since the ticket creation.

2023-02-21 15:57 UTC, br41nslug commented
> Of course, it can run without any problem, but when you start the application from the console, an error message appears:

Ah yeah running an electron app from the CLI was not my first instinct and dont remember seeing it in the reproduction steps. 
I am able to reproduce the issue now :) however the PR or patch do not directly fix the issue so im probably still missing something. In your repo you have the `PACKAGE_FILE_LOCATION` set as `"."` which is identical to the hardcoded value. Does this require a different value?

2023-02-21 16:09 UTC, nfjodor commented
> In your repo you have the `PACKAGE_FILE_LOCATION` set as `"."` which is identical to the hardcoded value. Does this require a different value?
As you can see here, I change the relative path to absolute: https://github.com/nfjodor/directus-electron/blob/main/src/index.js
With this, it can work without any problems.
It is also true for the other environment variables too and I solved the `path` problems easily, but the package.json can't be resolved, because it is a hardcoded value and can't be overwritten. This is why this PR was created.

I know my code isn't the most beautiful at the moment but currently, I started with a PoC to check if can I run Directus inside an electron wrapper.

And found only this issue. If this will be solved, I will make better code for that and I will make a foolproof readme.md too.

For example, I need to solve a lot of things, a splash screen, email templating with custom URL schema, the catch the URL with the electron, etc. I'm at step 0 now 😊

2023-02-21 16:21 UTC, br41nslug approved these changes
Ah that did it, running without errors now 😄 The repro code is still using `PACKAGE_EXTENSIONS_PATH` instead of `PACKAGE_FILE_LOCATION` thus is was not being solved on my end.

2023-02-21 16:22 UTC, merged

2023-02-21 16:23 UTC, nfjodor commented
> Ah that did it, running without errors now 😄 The code is still using `PACKAGE_EXTENSIONS_PATH` instead of `PACKAGE_FILE_LOCATION` thus not solving it on my end.

Because I was dumb and forgot to push my changes 🙄

2023-02-21 16:26 UTC, br41nslug commented
Thank you for the fix 😄 Also don't forget to share your electron creation on our discord, I'm sure more people in the community will love it

2023-04-09 21:04 UTC, flevi29 commented
https://github.com/directus/directus/blob/e56a6715be8f567d183fe18d3dc56345a9174c84/api/src/extensions.ts#L295

Shouldn't have this line been changed too to use the new env variable?