Rijk/eng 557 accelerated engineering manual flows
directus/directus pull request #17603
Opened 2023-02-23 00:14 UTC by rijkvanzanten

## Description

Adds new functionality to the manual trigger in Flows that allows an optional confirmation modal, with optional inputs. This allows you to ask for additional data to use in the flow that's ran on the manual trigger.

Closes ENG-557

## Todo

- [ ] Update docs

2023-02-23 14:01 UTC, freekrai approved these changes
Tested both the confirmation with a default text, plus with a custom text.

Also tested turning the confirmation off as well.

2023-02-27 11:08 UTC, br41nslug requested changes
I think at the very least the `fieldKey` needs to be required because interesting things start happening if you leave them empty
![image](https://user-images.githubusercontent.com/9389634/221548137-c9194ef4-90b8-432f-ab5d-c3823c5ae9cb.png)
![image](https://user-images.githubusercontent.com/9389634/221548195-f2a32f21-8385-4125-83c2-415e433c6197.png)

2023-02-27 14:35 UTC, br41nslug commented
> I think at the very least the fieldKey needs to be required because interesting things start happening if you leave them empty

I was not aware that this is already broken for the core repeater so might be out of scope here

2023-02-27 16:11 UTC, licitdev commented
@br41nslug The `fieldKey` has been set as required in https://github.com/directus/directus/pull/17603/commits/d2bb93f14c947538925c040c701a467f71532ddb. 
The support for required fields in repeater is added via PR #17637.

2023-03-24 19:10 UTC, rijkvanzanten commented on app/src/interfaces/_system/system-inline-fields/index.ts
> +	description: 'Inline Fields',
You can't choose nor see system interfaces, so I don't think it matters here

2023-03-30 07:55 UTC, paescuj commented on app/src/lang/translations/en-US.yaml
>  run_flow_on_selected: Select One or More Items First | Run flow on 1 Selected Item | Run flow on {n} Selected Items
```suggestion
run_flow_on_current_collection: Run Flow on Current Collection
run_flow_on_current: Run Flow on Current Item
run_flow_on_current_edited_confirm: This item may be updated by this flow, are you sure you want to execute it?
run_flow_on_selected: Select One or More Items First | Run Flow on 1 Selected Item | Run Flow on {n} Selected Items
```

2023-03-30 08:00 UTC, paescuj requested changes
I think we should use the field key as field title if no field name has been defined, like we're basically doing it in collections (using format title):
<img width="576" alt="Screenshot 2023-03-30 at 09 47 55" src="https://user-images.githubusercontent.com/5363448/228769285-2e5bbdec-5471-41a0-a258-5707afe563f5.png">

2023-03-30 15:31 UTC, br41nslug approved these changes
Issues I previously ran into seem to have been resolved nicely 🚀 

I did see 2 nice to have improvement options but they're no showstoppers for me
- perhaps `type` and `interface` should be defaulted to `String` and `Input` respectively as that is what they default to anyway when you leave them empty
- It may be nice to have the option to set default_value's for these inputs

2023-03-31 15:37 UTC, licitdev commented on app/src/interfaces/collection-item-dropdown/collection-item-dropdown.vue
> +		if (value.key) emit('input', value);
Added it just in case! Ref: https://github.com/directus/directus/pull/17603/commits/9b783cb2e3d19b1a2eeffdf742b15d50f9748113

2023-03-31 15:48 UTC, licitdev approved these changes
LGTM. Nice confirmation flow! 👍

2023-03-31 19:21 UTC, paescuj commented on app/src/lang/translations/en-US.yaml
> +    description: Select an item from a collection in json format
```suggestion
    description: Select an item from a collection in JSON format
```

2023-03-31 19:31 UTC, paescuj commented on app/src/lang/translations/en-US.yaml
> +run_flow_confirm: Are you sure you want to execute this Flow?
```suggestion
run_flow_confirm: Are you sure you want to execute this flow?
```

2023-03-31 19:32 UTC, paescuj approved these changes

2023-03-31 19:37 UTC, merged