Don't render $thumbnail field in table
directus/directus pull request #17733
Opened 2023-03-07 18:02 UTC by Nitwel

The problem was that when selecting the $thumbnail field to be a header, it didn't remove the fake $thumbnail part, thus didn't work.

Fixes #17541

2023-03-07 18:17 UTC, rijkvanzanten requested changes

2023-03-07 18:17 UTC, rijkvanzanten commented on app/src/layouts/tabular/index.ts
> +						const fieldParts = field.key.split('.').filter((part) => part !== '$thumbnail');
Lets make this "starts with $" instead 👍🏻

2023-03-08 14:12 UTC, br41nslug requested changes
This fix does prevent the original `/assets/undefined` error but I am running into some weirdness still being able to select the "thumbnail field". Perhaps the option should be hidden for the Permissions and Layouts.
![firefox_4kOL0V8Sz3](https://user-images.githubusercontent.com/9389634/223735136-a90785b2-13c2-4b33-a487-f33d28c127d7.gif)

2023-04-11 23:14 UTC, rijkvanzanten commented
I think we'll have to go back to the drawing board on this one. Proposed fix doesn't seem to resolve the issue for me 🤔

2023-04-11 23:14 UTC, closed without merging