Fix keep folder on reupload
directus/directus pull request #17744
Opened 2023-03-08 14:03 UTC by Nitwel

The problem was that the api would override the folder field, because it didn't existed in the payload but the case that the item already exists and has a folder wasn't considered.

Fixes #17427

2023-03-15 23:35 UTC, paescuj approved these changes

2023-03-16 16:32 UTC, jaads requested changes

2023-03-17 09:03 UTC, paescuj commented on api/src/services/files.ts
> +		const existingFile =
To be honest I didn't find it difficult to read, but that's also always a matter of opinion. 
Both ways are fine for me 👍 Let's @Nitwel decide for one of them 😄

2023-03-17 10:28 UTC, jaads commented on api/src/services/files.ts
> +		const existingFile =
yes, for me both are fine too. it might be just a personal preference of mine here :)

2023-03-21 15:16 UTC, jaads approved these changes
LGTM and works as expected

2023-03-21 15:17 UTC, merged