Fix tabular headers
directus/directus pull request #17799
Opened 2023-03-15 08:56 UTC by Nitwel

## Description

Will come soon.

Fixes #17716

2023-03-16 14:03 UTC, paescuj commented
Is this also going to address #17506 (reopened because of the #17816)?

2023-03-22 08:17 UTC, paescuj approved these changes
Only a small comment, otherwise looks great 😃👍

2023-03-22 09:18 UTC, paescuj requested changes
**Small addition:**

The value passed to `render-display` (computed in `getDisplayValue`) is now an array in case of relational fields. While this doesn't seem to be an issue, the following warning is shown in the console:

```
[Vue warn]: Invalid prop: type check failed for prop "value". Expected String | Number, got Array  
  at <FormattedValue interface="input" interface-options=null value= 
Array [ "test" ]
  ... > 
  at <VErrorBoundary key=2 name="display-formatted-value" > 
  at <RenderDisplay value= 
Array [ "test" ]
 display="formatted-value" options=null  ... > 
  at <TableRow headers= 
Array(3) [ {…}, {…}, {…} ]
 item= 
Object { category: "category1", id: 1, 1be40: (1) […], 5622e2d6: (1) […] }
 show-select="multiple"  ... > 
  at <Draggable key=3 modelValue= 
Array [ {…} ]
 onUpdate:modelValue=fn  ... > 
  at <VTable key=0 ref="table" modelValue= 
Array []
  ... > 
  at <Tabular key=1 class="layout" tableHeaders= 
Array(3) [ {…}, {…}, {…} ]
  ... > 
  at <PrivateView key=1 title="Parent" small-header=undefined > 
  at <AsyncComponentWrapper key=1 title="Parent" small-header=undefined > 
  at <TabularWrapper ref="layoutRef" selection= 
Array []
 onUpdate:selection=fn  ... > 
  at <ContentCollection collection="parent" bookmark=null archive=null > 
  at <CollectionOrItem collection="parent" bookmark=undefined archive=null  ... > 
  at <RouterView> 
  at <RouterPassthrough onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
#text ""
 > > 
  at <RouterView> 
  at <RouterPassthrough onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
#text ""
 > > 
  at <RouterView key=1 > 
  at <App> chunk-2GTISQ3F.js:1641:13
```

So we can probably just extend
https://github.com/directus/directus/blob/46c1666607abef720d2fb668c33e80e041ee4dc5/app/src/displays/formatted-value/formatted-value.vue#L37
by `Array`, correct?

2023-03-27 15:42 UTC, Nitwel commented
Added Array to the formatted-value display. 👍

2023-03-27 15:49 UTC, paescuj commented on app/src/layouts/tabular/tabular.vue
> +	return get(unAliasedItem, key);
`dealiased` is even better 😄🫶

2023-03-27 15:50 UTC, paescuj approved these changes

2023-04-11 14:22 UTC, rijkvanzanten approved these changes

2023-04-11 14:22 UTC, merged

2023-04-17 15:15 UTC, hanneskuettner commented
This PR caused the broken calendar layout display template #18206 and will also break the CSV export as it changed the return type (and function as far as I can tell) of `useAliasFields`.

In both cases the expected key is `aliasField` which has been removed.

See https://github.com/directus/directus/blob/42e19633456341b1cae4e19db7e52ac9e25bd08b/app/src/utils/render-string-template.ts#L70 

and 
https://github.com/directus/directus/blob/42e19633456341b1cae4e19db7e52ac9e25bd08b/app/src/utils/save-as-csv.ts#L22