Load relational data from api on button-links
directus/directus pull request #17959
Opened 2023-03-27 14:24 UTC by Nitwel

Before, you where able to select relational fields of an item to insert but we didn't fetch that data from the api and only relied on the data that was already existing. Could be a very old side effect of the relational rework.

Fixes #17837

2023-03-27 18:57 UTC, freekrai approved these changes

2023-04-11 23:36 UTC, rijkvanzanten requested changes

2023-04-11 23:36 UTC, rijkvanzanten commented on app/src/interfaces/presentation-links/presentation-links.vue
> +const RELATIONAL_TYPES = ['file', 'files', 'm2o', 'o2m', 'm2m', 'm2a', 'presentation', 'translations', 'group'];
This should use an existing `const`, or make this a shared `const` if it doesn't exist yet

2023-04-12 21:15 UTC, rijkvanzanten approved these changes

2023-04-12 21:15 UTC, merged