[WIP] Migrate to Material Symbols
directus/directus pull request #18004
Opened 2023-03-30 14:58 UTC by hanneskuettner

## Description

Migrate over to Material Symbols, the never version of Material Icons that has ~1k new icons.  

Please see my [discussion comment](https://github.com/directus/directus/discussions/12958#discussioncomment-5478746) in #12958 for some background on the implications this change has.

A total of 991 icons have been added with a lot of fallbacks for deprecated icon names. 
A total of 21 icons have been removed without any replacement.

<details><summary>List of removals</summary>

```
catching_pokemon
delivery_dining
discount
emoji_events
fitbit
highlight_alt
miscellaneous_services
moped
motion_photos_on
no_cell
panorama_horizontal_select
panorama_photosphere_select
panorama_vertical_select
panorama_wide_angle_select
person_add_alt_1
person_remove_alt_1
pix
play_circle_filled
play_circle_outline
signal_wifi_statusbar_connected_no_internet_4
whatsapp
```

</details>

I will wait until a decision has been made in the discussion but wanted to bring this PR on the way in the meantime.

![image](https://user-images.githubusercontent.com/4376726/228877849-b533d20c-16b6-4c17-8c14-04fa9428bec5.png)

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

2023-03-31 13:12 UTC, hanneskuettner commented
I've got a question about migrations. Right now the soon to be removed icon `bookmark_outline` is used in a migration as a default for an icon field. I guess this would warrant another migration that alters the default?

https://github.com/directus/directus/blob/953c2f95d57a944ccb4771e41505b8d5caa80189/api/src/database/migrations/20220308A-add-bookmark-icon-and-color.ts#L4-L7

Any hint how to approach this? My educated guess is 

```ts
// 2023XXXXA-update-default-value-bookmark-icon.ts
export async function up(knex: Knex): Promise<void> {
	const helper = getHelpers(knex).schema;

	await helper.changeToType('directus_presets', 'icon', 'string', {
		nullable: true,
		default: 'bookmark',
		length: 30,
	});
}

export async function down(knex: Knex): Promise<void> {
	const helper = getHelpers(knex).schema;

	await helper.changeToType('directus_presets', 'icon', 'string', {
		nullable: true,
		default: 'bookmark_outline',
		length: 30,
	});
}
```

2023-04-12 02:26 UTC, rijkvanzanten commented
@hanneskuettner Your educated guess is exactly right!

2023-04-12 07:28 UTC, hanneskuettner commented on api/src/database/migrations/20230401B-rename-bookmark-icon-in-presets.ts
I also had to add a migration for updating the `bookmark_outline` to the `bookmark_border` icon in the `directus_presets` table since there a probably quite a few `bookmark_outline` values out there since it was the default icon (even though it didn't officially exist in the Material Icons).

I changed it to `bookmark_border` which isn't officially in the icon set (it's been replaced by `bookmark`) to allow for a clean downgrade. Since the user might have some presets with the old `bookmark` icon set, which is filled, and we probably don't want migrate that away.

2023-04-12 16:47 UTC, rijkvanzanten requested changes
Out of 2837 changes in 54 files, I only found one typo! Good job @hanneskuettner 🎉 

I think we can merge the two migrations together, but other than that we should be in a good spot (i'll handle that tweak 👍🏻 )

2023-04-12 16:47 UTC, rijkvanzanten commented on app/src/interfaces/file-image/file-image.vue
> +				<v-icon large :name="imageError === 'UNKNOWN' ? 'error_' : 'info'" />
```suggestion
				<v-icon large :name="imageError === 'UNKNOWN' ? 'error' : 'info'" />
```

2023-04-12 17:01 UTC, rijkvanzanten commented on app/src/interfaces/select-icon/select-icon.vue
> +				</v-divider>
Lets omit the name here to keep things the same as before. If we wanna show the group names, they have to be localized

2023-04-12 17:04 UTC, rijkvanzanten approved these changes

2023-04-12 17:12 UTC, merged