WIP: Response cache
directus/directus pull request #1811
Opened 2017-09-13 23:54 UTC by parnas

2017-09-14 15:48 UTC, wellingguzman requested changes
Hey @parnas , I had multiple question that I commented ~above~ below, but one of my main concern is wouldn't this be almost identical to the previous cache middleware with the difference that this would have the output cached somewhere?

I may be confusing this, if you can please clear this up would be amazing.

Thanks!

2017-09-14 15:48 UTC, WellingGuzman commented on api/core/Directus/Slim/ResponseCacheMiddleware.php
> +            $parameters = $_GET;
You can use `$app->request()->get()` or `$app->request->get()` instead.

2017-09-14 15:48 UTC, WellingGuzman commented on api/core/Directus/Slim/ResponseCacheMiddleware.php
> +            $path = parse_url($_SERVER["REQUEST_URI"], PHP_URL_PATH);
You can use `$app->request->getResourceUri()`

2017-09-14 15:48 UTC, WellingGuzman commented on api/core/Directus/Slim/ResponseCacheMiddleware.php
> +        if($_SERVER['REQUEST_METHOD'] == 'GET') {
Can be replaced with: `$app->request->isGet()`

2017-09-14 15:48 UTC, WellingGuzman commented on api/core/Directus/Slim/ResponseCacheMiddleware.php
> +        $cache = Bootstrap::get('responseCache');
Use `$app->container->get(KEY);` instead of `Bootstrap::get(KEY);`

2017-09-14 15:48 UTC, WellingGuzman commented on api/core/Directus/Slim/ResponseCacheMiddleware.php
> +            $response->headers = $cachedResponse->headers;
What headers does the cache response generated? is this configurable and if it does where can it be?

2017-09-14 15:48 UTC, WellingGuzman commented on api/core/Directus/Slim/ResponseCacheMiddleware.php
> +        if($key && $cachedResponse = $cache->get($key)) {
Can the cache be disable? example on development environment or simple because we want it disable incase we are using a different solution?

2017-09-14 15:48 UTC, WellingGuzman commented on api/core/Directus/Slim/ResponseCacheMiddleware.php
> +class ResponseCacheMiddleware extends Middleware
Isn't this Middleware working similar to `HttpCacheMiddleware` (Previous `CacheMiddleware`)?

2017-09-14 15:48 UTC, WellingGuzman commented on api/routes/A1/Users.php
> +        $this->setTags(['table_users', 'entity_user_'.$id]);
We were expecting the new layer to cache the output, so we don't hit the db, but acting everything else as normal, so the user can execute hooks. that's one cache, then we would have a second one that's what you are using and that's the HTTP cache, unless this has not been clear to me, if it's please let us know.

2017-09-14 15:48 UTC, WellingGuzman commented on api/core/Directus/Bootstrap.php
> +        $filesystemAdapter = new Local(__DIR__.'/../../../cache/');
Will this be configurable?

2017-09-14 15:48 UTC, WellingGuzman commented on api/routes/A1/Users.php
> +        $this->invalidateTags('entity_user_'.$id);
Wouldn't be possible to instead of invalidate the entry, we update it?

2017-09-19 04:06 UTC, wellingguzman reviewed
I'm still confusing what was the change and what I'm going to test.

What should we expect from the new changes?

2017-09-19 09:44 UTC, parnas commented on api/core/Directus/Cache/Response.php
> +        $this->$array = array_merge($this->$array, (array)$tags);
Merges currently set tags with the newly added ones. (array)$tags is to be able to pass a single tag as a string.

2017-09-19 17:45 UTC, WellingGuzman commented on api/core/Directus/Cache/Response.php
> +        $this->$array = array_merge($this->$array, (array)$tags);
What about `$this->$array`?

2017-09-20 12:50 UTC, parnas commented on api/core/Directus/Cache/Response.php
> +        $this->$array = array_merge($this->$array, (array)$tags);
It's a variable variable. To not have copy/paste.

As you see, it's called from functions like this: `$this->updateTagsArray('invalidateTags', $tags)`, so, in that case $array would be 'invalidateTags', so it's `$this->invalidateTags = array_merge($this->$array, (array)$tags)`

2017-09-20 13:38 UTC, WellingGuzman commented on api/core/Directus/Cache/Response.php
> +        $this->$array = array_merge($this->$array, (array)$tags);
Still not following what is doing, like what would be the result or what we looking for. Adding comments would be better so I don't have to ask questions, I'm sorry just get lost here.

2017-09-21 07:49 UTC, WellingGuzman commented on api/core/Directus/Cache/Response.php
> +        $this->$array = array_merge($this->$array, (array)$tags);
`$array` param seems not to send an `array` but rather a string. please add phpdoc as well, and a clearer name.

2017-10-10 05:48 UTC, WellingGuzman commented on api/core/Directus/Bootstrap.php
> +        $filesystemAdapter = new Local(__DIR__.'/../../../cache/');
Can you make this default to `storage`, and let the user set this value to anything they want?

2017-10-18 03:27 UTC, merged