Fix tabular not properly dealiasing items
directus/directus pull request #18186
Opened 2023-04-14 11:58 UTC by Nitwel

The problem was that when merging the item returned from the api to replace alaised fields with their original names, I didn't take into account that the field without an alias could override the dealiased field, thus resulting in the wrong item.

closes #18181

2023-04-14 13:11 UTC, rijkvanzanten requested changes

2023-04-14 13:11 UTC, rijkvanzanten commented on app/src/layouts/tabular/index.ts
> +							if (types.at(-1) === 'o2m' && arrayField?.meta?.display === 'translations') {
We can't rely on the name of an extension for logic. Displays are extension types so the name could be anything

2023-04-19 12:22 UTC, Nitwel commented
@rijkvanzanten Going back to the discussion we had on Discord, your idea of being able to apply the translations display to any field wouldn't work at the moment as the display needs to configure which fields it should load, but the problem here is that you can only specify fields relative to your field so you can't load fields on the same level meaning, the display wouldn't be able to access the `languages_code.code` field.

What I did now is to remove the hacky logic so we can fix this for now and figure out a proper way to support translations display on none translations fields, meaning that for now we will only show it as an array like so:
![grafik](https://user-images.githubusercontent.com/22577866/233073302-665f4b1a-fab6-4307-b8a7-9f52391af582.png)

2023-04-21 19:13 UTC, rijkvanzanten approved these changes

2023-04-21 19:13 UTC, merged