Fix/users invite
directus/directus pull request #18583
Opened 2023-05-12 17:45 UTC by licitdev

Fix incorrect null check with a falsy check.

Fixes #18582.

2023-05-12 17:45 UTC, rijkvanzanten approved these changes

2023-05-12 17:48 UTC, paescuj requested changes
Couldn't we catch this one level up?

2023-05-12 17:50 UTC, licitdev commented
> Couldn't we catch this one level up?

The type for `role` is `string | undefined` but it was an explicit `null` check.

https://github.com/directus/directus/blob/667049aaf39e0f2ec5c2cee587c8fe6b6bd76f34/app/src/views/private/components/users-invite.vue#L50-L53

2023-05-13 00:06 UTC, paescuj approved these changes

2023-05-13 00:16 UTC, merged