GraphQL Subscriptions update
directus/directus pull request #18804
Opened 2023-06-02 14:53 UTC by br41nslug

Fixes ENG-1053

This slightly alters the GraphQL Subscription format.

Before: 
```graphql
subscription {
	messages_mutated {
		id
                _event
		text
	}
}
```

After:
```graphql
subscription {
	messages_mutated {
		id
		event
		data {
			text
		}
	}
}
```

With the added option to filter a specific event:
```graphql
subscription {
	messages_mutated(event: update) {
		id
		data {
			text
		}
	}
}
```

2023-06-05 12:06 UTC, licitdev approved these changes
Works as expected! 👍 Nice validation using Enum for the event filtering. Should we also add the event filtering to the REST implementation?

2023-06-05 12:06 UTC, licitdev commented on api/src/services/graphql/subscription.ts
> +					yield { [event]: { id: key, data: {}, event: 'delete' } };
```suggestion
					yield { [event]: { id: key, event: 'delete' } };
```
If a non-null field is in the selection set, an error is thrown.
```
Cannot return null for non-nullable field a.id.
```
By removing the `data` here, the data will simply be `null`.
Currently when nullable fields are selected, the object is constructed but values are all set to `null`.

```
subscription{
  a_mutated(event:delete){
    event
    id
    data {
      name
      description
    }
  }
}

Result {
  "data": {
    "a_mutated": {
      "event": "delete",
      "id": "23",
      "data": {
        "name": null,
        "description": null
      }
    }
  }
} 
```

2023-06-05 12:10 UTC, paescuj commented on .changeset/hungry-points-rescue.md
As this is going to be released under the whole "Websockets umbrella" I think we can omit the changeset here

2023-06-05 12:17 UTC, paescuj approved these changes
LGTM besides the suggestion from @licitdev ❤️

2023-06-05 12:17 UTC, br41nslug commented on api/src/services/graphql/subscription.ts
> +				yield { [event]: { id: key, data, event: 'create' } };
Very good catch :)

2023-06-05 13:16 UTC, paescuj requested changes
Should we align it with the REST format and call it `payload` instead of `data`?
Also docs needs to be updated now.

2023-06-05 13:20 UTC, br41nslug commented
> Should we align it with the REST format and call it `payload` instead of `data`? Also docs needs to be updated now.

As this was called `data` to stay in line with the API, should we update rest to be called `data` too instead? 🤔

> Also docs needs to be updated now.

Any specific part missed @paescuj ? there are updated docs in this PR

2023-06-05 13:38 UTC, rijkvanzanten approved these changes

2023-06-05 13:38 UTC, rijkvanzanten commented
> As this was called data to stay in line with the API, should we update rest to be called data too instead? 🤔

Yes lets make that consistent 👍🏻

2023-06-05 13:58 UTC, paescuj commented
> > Also docs needs to be updated now.
> 
> Any specific part missed @paescuj ? there are updated docs in this PR

Oh just the switch from `id` to `key` that now needs to be reflected in the doc page 👍

2023-06-05 21:48 UTC, paescuj approved these changes

2023-06-06 12:57 UTC, licitdev approved these changes

2023-06-06 16:34 UTC, merged