Docs landing page
directus/directus pull request #18911
Opened 2023-06-15 12:59 UTC by estheragbaje

This PR contains the development of the docs landing page

- Adding sections based on the design
- Implementing responsiveness
- Accessibility
- Styling
- Light and dark mode

2023-06-15 19:11 UTC, rijkvanzanten requested changes

2023-06-15 19:11 UTC, rijkvanzanten commented on docs/guides/headless-cms/schedule-content/index.md
> +  add-margin
The `addMargin` prop was removed in https://github.com/directus/directus/pull/18911/files#diff-7f7a2886ba028429230a8f3655f1c8b51e6b62ee8b08f14d14bbe7745a22f40eL16

2023-06-15 19:11 UTC, rijkvanzanten commented on docs/public/assets/baas.png
These should come from the Directus instance

2023-06-19 12:02 UTC, estheragbaje commented on docs/.vitepress/components/Divider.vue
> +	<div class="divider" />
Considering that the divider serves a purely visual or presentational role, I'm not too sure we should prioritize a11y regarding it.

2023-06-19 12:03 UTC, estheragbaje commented on docs/.vitepress/components/home/UseCase.vue
> +			<img :src="img" alt="" class="img-size" />
Combined this

2023-06-19 12:05 UTC, estheragbaje commented on docs/.vitepress/components/home/SelfHosting.vue
> +		<img :src="img" alt="" class="sh-img" />
I'll suggest we keep this as a different component entirely because unlike the article, this has a button

2023-06-19 12:05 UTC, estheragbaje commented on docs/.vitepress/components/home/Articles.vue
> +	<p>{{ data }}</p>
This was a redundant component. Taken it out

2023-06-26 17:12 UTC, phazonoverload commented
Just working through with a fine toothcomb - mostly related to links.

- Getting Started - I would send folks to the quickstart guide, which should be a focus in the next sprint. 
- Dev Reference -> Real Time link is broken. Also, we've been stylizing it 'Realtime' as a product name. 
- All User Guide links are broken but I think this is assuming the user guide PR is merged. 
- Graphic for config options doesn't make sense. Is this planned to be updated or shall we whip something up quickly? 

Final tiny design thing - any chance we can stop the nav between dev reference and user guide jumping when an option is clicked? 

This looks really, really good.

2023-06-26 18:57 UTC, rijkvanzanten requested changes, later dismissed
![CleanShot 2023-06-26 at 14 56 44@2x](https://github.com/directus/directus/assets/9141017/d81f1c09-6333-47ca-af85-8540355a2545)

Things seem to fall apart a little bit on the in-between breakpoint

2023-06-26 18:58 UTC, phazonoverload commented
> Things seem to fall apart a little bit on the in-between breakpoint

I reckon we should nix the snippet at this size

2023-06-26 18:59 UTC, rijkvanzanten commented
> > Things seem to fall apart a little bit on the in-between breakpoint
> 
> I reckon we should nix the snippet at this size

Yeah. A quick(er) fix would be to kick in the mobile breakpoint sooner, but it's nicer to have a proper in-between set of styles 👍🏻

2023-06-30 14:53 UTC, merged