Fix: Added a condition to handle validation errors related to non-unique fields.
directus/directus pull request #19068
Opened 2023-07-05 19:18 UTC by AshishBarvaliya

Closes: #18298 

In a sense, it can be argued that the bug is not technically valid. We already display a 'unique field error' message in the help icon when there is custom validation available. However, the issue lies in the fact that the custom validation field is free text, allowing users to enter any text. This can potentially mislead users, as illustrated in the mentioned example (#18298).

In this pull request, my intention is to specifically filter out the 'unique field error' in order to prevent any potential confusion.

2023-07-06 09:13 UTC, rijkvanzanten requested changes
Thanks @AshishBarvaliya! 🚀 

I think the same problem applies to any other type of system error as well 🤔  If you have a "value out of range" error for example, the app will normally show a "Value is too large for this field" (or something like that) message, but if you have a custom validation error message, the system one will be hidden as well. I think we might want to show the system error first no matter what the validation error type is, and append the custom validation message, rather than replacing the whole error value 🤔

2023-07-11 20:03 UTC, AshishBarvaliya commented
@rijkvanzanten Based on the code, it appears that the error message "Value is too large" does not belong to the `validationError` category. This can be observed when testing a field with a large value, as the error is displayed in a modal rather than as a field error.

-
<img width="503" alt="Screenshot 2023-07-11 at 3 55 44 PM" src="https://github.com/directus/directus/assets/49753983/99dcc7a6-ec79-4069-9270-aa72de1433ea">

-
<img width="652" alt="Screenshot 2023-07-11 at 3 55 26 PM" src="https://github.com/directus/directus/assets/49753983/4a887f5c-c46e-4b85-ace7-8a5ff928445b">

2023-07-12 09:50 UTC, rijkvanzanten commented
Oh that was just an example. I meant any of those validationError types that it does correctly display inline 👍🏻

2024-09-02 23:48 UTC, rijkvanzanten commented
Closing this due to inactivity

2024-09-02 23:48 UTC, closed without merging