Add oracledb to api/package.json
directus/directus pull request #19067
Opened 2023-07-05 15:22 UTC by stevefan1999-personal

Judging from https://github.com/directus/directus/actions/runs/5424640097/jobs/9864290720, there is only one unit test not being able to pass. Looks like we can just add it to the mix now.

2023-07-05 15:43 UTC, stevefan1999-personal commented
I can't regenerate pnpm lockfile, please do this for me

2023-07-05 15:59 UTC, stevefan1999-personal commented
Seeks like we are still using oracledb 5.x.x, hmm so the test result is not representative...

2023-07-05 16:11 UTC, rijkvanzanten commented
The node Oracledb package can't be installed under ARM platforms (eg any modern mac), so this is not something we can add to the dependencies section of the package.json file unfortunately

2023-07-05 16:26 UTC, stevefan1999-personal commented
> The node Oracledb package can't be installed under ARM platforms (eg any modern mac), so this is not something we can add to the dependencies section of the package.json file unfortunately

The latest 6.x version of oracledb implemented a pure JS driver which I think should be out of the box compatible. I did not see any breaking changes or migration guide so I assumed they have backward compatibility.

2023-07-06 09:14 UTC, rijkvanzanten commented
> The latest 6.x version of oracledb implemented a pure JS driver which I think should be out of the box compatible. I did not see any breaking changes or migration guide so I assumed they have backward compatibility.

Fantastic!! That's news to me 😄 Glad to hear that incredibly annoying requirement on native binaries that may or may not exist is a thing of the past. In that case, forget what I said before 🙂

2023-07-06 09:18 UTC, rijkvanzanten requested changes

2023-07-06 09:18 UTC, rijkvanzanten commented on .github/workflows/blackbox-main.yml
> +          pnpm -w -D add oracledb@6.0.2
I think the whole "Install Oracle client" block can be removed, as the dependency will exist in the `api`s package.json and is therefore installed in the regular install step

2023-07-10 03:21 UTC, stevefan1999-personal commented
Now we need to run the blackbox test...preferrably before merging the PR.

2023-07-10 07:17 UTC, stevefan1999-personal commented
```
✖ Bootstrap databases and start servers [FAILED: Directus-oracle bootstrap failed: 
 Error: select * from "directus_fields" where "interface" = :1 - ORA-01002: fetch out of sequence
    at Protocol._processMessage (/home/runner/work/directus/directus/dist/node_modules/.pnpm/oracledb@6.0.2/node_modules/oracledb/lib/thin/protocol/protocol.js:167:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ThinConnectionImpl.execute (/home/runner/work/directus/directus/dist/node_modules/.pnpm/oracledb@6.0.2/node_modules/oracledb/lib/thin/connection.js:802:7)
    at async Connection.execute (/home/runner/work/directus/directus/dist/node_modules/.pnpm/oracledb@6.0.2/node_modules/oracledb/lib/connection.js:861:16)
    at async Connection.<anonymous> (/home/runner/work/directus/directus/dist/node_modules/.pnpm/oracledb@6.0.2/node_modules/oracledb/lib/util.js:162:14) {
  offset: 0,
  errorNum: 1002,
  code: 'ORA-01002'
}
]
```

Hmm...[ORA-01002: fetch out of sequence tips (dba-oracle.com)](http://www.dba-oracle.com/t_ora_01002_fetch_out_of_sequence.htm)

2023-07-10 07:26 UTC, stevefan1999-personal commented
https://github.com/stevefan1999-personal/directus/blob/8c23245b47394a978888e7c502630c691666c0ab/api/src/database/migrations/20210802A-replace-groups.ts#L6-L7
I'm not sure if this is the offending statement...

2023-07-24 19:30 UTC, rijkvanzanten approved these changes
Change LGTM, but lets see if the test will pass now (no clue why it shouldn't after this change, but oracle has surprised me in the past)

2023-07-24 19:40 UTC, rijkvanzanten commented
Hmm same problem again. @aidenfoxx ever seen this issue fly by before? Kinda surprised it only started throwing this after upgrading the connection library

2023-07-24 20:02 UTC, aidenfoxx commented
I've not seen it before. Could be a race condition, if other migrations are still being brought up on the Oracle side for some reason? Only think I can think of that would cause such a basic query to fail. 🤷

2023-07-25 19:08 UTC, licitdev commented
I wonder if the error is due to mismatched package versions, as Knex is using `oracledb@5.5.0`, pending a dependency bump. 🤔 

Ref: https://github.com/knex/knex/pull/5630, https://github.com/knex/knex/issues/5615

2023-09-09 16:13 UTC, stevefan1999-personal commented
YES! I've been monitoring the blackbox test for Oracle under the Actions tab, and some of the tests started passing.

It seems like https://github.com/oracle/node-oracledb/releases/tag/v6.1.0 and https://github.com/oracle/node-oracledb/issues/1565 was indeed the blocking factor and now it is fixed a week ago now, we can finally get this PR moving on

2023-09-09 16:34 UTC, stevefan1999-personal commented
All cleared.
```
Test Suites: 36 passed, 36 total
Tests:       9968 passed, 9968 total
Snapshots:   0 total
Time:        1778.646 s
Ran all test suites.
❯ Stop Directus servers
❯ OracleDB
✔ OracleDB
✔ Stop Directus servers
```
@rijkvanzanten I think it is good. Let's merge it!

2023-09-11 03:06 UTC, stevefan1999-personal commented
@[paescuj](https://github.com/paescuj) sorry to bother but do you think we need to have a way to let PRs to test the main workflow so that they can be safely merged. I think we can limit certain action workflows to get permission from maintainers first before launching.

2023-09-11 07:58 UTC, paescuj commented
> It seems like https://github.com/oracle/node-oracledb/releases/tag/v6.1.0 and https://github.com/oracle/node-oracledb/issues/1565 was indeed the blocking factor and now it is fixed a week ago now, we can finally get this PR moving on.

Good news 😃 

> @rijkvanzanten I think it is good. Let's merge it!

Since we're using `oracledb` via Knex, we should wait for official support (https://github.com/knex/knex/issues/5615). This should land soon, Node.js 20 will be LTS from October 24.

> @[paescuj](https://github.com/paescuj) sorry to bother but do you think we need to have a way to let PRs to test the main workflow so that they can be safely merged. I think we can limit certain action workflows to get permission from maintainers first before launching.

I don't think this is necessary, it's usually sufficient to run only the SQLite test in PRs. Exceptions are rare and can be handled manually 👍

2023-09-11 08:11 UTC, stevefan1999-personal commented
@paescuj 

> Since we're using `oracledb` via Knex, we should wait for official support ([knex/knex#5615](https://github.com/knex/knex/issues/5615)). This should land soon, Node.js 20 will be LTS from October 24.

My concern is that the upstream Knex are trying to upgrade the version to 6.1.0 (as evidenced here: https://github.com/knex/knex/pull/5675). The workflow for Oracle tests seems fine, but if you look closely, test errors are deliberately ignored. From my own prediction I'd be safe to assume at least 10% of them are supposed to be failing. Still, our integration tests here at Directus shows there is no problem whatsoever (all integration tests with Oracle Driver 6.1.0 passed, with Knex version compatibility bypassed thanks to semver).

2023-09-12 08:49 UTC, stevefan1999-personal commented
@paescuj [Bump oracledb from 5.5.0 to 6.1.0 by dependabot\[bot\] · Pull Request #5675 · knex/knex (github.com)](https://github.com/knex/knex/pull/5675) is merged.

2023-09-13 19:26 UTC, rijkvanzanten commented
heyyyy exciting stuff! So just to confirm, we're awaiting a new Knex release and then it's time to ship it?! ⛵

2023-09-13 20:08 UTC, paescuj commented
> heyyyy exciting stuff! So just to confirm, we're awaiting a new Knex release and then it's time to ship it?! ⛵

That would be my preferred way ⛵😃

2023-11-23 06:09 UTC, stevefan1999-personal commented
**@paescuj** they have released 3.0.0 which included oracledb 6.1.0, mind merging this?

2023-11-23 09:39 UTC, paescuj commented
> **@paescuj** they have released 3.0.0 which included oracledb 6.1.0, mind merging this?

Yeah, I'll look into this soon 👍

2023-12-18 12:11 UTC, paescuj approved these changes
Thanks @stevefan1999-personal!

2023-12-18 12:17 UTC, merged

2023-12-18 14:37 UTC, stevefan1999-personal commented
@paescuj much appreciated for the follow ups!