Add max size to markdown interface
directus/directus pull request #19305
Opened 2023-07-31 10:57 UTC by Nitwel

fixes #18869

2023-07-31 11:19 UTC, br41nslug requested changes
The top bar stays in the view nicely but i am losing the last line now in both chrome and firefox 😬 
![chrome_bwp5aQJIcb](https://github.com/directus/directus/assets/9389634/330e5ea5-9f64-47bf-8029-3f7a01177662)
![firefox_UNrvvKcbCu](https://github.com/directus/directus/assets/9389634/15025252-2a6c-4b47-b409-3a1709777f23)

2023-08-01 08:45 UTC, Nitwel commented
Good catch, I made it now so that you can scroll to the bottom of it. For some reason, they made a hacky scrollbar by manually setting it's height using JS and you can only reach the very end using mouse scroll and not the scroll bar. But that feels like their fault for not going with standards.

2023-08-01 09:41 UTC, paescuj approved these changes

2023-08-01 12:11 UTC, br41nslug approved these changes

2023-08-01 12:14 UTC, licitdev approved these changes
🚀

2023-08-01 12:33 UTC, merged