Fix hiding navigation on root folder
directus/directus pull request #19518
Opened 2023-08-24 11:20 UTC by Nitwel

fixes #19493

2023-08-24 12:24 UTC, paescuj requested changes, later dismissed
We need to introduce new options to address this - simply showing the navigation in every case would be a breaking change, see https://github.com/directus/directus/issues/19493#issuecomment-1691575197.

2023-08-24 19:43 UTC, paescuj commented
Closing for now in favor of new pull request which addresses https://github.com/directus/directus/pull/19518#issuecomment-1691656913.

2023-08-25 10:42 UTC, Nitwel commented
Added the option now to show or hide the drawer manually. And when the root folder is set, it properly only shows that folder and it's children.

Also added tests for the useFiles composable. 🧪 

![grafik](https://github.com/directus/directus/assets/22577866/98f2f2a4-95f4-4d41-9751-335b3272fade)

![grafik](https://github.com/directus/directus/assets/22577866/ae2958f1-8aca-47e7-a786-dff8ed9e4460)

2023-09-04 13:44 UTC, DanielBiegler submitted a review, later dismissed
There seems to be a problem with refetching the folders after creating/deleting/moving folders

[Screencast from 04.09.2023 15:37:27.webm](https://github.com/directus/directus/assets/14810858/b793fa24-a5a5-4650-9171-aa668542d71a)

Switched back to main branch for comparison and dont have the problem there.

2023-09-21 07:21 UTC, paescuj approved these changes

2023-09-26 12:41 UTC, paescuj commented on app/src/views/private/components/files-navigation.vue
> +	return folders.value.find((folder) => folder.id === rootFolder!.value);
Great catch ❤️

2023-09-26 12:52 UTC, azrikahar approved these changes

2023-09-26 12:52 UTC, merged