API / Auth: Require OTP if Enforce TFA is enabled
directus/directus pull request #22190
Opened 2024-04-12 21:41 UTC by joselcvarela

While doing some tests I have enabled "Require 2FA" under the role page.
Then I have tried to login with a user via API under this role and it worked.

I was expecting that to not work, as I have enabled the Require 2FA.
Although the login worked expected.

In this PR we fix this behaviour so if Required 2FA is enabled on role, then an `otp` will be required on `login`.

## Scope

What's changed:

- Require OTP on login endpoint if role enforces 2FA

## Potential Risks / Drawbacks

- People thinking that MFA only applies to App and not API might have issues as `otp` field is now required per role conditions.

## Review Notes / Questions

- N/A

2024-04-15 09:35 UTC, paescuj commented
@joselcvarela Hmm, it seems like the previous check was designed that way in order to still allow users to login after role settings has been changed to "Require 2FA" and being able to set-up 2FA. Such users were redirected by the App: https://github.com/directus/directus/blob/dfe6cca40b34926012797d4cc127b1579c1d57d4/app/src/router.ts#L140-L142
So maybe instead of adjusting the login method, we can block all routes except for `/users/me/tfa/*` via a middleware, as long as a user hasn't set-up 2FA yet?

2024-04-15 09:59 UTC, br41nslug commented
As Pascal mentioned the user still working after toggling the "require 2fa" options is very much intentional until the first time the user logs into the App to actually configure 2fa.

2024-04-23 12:52 UTC, br41nslug requested changes
Looking back on this, the current solution blocks all logins when the "require TFA" is enabled for a role preventing users from logging into the app and setting up TFA which isnt ideal. The desired flow here is:
- when logging in using the App you get redirected to the TFA setup
- when logging in using the Api you get an error instructing you to set up TFA by logging into the App (as blindly redirecting may break server api interaction in unforeseen ways)
- We should probably document the API only flow for configuring TFA for "No App Access" + "Require TFA" roles

2024-09-02 23:15 UTC, rijkvanzanten commented
Closing this to be revisited later.

2024-09-02 23:15 UTC, closed without merging