Update Editor.js to 2.30+
directus/directus pull request #23837
Opened 2024-10-10 16:23 UTC by paescuj

## Scope

What's changed:

- Update Editor.js itself as well as plugin packages
- Adjust style overrides for changes made in [Editor.js 2.30](https://github.com/codex-team/editor.js/releases/tag/v2.30.0)

---

Unblocks #23814

2024-11-27 01:09 UTC, rijkvanzanten reviewed
Code changes LGTM, @directus/web to confirm functionality 🚀

2024-11-27 05:42 UTC, connorwinston requested changes
Seems good functionality wise and code wise as well! However, there are some weird styling things going on which idk if you want to address those in here. Note this is in Chrome.

_Should the whole popover scroll and not just the last 3 items for editing an image block?_
<img width="234" alt="image" src="https://github.com/user-attachments/assets/e8b3b8aa-3bf5-4a69-919b-d786ccbfadfb">

_If I click to open the popover and it is at the bottom of the page it gets hidden, the position of the popover doesn't match the available space. I can't nail down a pattern of when this is happening, but changing the amount of content in the editor and the overall length of the item form affects it._
<img width="264" alt="image" src="https://github.com/user-attachments/assets/24f378d1-4bd6-43e0-bf27-35a06c597caf">

_If you open the popover, then scroll the page where the popover goes out of the view a second scroll bar will appear around the directus app as a whole. This only happens when the above mentioned popper position is out of place._
<img width="332" alt="image" src="https://github.com/user-attachments/assets/9b48ac90-0fc0-48be-bdab-61f8ce4d0688">

2024-12-10 14:45 UTC, paescuj commented
> Seems good functionality wise and code wise as well! However, there are some weird styling things going on which idk if you want to address those in here. Note this is in Chrome.

Thanks for your review! ❤️ 

> _Should the whole popover scroll and not just the last 3 items for editing an image block?_ <img alt="image" width="234" src="https://private-user-images.githubusercontent.com/12714889/390276041-e8b3b8aa-3bf5-4a69-919b-d786ccbfadfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MzEwMTEsIm5iZiI6MTczMzgzMDcxMSwicGF0aCI6Ii8xMjcxNDg4OS8zOTAyNzYwNDEtZThiM2I4YWEtM2JmNS00YTY5LTkxOWItZDc4NmNjYmZhZGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDExMzgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NGQ2ODdmNzVmNWNlY2M3YmQwNjI3MjA4NTEwMTNkNTE4Yjg3N2ExYjY0MzE4YzczZjVmYzM3NDMzOGMwNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vxMKHcLSZPG8reoDi5HXl7sXeU3-4my7kfSynH4qlM4">

I couldn't reproduce this in any of the major browsers 🤔 The scroll area always wraps all options.

> _If I click to open the popover and it is at the bottom of the page it gets hidden, the position of the popover doesn't match the available space. I can't nail down a pattern of when this is happening, but changing the amount of content in the editor and the overall length of the item form affects it._ <img alt="image" width="264" src="https://private-user-images.githubusercontent.com/12714889/390276359-24f378d1-4bd6-43e0-bf27-35a06c597caf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MzEwMTEsIm5iZiI6MTczMzgzMDcxMSwicGF0aCI6Ii8xMjcxNDg4OS8zOTAyNzYzNTktMjRmMzc4ZDEtNGJkNi00M2UwLWJmMjctMzVhMDZjNTk3Y2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDExMzgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YzM2Y2UyOTUxMjcwNjlhZWUxNTQ5NzczZTY2ZGNmMzA4NWEwODc5YTU0ZDRjOTcwODBhMGE0Njc4NmYyMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1ZQvg5A7pTciDAQoU0UcnI4i6TRjFaQoVfTp3YZa7zc">

For the placement of the toolbars, Editor.js only looks at the editor area and not at the viewport. Unfortunately, there's no option for changing that and I also think that has already been the case before the update to 2.30+.

> _If you open the popover, then scroll the page where the popover goes out of the view a second scroll bar will appear around the directus app as a whole. This only happens when the above mentioned popper position is out of place._ <img alt="image" width="332" src="https://private-user-images.githubusercontent.com/12714889/390276592-9b48ac90-0fc0-48be-bdab-61f8ce4d0688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MzEwMTEsIm5iZiI6MTczMzgzMDcxMSwicGF0aCI6Ii8xMjcxNDg4OS8zOTAyNzY1OTItOWI0OGFjOTAtMGZjMC00OGJlLWJkYWItNjFmOGNlNGQwNjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDExMzgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyOWUzZGI5NTAzMDBjZWU0ZjUzZDRlNDk0MzE5ZTg2ZTlkNjM3YzQxYTAxNTNiMTY5MWQ0Y2Y3ODFlZmVhNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UK5d1BGNlPWXMcdf1H8F-Blq0ukTRhphVBqDfQIQyzo">

I couldn't reproduce that one either, but I feel like it isn't related to any of the styling changes included in this PR.

2025-01-06 18:21 UTC, connorwinston approved these changes
LGTM!! 🎉

2025-01-06 18:47 UTC, merged