Fix enforcing `chunkSize` when TUS is not enabled
directus/directus pull request #24002
Opened 2024-11-07 12:55 UTC by ComfortablyCoding

## Scope

What's changed:

- We no longer incorrectly enforce chunkSize if TUS is not enabled

## Potential Risks / Drawbacks

- None

## Review Notes / Questions

- None

---

Fixes #24001

2024-11-13 20:46 UTC, licitdev reviewed
Let's update the default chunk size to `8mb` which should be a valid chunk size across drivers.

On a side note, I can confirm that `8mb` chunk size works for the S3 driver.

2024-11-14 03:33 UTC, ComfortablyCoding commented
> Let's update the default chunk size to `8mb` which should be a valid chunk size across drivers.

Agreed, added via 6aafc99

2024-11-15 20:02 UTC, licitdev approved these changes

2024-11-15 20:07 UTC, licitdev requested changes
Changeset needs to be updated

2024-11-15 20:11 UTC, ComfortablyCoding commented
> Changeset needs to be updated

Updated, should we consider `env` change as major? Technically changing the default is a breaking change

2024-11-19 08:58 UTC, licitdev commented on .changeset/cyan-sloths-appear.md
> +Fixed enforcing `chunkSize` when TUS is not enabled
```suggestion
Fixed enforcing `chunkSize` when TUS is not enabled and updated the default `TUS_CHUNK_SIZE` to `8mb`
```

2024-11-19 16:25 UTC, licitdev approved these changes

2024-11-19 16:27 UTC, merged