Assign admin policy to a new role created via command line when needed
directus/directus pull request #24022
Opened 2024-11-11 00:46 UTC by NickSettler

## Scope

Creating a new role via command line with admin access doesn't work. It happens, because this CLI command still relies on the old database schema, which had `admin_access` property as a part of `Role` type. 

Addition of policies changed this concept and migrated `admin_access` field to a policy database table.

The command for creating an admin role via the command line remained unchanged since that time.

What's changed:

- Admin role creation via CLI adds a corresponding row in the directus_access table
- In case there is no admin policy, the logger outputs an error

## Potential Risks / Drawbacks

- I cannot see any. Admin role creation is not working now. Default role creation remains unchanged

## Review Notes / Questions

- ...

---

Fixes #24021

2024-11-26 23:57 UTC, rijkvanzanten requested changes

2024-11-26 23:57 UTC, rijkvanzanten commented on api/src/cli/commands/roles/create.ts
> +		const adminPolicyId = await policiesService.knex
We should use `readOne` from the service here, as there might be differences in how databases store the values under the hood (f.e. in SQLite a boolean is `0` / `1` and will fail with a "where `true`"). The Directus methods will type cast these differences away.

That being said, seeing you're trying to create a whole new role, should we instead opt to just create a new admin policy that's just for this role? 🤔 Might be less confusing than reusing one that might be named for a certain use case or group.

2024-11-27 00:02 UTC, rijkvanzanten commented
Thanks @NickSettler! And welcome to the repo 🙂 Little usage question up above, but otherwise LGTM 🚀

2024-11-27 00:36 UTC, NickSettler commented
> Thanks @NickSettler! And welcome to the repo 🙂 Little usage question up above, but otherwise LGTM 🚀

Thank you! 🙂

2024-12-05 19:26 UTC, rijkvanzanten approved these changes

2024-12-05 19:29 UTC, merged