Fix 24023/ensure different language in translation split view
directus/directus pull request #24137
Opened 2024-12-03 20:02 UTC by eremannisto

## Scope

What's changed:

- Modified language selection logic in split-view to prevent duplicate languages
- Improved TypeScript typing for null safety
- Added better fallback logic for language selection

Before:
<img width="836" alt="before" src="https://github.com/user-attachments/assets/11e8c3e5-9be8-4f39-a11c-bdb7c04ff4c0">

After:
<img width="888" alt="languages" src="https://github.com/user-attachments/assets/58b6beee-bdba-4c70-9d74-70538f8015a6">
<img width="888" alt="english" src="https://github.com/user-attachments/assets/4119328c-cc84-4685-97fa-56b47887688e">
<img width="888" alt="finnish" src="https://github.com/user-attachments/assets/a745a81f-62f0-4560-943c-635e73248d6c">
<img width="888" alt="none" src="https://github.com/user-attachments/assets/36832959-c012-4832-a064-67682b480d3c">
<img width="888" alt="one" src="https://github.com/user-attachments/assets/e69c5ff6-1dcc-46d5-8901-27cd05a6a438">

## Potential Risks / Drawbacks

- None identified - changes only affect the UI behavior of translation split-view
- Maintains existing fallback behavior if only one language is available

## Review Notes / Questions

- The fix prioritizes showing different languages in split-view while respecting user/default language preferences
- The changes include TypeScript improvements for better type safety

---

Fixes [#24023](https://github.com/directus/directus/issues/24023)

2024-12-03 20:15 UTC, eremannisto commented
Hi! First time contributing to Directus here. Please let me know if any adjustments are needed to align with the project's PR guidelines.

2024-12-04 19:01 UTC, AlexGaillard requested changes, later dismissed
Thanks for the PR @eremannisto 👋 

Great work finding the source of the problem and also the fix. I've included some thoughts about how we can maybe simplify this a little bit and maybe be a bit more performant.

I think we can get this wrapped up pretty quickly 🚀

2024-12-04 22:26 UTC, AlexGaillard commented on app/src/interfaces/translations/translations.vue
> +				secondLang.value = (alternativeLang || defaultLang || languages.value[0])?.[pkField];
I think this comment got doubled when github conked out on me during review 🙃

2024-12-05 06:04 UTC, eremannisto commented
Thanks @AlexGaillard for the detailed code review and optimization suggestions! I made the suggested changes and tested it, and seems to work perfeclty. :)

2024-12-05 18:17 UTC, rijkvanzanten approved these changes

2024-12-05 18:18 UTC, rijkvanzanten commented
Thanks @eremannisto! And welcome to the repo 🙂 I'll let @AlexGaillard smack that merge button. LGTM! 🚀

2024-12-05 19:23 UTC, merged