Add prometheus support
directus/directus pull request #24233
Opened 2024-12-17 02:30 UTC by ComfortablyCoding

## Scope

What's changed:

- Added basic prometheus support
   - Only the pull method is currently supported via the `/metrics` endpoint
   - It can be enabled via `METRICS_ENABLED` and the schedule can be controlled via `METRICS_SCHEDULE`
   - Access to the endpoint is restricted to admins or requests containing a token in the `METRICS_TOKENS` list
   - Metrics generated can be controlled via its respective `METRICS_<METRIC>_ENABLED` env variable

## Potential Risks / Drawbacks

- if the `METRICS_SCHEDULE` is set at a high frequency it can place load on the server
- If the initial request to metrics occurs before the first schedule is run no metrics are returned
- If the prometheus pull frequency is higher than the `METRICS_SCHEDULE` stale metrics will be returned

## Review Notes / Questions

- Should we support metric generation frequency on a per metric basis?
- Do we want `read` and `write` over `response_time`? If it is a nice to have we can leave it with `response_time` and add an option for more granular control in the future
- `-1` is returned for any metrics in an error state

---

Fixes SER-456

2025-01-02 15:00 UTC, licitdev commented on api/src/schedules/metrics.test.ts
> +	test('Schedules synchronized job', async () => {
```suggestion
	test('Schedules job', async () => {
```

2025-01-06 15:02 UTC, wrynegade approved these changes
I really like the method here of preparing the metrics on a schedule before they are actually requested :+1: Along with the control over `METRICS_SCHEDULE` and `METRICS_TOKENS` this should be an excellent starting point for Prometheus integration.

2025-01-14 10:07 UTC, danielBreitlauch reviewed
There seems to be the place missing where we calculate the histogram etc.

2025-01-14 14:50 UTC, ComfortablyCoding commented on api/src/schedules/metrics.ts
> +	if (lockedAt !== 0 && lockedAt > now - METRICS_LOCK_TIMEOUT) {
This will/should lock it so that duplicate runs will not happen on the same instance which is the expected behaviour.

2025-01-17 17:57 UTC, ComfortablyCoding commented on api/src/metrics/lib/create-metrics.ts
> +			if (await hasDatabaseConnection()) {
Resolved 3418b77ed85967822639bb88cf8ce9b304fca5d1 as we now listed on the `query-response` db event

2025-01-17 17:58 UTC, ComfortablyCoding commented on api/src/metrics/lib/create-metrics.ts
> +			await cache.set(`metrics-${checkId}`, '1', 5);
We now just track error counts for cache, as such this is no longe applicable.

2025-01-22 10:41 UTC, danielBreitlauch requested changes

2025-01-22 10:41 UTC, danielBreitlauch commented on api/src/metrics/lib/create-metrics.ts
> +		return registry.metrics();
For the AggregatorRegistry to work we need to call clusterMetrics() otherwise we only get the local ones.

2025-01-22 16:48 UTC, ComfortablyCoding commented on api/src/metrics/lib/create-metrics.ts
> +		return registry.metrics();
Upon further investigation it is not possible to use `clusterMetrics` in a `pm2` context as it utilizes the cluster module [which doesn't work with pm2](https://github.com/Unitech/pm2/issues/2885#issue-229467279).

Due to this we will need to add our own custom IPC logic as originally proposed

2025-01-23 19:06 UTC, ComfortablyCoding commented on api/src/metrics/lib/create-metrics.ts
> +		return registry.metrics();
IPC logic added in [66979cd](https://github.com/directus/directus/pull/24233/commits/66979cd12d952c3dd0a98c06f1c0347462c12622) and fine tuned a bit in [97afd49](https://github.com/directus/directus/pull/24233/commits/97afd49f926e5c52d495246008d7991cd19e261c).

2025-01-24 14:34 UTC, danielBreitlauch approved these changes
LGTM 🚀 .

Technically it is weird. The metrics go through a pipeline; own registry -> aggregated json distributed (when scheduled) -> collected (when requested).

We have to make sure the scheduling and requesting happens in the same frequency.

2025-01-24 14:34 UTC, danielBreitlauch commented on api/src/metrics/lib/create-metrics.ts
> +				return AggregatorRegistry.aggregate(aggregate).metrics();
Nice way to reuse the `AggregatorRegistry`'s functionality without using their transport method.

2025-01-24 15:02 UTC, paescuj commented on api/src/schedules/metrics.ts
> +	lockedAt = 0;
We should put this in a `try...finally` block to ensure lockedAt is reset even if the generation fails for some reason:

```suggestion
	try {
		await metrics.generate();
	} finally {
		lockedAt = 0;
	}
```

2025-01-24 15:54 UTC, ComfortablyCoding commented on api/src/schedules/metrics.ts
> +	lockedAt = 0;
Agreed!

2025-01-24 15:56 UTC, ComfortablyCoding commented on api/src/metrics/lib/create-metrics.ts
> +				return AggregatorRegistry.aggregate(aggregate).metrics();
Thanks :)

2025-01-24 16:06 UTC, ComfortablyCoding commented
> We have to make sure the scheduling and requesting happens in the same frequency.

We can add a note in the documentation mentioning this for PM2 contexts but it is left up to the user to ensure they are in sync

2025-01-24 16:20 UTC, ComfortablyCoding commented on api/src/schedules/metrics.ts
> +	lockedAt = 0;
Per discussion update to use catch in addition to finally via ee0d44d0b7fc68976351b6661186bfb035c4e330

2025-02-06 16:07 UTC, paescuj reviewed
Should we mention somewhere that the metrics are sort of in an experimental state (i.e. we might still tweak some parts)?

2025-02-07 14:42 UTC, ComfortablyCoding commented on api/src/database/index.ts
> +				useMetrics().getDatabaseResponseMetric()?.observe(delta);
While we do initialize it, no collection is actually set. Each metric has its own `*_ENABLED` check that will return `null` if not enabled. As such I do not see the need to add an additional `?` to every `useMetrics` call. 

If we do ever change this logic it can also be accounted for then.

2025-02-07 14:47 UTC, ComfortablyCoding commented on docs/reference/system/metrics.md
I am ok adding the restriction that this endpoint is for admin or users passing in the metrics token as it has precedent. 

I do not believe we should add the `env` variables any place other than the `config` list as we do not do this for any other endpoint that requires `env` variables to be enabled (e.g. TUS).

2025-02-07 14:51 UTC, paescuj commented on docs/reference/system/metrics.md
I wouldn't list the specific envs either, but mention that this endpoint is disabled and restricted by default.

2025-02-07 15:06 UTC, paescuj commented on api/src/database/index.ts
> +				useMetrics().getDatabaseResponseMetric()?.observe(delta);
It is on optimization-level for sure, but seeing that (under pm2) we do initialize unnecessary listeners it might be worth it and it would additionally give us the possibility to save a few resources more by dynamically importing `create-metrics.js` 🤔 Also it just feels a tad odd that collection of database metrics can be enabled and is actually performed (`METRICS_DATABASE_ENABLED`) while metrics as a whole (`METRICS_ENABLED`) is disabled.

2025-02-07 15:06 UTC, ComfortablyCoding commented
> Should we mention somewhere that the metrics are sort of in an experimental state (i.e. we might still tweak some parts)?

I would lean towards no as we do not have the concept of experimental features. Currently if breaking changes are needed we implement as needed and document it as breaking in the release

2025-02-07 15:15 UTC, paescuj commented on docs/reference/system/metrics.md
Well, but in this case it's the whole endpoint that is disabled.
When visiting this doc page as an admin/user, then checking `/metrics` I'd be confused that there's no result and probably I'd also have no idea how authentication is meant to be used here without looking into the code.
1-2 sentences should do it, but IMO some basic info is mandatory if we do not explicitly mark this feature as experimental/internal.

2025-02-07 15:17 UTC, ComfortablyCoding commented on docs/reference/system/metrics.md
> +Retrieve monitored metrics for connected services.
```suggestion
Retrieve monitored metrics for connected services. This endpoint is only available to admin users or requests containing a metric token defined in the `METRICS_TOKENS` list with the following authorization header format `Authorization: Metric <token>`
```

2025-02-07 15:17 UTC, ComfortablyCoding commented on docs/reference/system/metrics.md
> +Retrieve monitored metrics for connected services.
cc @paescuj

2025-02-07 15:20 UTC, ComfortablyCoding commented on docs/reference/system/metrics.md
TUS functions the same way by disabling the entire endpoint if not enabled https://github.com/directus/directus/blob/3581f5eff122599b434dde69befd88697d1fc458/api/src/app.ts#L289-L291

2025-02-07 15:21 UTC, ComfortablyCoding commented on docs/reference/system/metrics.md
> I am ok adding the restriction that this endpoint is for admin or users passing in the metrics token as it has precedent.

Added suggested update to https://github.com/directus/directus/pull/24233#discussion_r1946696975

2025-02-07 15:31 UTC, paescuj commented on docs/reference/system/metrics.md
> +Retrieve monitored metrics for connected services.
Awesome, thanks! ❤️ 

Just suggesting a small addition:

```suggestion
Retrieve monitored metrics for connected services.

This endpoint is disabled by default and, if enabled, only available to admin users or requests containing a metric
token defined in the `METRICS_TOKENS` list with the authorization header format `Authorization: Metric <token>`.

```

2025-02-07 18:35 UTC, ComfortablyCoding commented on api/src/database/index.ts
> +				useMetrics().getDatabaseResponseMetric()?.observe(delta);
Agreed, implemented via 264fe98fe173808eac692e4d8368868686b36c0c. As discussed since a dynamic import would change it to be a promise based response leaving that off for now

2025-02-07 19:09 UTC, paescuj commented on api/src/metrics/lib/create-metrics.test.ts
> +	test('Returns defined when metrics is disabled', () => {
```suggestion
	test('Returns defined when metrics is enabled', () => {
```

2025-02-07 19:18 UTC, ComfortablyCoding commented on api/src/metrics/lib/create-metrics.test.ts
> +	test('Returns defined when metrics is disabled', () => {
Copy paste strikes again 😓

2025-02-07 19:19 UTC, ComfortablyCoding commented on packages/env/src/constants/directus-variables.ts
> +	'METRICS_STORAGE_ENABLED',
CSV approach implemented via https://github.com/directus/directus/pull/24233/commits/f915af00c322c15da5d6b9a245f2e92b3266e2b8

2025-02-10 13:05 UTC, paescuj commented on .changeset/strange-coins-play.md
> +'docs': minor
```suggestion
'@directus/env': patch
'docs': patch
```

2025-02-10 13:05 UTC, paescuj approved these changes

2025-02-13 12:16 UTC, ComfortablyCoding commented on docs/self-hosted/config-options.md
> +| `METRICS_SCHEDULE` | The cron schedule at which to generate the metrics, the default is every minute. Metrics are not generated at request time but instead return the last generated values per the
Yes, I'll move this to a note and be more specific

2025-02-13 14:32 UTC, ComfortablyCoding commented on docs/self-hosted/config-options.md
> +| `METRICS_SCHEDULE` | The cron schedule at which to generate the metrics, the default is every minute. Metrics are not generated at request time but instead return the last generated values per the
Resolved as discussed via da828c923858f0889f0e0bb11e824a23061c7fd1

2025-02-17 10:21 UTC, licitdev commented on api/src/metrics/lib/create-metrics.ts
> +	const services: MetricService[] = (env['METRICS_SERVICES'] as MetricService[] | undefined) ?? [];
Let's also utilize the `toArray` here.

2025-02-17 10:21 UTC, licitdev commented on .changeset/strange-coins-play.md
> +---
I think we should bump this to a `minor` release.

```suggestion
---
'directus': minor
```

2025-02-17 10:44 UTC, paescuj commented on api/src/controllers/metrics.ts
> +		}
This is already performed in https://github.com/directus/directus/blob/7cf1d02792b7126b23b95ba4392469deb75e4eed/packages/env/src/lib/cast.ts#L26-L29 since we've added it to the type map https://github.com/directus/directus/blob/64848a5219ddfb4e1484303b32b0fe6e328603d8/packages/env/src/constants/type-map.ts#L38
so in this case the casting should be fine 👍

2025-02-17 10:52 UTC, licitdev commented on api/src/controllers/metrics.ts
> +		}
TIL on the distinction with other array env vars that aren't in this type map! Thanks!

2025-02-17 13:33 UTC, ComfortablyCoding commented on api/src/controllers/metrics.ts
> +		}
Additionally it also results in `[undefined]` when the value is not provided if I remember correctly.

2025-02-17 13:51 UTC, licitdev commented on api/src/controllers/metrics.ts
> +		}
Yup! Hence there's a need for `.filter`if we're using `toArray` 😄

2025-02-19 11:31 UTC, merged

2025-02-25 08:52 UTC, asitanc commented
@ComfortablyCoding Will there be a way to also add custom prefix/namespace? As far as I see, it has `directus_` prefix, but it would be cool to have this option on env. Thank you!

2025-02-25 13:58 UTC, ComfortablyCoding commented
> @ComfortablyCoding Will there be a way to also add custom prefix/namespace? As far as I see, it has `directus_` prefix, but it would be cool to have this option on env. Thank you!

In the current iteration unfortunately no, feel free to file an issue suggesting this improvement 👍