[rbs] fix tiny tweak 24287
directus/directus pull request #24288
Opened 2024-12-26 21:06 UTC by robsoncombr

Before the change we have margin bigger than the line I noticed it before but during some changes it was lost from the previous PR so I'm sending this one as a re-opening action.

I made the red background to make it easier to note the difference it tiny but the right is really 1px;

With margin 2px;

![image](https://github.com/user-attachments/assets/e0d6cea8-8a59-4dad-8f33-c50dfd8e3f46)

With margin 1px;

![image](https://github.com/user-attachments/assets/80480b85-c0ec-4c2b-8b78-848d5dedba75)

Fixes #24287 24287

2024-12-26 21:17 UTC, rijkvanzanten requested changes

2024-12-29 12:10 UTC, robsoncombr commented on api/src/auth/drivers/oauth2.ts
> +			client_id: clientId.toString(),
Oops 🤭

2024-12-29 13:37 UTC, paescuj commented
@robsoncombr Thanks for this pull request! ❤️ 

Could you help me understand why you want to reduce the margin / border-width to 1px?
The current value of 2px is in line with e.g. the border with of input fields and 1px is hardly visible anymore in my opinion.

I don't see an issue with the current styling:

<img width="300" alt="login-page" src="https://github.com/user-attachments/assets/8fdcaf6c-bca2-48b5-a959-e8977ca4816b" />

2024-12-30 19:25 UTC, robsoncombr commented
@paescuj interesting, and here is different for the record, windows 11 + edge
Allow me to review this, will let you know..

2024-12-30 21:47 UTC, robsoncombr commented
@paescuj you know what? you are right while I'm old and needing to change my glasses.

took new screenshots with max zoom with original code.

no hover
![image](https://github.com/user-attachments/assets/cc104e6b-e975-4899-ade3-81587e717eb3)

hover
![image](https://github.com/user-attachments/assets/d13f0d74-7bbd-4a51-b20b-0d16a5050428)
![image](https://github.com/user-attachments/assets/0672f619-5b10-4ff5-b702-9406ab188597)

@rijkvanzanten ouch!

better we forget this all and close as being a false alarm 😂 it was just a crazy blind programmer.

and happy new year to everyone!

2024-12-31 16:38 UTC, closed without merging

2024-12-31 16:39 UTC, AlexGaillard commented
No worries @robsoncombr. Thanks for all your hard work. 👍 And HNY to you too 🎉