Added escaping on file paths including "\u"
directus/directus pull request #6215
Opened 2021-06-11 16:20 UTC by skizer

- Added escaping on file paths including "\u" as JS inteprets this as hexa value
 _-- Occurs on Windows OS due nodejs path.join converting paths from "/" to "\"_

2021-06-14 15:30 UTC, nickrum requested changes
I think we should use `require('path/posix')` instead of `require('path')` here, as those paths are used as vue-router paths in the App. That should fix the issue on Windows.

2021-06-23 11:37 UTC, nickrum commented
@skizer What do you think of the change I proposed? I can take over from here if you want 😉

2021-06-25 12:30 UTC, 1adetbeyfendi commented
working, i think build before os check <3  @nickrum

2021-06-28 20:30 UTC, nickrum approved these changes

2021-06-28 20:44 UTC, rijkvanzanten approved these changes

2021-06-28 20:46 UTC, merged