Allow custom transformations of assets
directus/directus pull request #6593
Opened 2021-07-01 00:53 UTC by tim-smart

This exposes one query parameter `transforms`, which is a JSON array of
sharp transformation methods + arguments.

It also updates the system asset presets. The UX for this still needs some work

2021-07-01 01:22 UTC, tim-smart commented on api/src/services/assets.ts
> +		].join('__');
Possible to normalize the options and create some sort of hash?

2021-07-01 01:23 UTC, tim-smart commented on api/src/database/system-data/fields/settings.yaml
> +                - field: options
There has to be a better way lol.

2021-07-01 02:30 UTC, tim-smart commented on api/src/database/system-data/fields/settings.yaml
> +                - field: options
Partially kept old easy to use fields.

2021-07-01 03:11 UTC, tim-smart commented on api/src/services/assets.ts
> +		].join('__');
Used `object-hash` from NPM instead.

2021-07-02 09:45 UTC, rijkvanzanten commented
Love it! Thanks @tim-smart 🙂

2021-07-04 01:59 UTC, tim-smart commented
I'm going to stop here on this one.

Not sure if you liked the direction this was taking?

We will need this in a week or two, so will float this patch on a fork until Directus has something for reformatting images etc.

2021-07-04 11:20 UTC, rijkvanzanten commented
> Not sure if you liked the direction this was taking?

I think the direction of putting all the options under a single `transform` query param makes total sense. 


Haven't had the time to do a full review yet (I'm OOO currently), but this all looks very promising on first glance 🙂

2021-07-12 16:05 UTC, SeanDylanGoff commented
@tim-smart key-value pairs instead of an array won't work because order matters for the transforms, right?
Because if we did have an object we could use the existing filter implementation for advanced configuration on which transforms are allowed and which aren't

2021-07-12 20:55 UTC, tim-smart commented
> @tim-smart key-value pairs instead of an array won't work because order matters for the transforms, right?
> Because if we did have an object we could use the existing filter implementation for advanced configuration on which transforms are allowed and which aren't

Yes, order matters. You can also run the same transformation function more than once - you can't have duplicate keys in an object :)

2021-07-21 16:24 UTC, rijkvanzanten requested changes
Little hard to understand how to use it exactly without having docs.

I'll take care of resolving the comments 👍🏻

2021-07-21 16:24 UTC, rijkvanzanten commented on api/src/controllers/assets.ts
> +			} catch (_) {
```suggestion
			} catch {
```

2021-07-21 16:24 UTC, rijkvanzanten commented on api/src/database/system-data/fields/settings.yaml
> +                          text: webp
These are already listed under `format` above, no need to duplicate here

2021-07-21 16:24 UTC, rijkvanzanten commented on api/src/database/system-data/fields/settings.yaml
> +                            note: JSON representation of the argument
We should figure out how to document this, little difficult to understand how to use it

2021-07-21 16:47 UTC, rijkvanzanten commented
@tim-smart This is great, thanks!

The only thing I'm slightly worried about is the complexity of the parameter. Something like `transforms=[["resize", [200, 300, { "fit": "contain", "position": "right top", "background": { "r": 255, "g": 150, "b": 0, "alpha": 0.5 }}]]` might be a little intimidating for less-experienced users, but at the same time, I wouldn't really know how to optimize that without reinventing Sharp's full API in our assets layer 🤔  This is just a side effect of exposing the full API of Sharp of course, which in itself is crazy 

PS good thinking on using object-hash for the asset filename. Jealous I didn't think of that earlier! 😄

2021-07-21 18:25 UTC, rijkvanzanten commented
Update: I'll add support for the "simple" transforms back in (eg `width`/`height`/`quality`/`format`). These are obviously limited in what they can do (no order, no complex settings), but allow a nice simple API for most transformations. Users who have a need for the more advanced configuration can use the full transforms escape hatch

2021-07-21 19:29 UTC, rijkvanzanten commented
Update 2: while the setup using the repeater was nice, it did mean we'd have a total of 3 different syntaxes for providing the transformation options. I've reduced that to a json input (for now, we should add a custom sharp-options interface later) so we have a single API for controlling the transforms

2021-07-21 19:57 UTC, rijkvanzanten approved these changes

2021-07-21 19:57 UTC, merged

2021-07-21 21:45 UTC, tim-smart commented
> Update: I'll add support for the "simple" transforms back in (eg `width`/`height`/`quality`/`format`). These are obviously limited in what they can do (no order, no complex settings), but allow a nice simple API for most transformations. Users who have a need for the more advanced configuration can use the full transforms escape hatch

Sound good.

Just looking at the changes, I'm not sure if using the simple params will do anything? Can see where they get resolved :)

2021-07-21 21:47 UTC, tim-smart commented
> > Update: I'll add support for the "simple" transforms back in (eg `width`/`height`/`quality`/`format`). These are obviously limited in what they can do (no order, no complex settings), but allow a nice simple API for most transformations. Users who have a need for the more advanced configuration can use the full transforms escape hatch
> 
> Sound good.
> 
> Just looking at the changes, I'm not sure if using the simple params will do anything? Can't see where they get resolved :)

Nevermind, I see what's going on now!