Use relative base url for app and extensions
directus/directus pull request #6923
Opened 2021-07-22 11:59 UTC by nickrum

This also adds a url util and uses it when working with PUBLIC_URL in other places.

2021-07-23 13:27 UTC, rijkvanzanten commented
Why should we use a relative base URL? Doesn't that mean that refreshes on a path will cause problems? Eg if you refresh `/collections`, doesn't that mean it'll start loading things from `/collections/assets/index.js` etc?

2021-07-23 14:24 UTC, nickrum commented
In this case, _relative_ means _relative to the origin_. So, the base URL will always start with a leading slash. The `Url` utils doesn't currently support _path-relative_ URLs (or rather they are converted to _origin-relative_ URLs as that is how the native `URL` class handles it).

2021-07-23 14:27 UTC, rijkvanzanten commented
Ohhh gotcha!

2021-08-26 14:50 UTC, rijkvanzanten requested changes

2021-08-26 21:11 UTC, rijkvanzanten approved these changes

2021-08-26 21:11 UTC, merged