Add Filter interface
directus/directus pull request #7492
Opened 2021-08-18 16:03 UTC by Nitwel

This will add a dedicated interface for creating filters for search querys and conditional fields.

2021-08-19 12:52 UTC, dimitrov-adrian commented
I was started doing pretty same in my end, but in different approach. Basically I was porting sidebar filters as a separate component that am using in sidebar and in a new system filter interface. Then this interface come in place to o2m, m2o and file/images interfaces as an option, so to add filter ability to relational interface options.

2021-08-23 08:40 UTC, Nitwel commented
Here's a preview on how the filter interface will look.
![grafik](https://user-images.githubusercontent.com/22577866/130417276-4ef80305-bfc8-4b2b-abc5-85aba713892d.png)

2021-08-31 13:45 UTC, Oreilles commented
Awesome. Being able to use this in layouts advanced filter would be great too.

2021-09-01 22:40 UTC, rijkvanzanten commented
Updated design direction:

<img width="313" alt="CleanShot 2021-09-01 at 18 40 39@2x" src="https://user-images.githubusercontent.com/9141017/131754673-996c47d1-1d95-4959-b9ac-c2a373b8d702.png">

2021-09-10 18:30 UTC, rijkvanzanten requested changes

2021-09-10 18:30 UTC, rijkvanzanten commented
<img width="336" alt="CleanShot 2021-09-10 at 14 30 23@2x" src="https://user-images.githubusercontent.com/9141017/132900708-cccf1f0c-bb20-4ea1-a5d9-5cb674f56f92.png">

We have to improve the default state

2021-09-10 19:16 UTC, rijkvanzanten commented
The changes in this PR seemed to have made the v-field-template interface pretty unstable 🤔

2021-09-10 19:28 UTC, rijkvanzanten requested changes

2021-09-10 19:28 UTC, rijkvanzanten commented on app/src/components/v-select/v-select.vue
> +		<v-list class="list" :mandatory="mandatory" @toggle="$emit('group-clicked', $event)">
group-toggle

2021-09-10 19:28 UTC, rijkvanzanten commented on app/src/components/v-select/v-select.vue
> +		},
This might have to be on a per-group level instead of as a general prop on the whole v-select

2021-09-10 19:28 UTC, rijkvanzanten commented on app/src/interfaces/_system/system-filter/field-input.vue
> +			].includes(field.comparator)
We should make these shared constants and pull from that instead

2021-09-10 19:28 UTC, rijkvanzanten commented on app/src/interfaces/_system/system-filter/field-input.vue
> +		});
We should rely on the default interfaces list for this 🤔

2021-09-10 19:28 UTC, rijkvanzanten commented on app/src/interfaces/_system/system-filter/system-filter.vue
> +] as const;
Should pull this from the shared constants

2021-09-10 20:01 UTC, rijkvanzanten requested changes
.

2021-09-23 02:43 UTC, azrikahar reviewed
This review may not be super thorough as it's just from a code perspective, but nothing very obvious/glaring otherwise.

2021-09-23 02:43 UTC, azrikahar commented on app/src/lang/translations/en-US.yaml
> +    name: Filter,
Is the comma intentional?

2021-09-23 09:23 UTC, Nitwel commented on app/src/components/v-field-select/v-field-select.vue
> +import { useFieldTree } from '@/composables/use-field-tree';
Doesn't matter as it can be imported both ways.

2021-09-23 09:49 UTC, Nitwel commented on app/src/components/v-field-select/v-field-select.vue
> +import { useFieldTree } from '@/composables/use-field-tree';
The reason why we can to this is that `@/composables/use-field-tree` is pointing to a folder and not a file which contains a `index.ts` which exports the composable both as a default and in an object. https://github.com/directus/directus/blob/b3639310c845e9173579070204c657d889150c79/app/src/composables/use-field-tree/index.ts#L1-L4

2021-09-23 10:36 UTC, azrikahar commented on app/src/components/v-field-select/v-field-select.vue
> +import { useFieldTree } from '@/composables/use-field-tree';
Thanks for clarifying! 👍

2021-09-24 21:37 UTC, rijkvanzanten requested changes

2021-09-24 21:37 UTC, rijkvanzanten commented on app/src/interfaces/_system/system-filter/system-filter.vue
> +	},
Lets make this interface use the regular (documented) filter structure, instead of converting to/from a proprietary array-based structure.

2021-09-30 21:10 UTC, rijkvanzanten approved these changes

2021-09-30 21:17 UTC, merged