Display private images in WYSIWYG editor
directus/directus pull request #7583
Opened 2021-08-24 20:12 UTC by jaycammarano

Fixes #5920 
Appends an access token to the image URL when displaying it in the WYSIWYG editor as well as in the image upload drawer. 
Removes access token before adding to the database.

2021-08-24 20:15 UTC, rijkvanzanten requested changes

2021-08-24 20:15 UTC, rijkvanzanten commented on app/src/interfaces/input-rich-text-html/input-rich-text-html.vue
> +					const remove_token = newValue.replace(
Use camelCase

2021-08-24 20:15 UTC, rijkvanzanten commented on app/src/interfaces/input-rich-text-html/input-rich-text-html.vue
> +							return `${pre}${matched.origin}${matched.pathname}${params}${post}`;
We still have to include the configured token when it exists (from `props.imageToken`)

2021-08-24 20:15 UTC, rijkvanzanten commented on app/src/interfaces/input-rich-text-html/input-rich-text-html.vue
> +function getPublicPath() { throw new Error('Function not implemented.'); }
This doesn't seem right here

2021-08-24 20:39 UTC, rijkvanzanten requested changes

2021-08-24 20:39 UTC, rijkvanzanten commented on app/src/interfaces/input-rich-text-html/input-rich-text-html.vue
> +							}${params}${post}`;
Wouldn't this resolve into `https://localhost:8055/assets/abc-def-ghi/my-custom-image-token?query=ab` ? The imageToken is part of params, so I think it has to be

```
params.set('access_token', props.imageToken);

return `${pre}${matched.origin}${matched.pathname}${params}${post}`;

2021-08-24 22:51 UTC, rijkvanzanten approved these changes

2021-08-24 22:55 UTC, rijkvanzanten approved these changes

2021-08-24 22:55 UTC, merged

2021-10-08 11:44 UTC, domdus commented
Hey guys,

I'm on rc.95 and not sure if this is fully working. I can embed see an image in WYSIWYG editor at first.
I also see the token being added when right-click the image -> image (modal view): 
![image](https://user-images.githubusercontent.com/67951828/136549285-fc5c0d8a-2202-4e8f-b271-02a6ea7e6d91.png)

If you **instead** select the image and click "image" from the toolbar on top (sidebar view), the token is added **twice** and images goes HTTP 500:

**Request-URL:**
`https://<DOMAIN>/assets/159ce235-9b5f-4dee-9d48-ff8de56a7509?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM0NjZkMDQ3LWQwZGItNDliZC1iN2EyLWQ3NmQzMjMzZDdjMyIsImlhdCI6MTYzMzY5MjE4MSwiZXhwIjoxNjMzNjkzMDgxLCJpc3MiOiJkaXJlY3R1cyJ9.KIpMiYa1WiblxDLyEXqLn1cKSJh0YlM-03mIqBMfzMk&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM0NjZkMDQ3LWQwZGItNDliZC1iN2EyLWQ3NmQzMjMzZDdjMyIsImlhdCI6MTYzMzY5Mjc5NSwiZXhwIjoxNjMzNjkzNjk1LCJpc3MiOiJkaXJlY3R1cyJ9.hIZoQhT4RfJ2FJxZ_5IpT-4z7R6IkgWL4B8iSE4Mt5c`

![image](https://user-images.githubusercontent.com/67951828/136550363-20a4b5ec-72f9-4bfd-b465-53eacb5d4408.png)

2021-10-08 14:42 UTC, domdus commented
#8653