Update logging in CLI commands
directus/directus pull request #7676
Opened 2021-08-29 09:56 UTC by smilledge

### ✨️ Improvements
- Replaced usage of `console` with `logger` in CLI commands
- Logging from CLI commands will now respect the `LOG_LEVEL` env var
![log level demo](https://user-images.githubusercontent.com/1536407/131246095-c2f49d72-6b61-47fc-9429-95e3ec87ab87.png)
- Useful information (eg, IDs from the create role/user) is always written to stdout so that output can be piped to other commands
![pipe output demo](https://user-images.githubusercontent.com/1536407/131246148-e3e256b2-0809-4468-9152-664a4185abb3.png)

2021-08-30 15:28 UTC, rijkvanzanten requested changes
I'm wondering if we should keep relying on console.log for `init`, as that's meant to be an interactive questionnaire, and not a flow you'd ever disable the "logs" for 🤔 

The others make sense to me 👍🏻

2021-08-30 15:28 UTC, rijkvanzanten commented on api/src/cli/commands/init/index.ts
> +			logger.info('');
We can drop the `''` here. With `console.log`, it'll print an empty line, but with `pino`, it'll construct a whole new logging object without a message, which isn't what we'd want.

```suggestion
			logger.info(err, `
Something went wrong while seeding the database:

${chalk.red(`[${err.code || 'Error'}]`)} ${err.message}

Please try again
			`);
```

2021-08-30 15:28 UTC, rijkvanzanten commented on api/src/cli/commands/init/index.ts
> +	logger.info(`Create your first admin user:`);
```suggestion
	logger.info(`


Create your first admin user:`);
```

2021-08-31 03:50 UTC, smilledge commented
Yeah definitely, I didn't think of that. We can use stdout for the init command too? 

Output looks like this now;
![Screenshot from 2021-08-31 13-45-48](https://user-images.githubusercontent.com/1536407/131438709-2ec4785d-9c3d-4bc4-a05a-6c5f6cd07cad.png)

2021-08-31 15:33 UTC, rijkvanzanten commented
> We can use stdout for the init command too?

Sure! That works. What's the perk of relying on stdout directly instead of console log? Doesn't console log just print to stdout with a newline character at the end?

2021-09-02 13:16 UTC, smilledge commented
> What's the perk of relying on stdout directly instead of console log? Doesn't console log just print to stdout with a newline character at the end?

Yeah there isn't really any different here, just semantics and avoiding an `eslint-disable` 🤷‍♂️

2021-09-03 02:03 UTC, rijkvanzanten approved these changes

2021-09-03 02:04 UTC, rijkvanzanten commented
LGTM! Thanks Sam 🙂

2021-09-03 02:06 UTC, merged