Add jwt support for static token
directus/directus pull request #7830
Opened 2021-09-04 13:38 UTC by azrikahar

Fixes #5598

## Context

Currently the `authenticate` middleware checks whether the token is in JWT format (`isJWT(req.token)`). If it is, then proceed to check it like a user access token, else it will then try to search for the static token for this user, as seen here:

https://github.com/directus/directus/blob/698580a6611207c26973da8b4795deb360ba4521/api/src/middleware/authenticate.ts#L26-L79

The `isJWT()` utility function currently only checks if a string conforms to the structure of a JWT. Line 26 in particular is where the payload is parsed, but not really inspected for it's content:

https://github.com/directus/directus/blob/698580a6611207c26973da8b4795deb360ba4521/api/src/utils/is-jwt.ts#L7-L32
 
## Solution

Previously the suggested solution in the reply of the above issue was to add a dedicated directus scope. However [JWT spec already has the Issuer claim](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.1) which is used to identify who issued the token. Since that aligns perfectly to the purpose/direction of the suggested solution, this PR opts to use the Issuer claim. Plus it's supported out-of-the-box by the `jsonwebtoken` package currently used in Directus.

The `isJWT()` utility is modified to check whether the payload includes `iss: 'directus'` (Issuer claim) property. It is then promptly renamed to `isDirectusJWT()` to be more appropriate.

## Test performed in the before/after depiction

I used the following custom made JWT token using the site https://jwt.io/ in both cases. It is set as the static token for the admin user.

![chrome_aJ8sdTzlkt](https://user-images.githubusercontent.com/42867097/132095958-460a581d-24a4-4ce0-aa2f-2e7f225bf12e.png)

## Before fix

### The payload in the token

![chrome_bKZ3bkFN9q](https://user-images.githubusercontent.com/42867097/132095779-8b593b8d-4581-4950-bfe2-5963032669cf.png)

### Failed attempt to call collections API using the custom token

![chrome_mCSbSkYyN8](https://user-images.githubusercontent.com/42867097/132096051-dd8ca773-ea1e-41fd-bdd5-32c9f44ea00c.png)

## After fix

### The payload in the token

Now the payload includes `iss` property which is the Issuer claim.

![chrome_qZ5l6O5aUm](https://user-images.githubusercontent.com/42867097/132095820-604e8455-7e42-4ad8-9d6b-3dc4fe9efccd.png)

### Successful attempt to call collections API using the custom token

![chrome_MMimUvYI0V](https://user-images.githubusercontent.com/42867097/132096034-8898f10e-c910-49dd-8056-2bbc39273b96.png)

## Pending Discussion

Currently there are still 2 places where JWT signing occurs that **DOES NOT** add issuer to the payload, which are

- Invite User

    - Where JWT signing occurs & the scope `invite` is added to the payload
    
        https://github.com/directus/directus/blob/698580a6611207c26973da8b4795deb360ba4521/api/src/services/users.ts#L307-L308

    - Where the token is checked to see whether the scope `invite` is present
    
        https://github.com/directus/directus/blob/698580a6611207c26973da8b4795deb360ba4521/api/src/services/users.ts#L329-L334
        
- Request Password Reset

    - Where JWT signing occurs & the scope `password-reset` is added to the payload
  
        https://github.com/directus/directus/blob/698580a6611207c26973da8b4795deb360ba4521/api/src/services/users.ts#L367-L368

    - Where the token is checked to see whether the scope `password-reset` is present
    
        https://github.com/directus/directus/blob/698580a6611207c26973da8b4795deb360ba4521/api/src/services/users.ts#L393-L398

Current thoughts on the above 2 features involving JWT tokens:

- If we were to add the issuer here, it may break existing pending user invites & password resets, right? so we might need to note this as a breaking change if we do indeed add issuer to them.

- It may not even be necessary to add issuer for them since there are the scope check already.

- However in terms of completeness or uniformity perspective, adding issuer to them also sort of makes sense.

2021-09-07 19:50 UTC, rijkvanzanten commented
@azrikahar Lets add the `iss` to every place we generate a JWT, for consistencies sake 👍🏻

2021-09-07 19:51 UTC, rijkvanzanten requested changes
@azrikahar Lets add the `iss` to every place we generate a JWT, for consistencies sake 👍🏻

2021-09-07 21:41 UTC, azrikahar commented
> @azrikahar Lets add the `iss` to every place we generate a JWT, for consistencies sake 👍🏻

Done 👍 regarding the pending jwt tokens already sent out via email for password resets and user invites will end up unusable, I'll let you decide if that's notice worthy or not. Cheers!

2021-09-09 18:46 UTC, rijkvanzanten approved these changes

2021-09-09 18:47 UTC, merged