Convert to object default json value
directus/directus pull request #8041
Opened 2021-09-15 06:20 UTC by joselcvarela

With this PR #8012 I couldn't run app locally.
Basically, I found that PR is adding a new json column to an existent table with a default value.
Turns out that default value comes as string instead of an json object (at least in SQLite).

![image](https://user-images.githubusercontent.com/14039341/133380913-a0ecc8da-c6bd-4869-807b-25ab28aa97be.png)

This ensures the returned value is a json object.

PS: I can't replicate anymore since I have populated that field. It seems this is an edge case, but I think it could be helpful on future.

2021-09-16 01:19 UTC, rijkvanzanten requested changes

2021-09-16 01:19 UTC, rijkvanzanten commented on api/src/utils/get-default-value.ts
> +	if (typeof value === 'object') return value;
We should take null/undefined and other falsy values in mind here as well. I think a simple `if (!value) return value` should do the trick

2021-09-16 01:19 UTC, rijkvanzanten commented on api/src/utils/get-default-value.ts
> +		}
We should return the original value still when the json conversion goes wrong.

```suggestion
		} catch (err: any) {
			if (env.NODE_ENV === 'development') {
				logger.error(err);
			}
			
			return value;
		}
```

2021-09-16 01:19 UTC, rijkvanzanten commented
Another funky thing here to be aware of is that not every database vendor supports default values in JSON type columns, but that's not really something we can do much about..

2021-09-16 06:57 UTC, joselcvarela commented
Since this is a json column, shouldn't we always return an object?
If for example value is `0`, and we do the condition `if (!value) return value`, we will return a `number`.
Is this an expected case?

2021-09-18 01:46 UTC, rijkvanzanten commented
> Since this is a json column, shouldn't we always return an object?
If for example value is 0, and we do the condition if (!value) return value, we will return a number.
Is this an expected case?

`0` is theoretically valid JSON, as are the other primitives 🙂

2021-09-28 23:16 UTC, rijkvanzanten approved these changes

2021-09-28 23:16 UTC, merged