Tests for validatePayload, generateExtensionsEntry, and ensureExtensionsDir
directus/directus pull request #8353
Opened 2021-09-27 19:29 UTC by jaycammarano

- validatePayload, tests passing 100% coverage 
- generateExtensionsEntry, tests passing 100% coverage 
- and ensureExtensionsDir, tests passing missing line 12

2021-09-27 20:02 UTC, rijkvanzanten requested changes

2021-09-27 20:02 UTC, rijkvanzanten commented on packages/shared/src/utils/node/ensure-extension-dirs.test.ts
> +	it('throws an error when a folder cant be opened', () => {
We should add some before/after functions here to setup/teardown the folder structure to test, to ensure other tests/repeated invocations don't cause state-based inconsistencies in the test results

2021-09-27 23:05 UTC, rijkvanzanten requested changes

2021-09-27 23:05 UTC, rijkvanzanten commented on packages/shared/src/utils/node/ensure-extension-dirs.test.ts
> +		}).rejects.toThrow(`Extension folder "/interfaces" couldn't be opened`);
This `/interfaces` name is based on the imported const, but isn't really specific to this particular test/function. we should test with a custom name so we can test the function, rather then test the function combined with the external `types` array (the function should work regardless of input array)

```suggestion
			await ensureExtensionDirs('/.', ['test']);
		}).rejects.toThrow(`Extension folder "/test" couldn't be opened`);
```

2021-09-27 23:06 UTC, rijkvanzanten commented
Gotta keep things as decoupled as possible for these unit tests 🙂

2021-09-27 23:51 UTC, nickrum requested changes

2021-09-27 23:51 UTC, nickrum commented on packages/shared/package.json
> +		"tmp": "^0.2.1",
This should probably be a dev dependency.

2021-09-28 13:47 UTC, rijkvanzanten requested changes

2021-09-28 13:56 UTC, nickrum approved these changes

2021-09-28 18:36 UTC, rijkvanzanten approved these changes

2021-09-28 22:58 UTC, merged