Unit tests for get-extensions.ts
directus/directus pull request #8470
Opened 2021-09-30 19:12 UTC by jaycammarano

- getPackageExtensions tests pass, 95% coverage
- getLocalExtensions tests passing, 100% coverage
- superfluous root boolean removed from Extension type

2021-09-30 19:13 UTC, rijkvanzanten approved these changes

2021-09-30 19:25 UTC, rijkvanzanten commented
@jaycammarano Missed a case where root is used 🤔

2021-09-30 19:26 UTC, nickrum requested changes

2021-09-30 19:26 UTC, nickrum commented on packages/shared/src/utils/node/get-extensions.ts
>  	async function listExtensionsChildren(extensionNames: string[], root?: string) {
```suggestion
	async function listExtensionsChildren(extensionNames: string[], root: string) {
```

2021-10-01 15:00 UTC, nickrum approved these changes

2021-10-01 15:01 UTC, merged