smaller and bolder breadcrumb
directus/directus pull request #8566
Opened 2021-10-05 15:54 UTC by benhaynes

NOTE: The Settings routes are not currently using `v-breadcrumb`... but should. @rijkvanzanten said this was just an oversight from earlier on.

2021-10-05 15:55 UTC, rijkvanzanten requested changes
Lets fix the settings breadcrumb omission as part of this PR before merging

2021-10-05 15:57 UTC, benhaynes commented
I agree. I looked into this, but it's beyond my skillset.

2021-10-05 15:59 UTC, rijkvanzanten commented
That's why I assigned myself as co-assignee for this pr 😄

2021-10-07 22:15 UTC, rijkvanzanten approved these changes

2021-10-07 22:16 UTC, merged