Authentificate input-autocomplete-api requests to Directus API
directus/directus pull request #9389
Opened 2021-11-03 07:09 UTC by julbd

This allows querying the Directus API itself.

We could also add many variables to the "scope" passed to the URL, such as `access_token`, environment variables or stores in addition to `{{value}}`.

2021-11-03 19:57 UTC, rijkvanzanten commented
What's the benefit of using the Directus API in the auto-complete input over utilizing a relational interface? It can only save static value, so you'd lose a lot of perks

2021-11-03 20:35 UTC, julbd commented
@rijkvanzanten Relational interface require a dedicated collection. In some case, you could want to suggest the existing values (from the API) used in others records, without requiring to manually "create a new item" for new values.

2021-11-03 20:37 UTC, rijkvanzanten commented
> In some case, you could want to suggest the existing values (from the API) used in others records, without requiring to explicitly "create a new item" for others values.

Huh, but if you're pulling that item from Directus' API, don't you already have a collection+item you want to reference?

2021-11-03 20:41 UTC, julbd commented
...you want to suggest+copy, not create+reference. More generally, I found weird to have an "API" interface that could not target its own super-powerful API.

2021-11-03 20:42 UTC, rijkvanzanten commented
Ahhh I see! That makes more sense 😄

2022-06-19 08:30 UTC, mslonina commented
Hi,

would it be possible here to set custom headers for authorized requests to other services? I.e. with $CURRENT_USER having access to directus_users fields, one can extend the model to set external API key/token (for example another Directus instance) and use them during autocomplete.

2022-06-20 15:26 UTC, rijkvanzanten commented
@mslonina The current autocomplete input uses the Application to make the requests, so it doesn't have access to any of the API-based variables coming from authorization at this point 🤔 If we wanted to support those dynamic variables, they'd have to be re-implemented into that interface specifically, which would add quite a bit of maintenance headaches

2022-06-30 15:56 UTC, rijkvanzanten requested changes

2022-06-30 18:14 UTC, azrikahar commented on app/src/interfaces/input-autocomplete-api/input-autocomplete-api.vue
> +				url = addTokenToURL(url);
Is this the same as #14193? (or is this PR still needed?)

2022-06-30 18:25 UTC, rijkvanzanten commented
Superseded by https://github.com/directus/directus/pull/14193

2022-06-30 18:25 UTC, closed without merging