Expose server instance in action hook 'server.start'
directus/directus pull request #9616
Opened 2021-11-08 17:41 UTC by gkielwasser

Since hooks refactor, we cannot access anymore the http server instance. Expose it.

2021-11-08 18:00 UTC, joselcvarela requested changes
Hey @gkielwasser,
Thanks for this.

Can you also add to `server.stop` and update the documentation?
https://docs.directus.io/extensions/hooks/#available-events-2

Also you can put all in a single line, since it is a single variable.

2021-11-08 18:09 UTC, gkielwasser commented
> Hey @gkielwasser, Thanks for this.
> 
> Can you also add to `server.stop` and update the documentation? https://docs.directus.io/extensions/hooks/#available-events-2
> 
> Also you can put all in a single line, since it is a single variable.

yep it makes sense, here it is

2021-11-08 18:23 UTC, joselcvarela approved these changes

2021-11-09 16:22 UTC, rijkvanzanten approved these changes

2021-11-09 16:28 UTC, merged