Update formatted-value display
directus/directus pull request #9773
Opened 2021-11-13 08:50 UTC by alejandro-tss

List of configuration parameters available in the display, divided into three groups, the common parameters, for all types of values, the number parameters for the types `integer,float,decimal,bigInteger`, the parameters for the types `string,text` and the conditional parameters based on the configuration of the links.

### Common parameters
- [x] **clipboard**: Adds a button to copy the field value to the clipboard.
- [x] **bold**: Change the font thickness to bold.
- [x] **font**: List of font format, allows: Sans Serif, Serif or Monospace.
- [x] **textAlign**: Text alignment list, useful to align numeric values, allows: Left, Center or Right
- [x] **color**: Text color.
- [ ] **backgroundColor**: Background color of the cell.
- [x] **iconLeft**: Icon that appears to the left of the text.
- [x] **iconLeftColor*: Color of the icon that appears to the left of the text.
- [x] **iconRight**: Icon that appears to the right of the text.
- [x] **iconRightColor**: Color of the icon that appears to the right of the text.

### Parameters for numeric types
- [x] **prefix**: Add text to the left of the value. **Important**: does not remove blanks.
- [x] **suffix**: Add text to the right of the value. **Important**: does not remove blanks.
- [ ] **multiply**: Multiply by one number. This allows, for example, to display percentage values.
- [ ] **divide**: Divide by a number. This allows, for example, to divide by the decimals of the currency when storing amounts of money without decimals, a very common case when integrating payment gateways.
- [x] **formatRules**: Allows to configure text formatting rules.
    - [x] **operator**: List of operators to check the rule, allows: Less than, Less than or equal to, Greater than, Greater than or equal to, Equal to, Not equal to, Not equal to, Not equal to.
    - [x] **value**: Value to check against the original value.
    - [x] **color**: Allows to change the color of the default text.
    - [ ] **backgroundColor**: Allows to change the default background color.
    - [x] **iconLeft**: Allows to change the icon that appears to the left of the text.
    - [x] **iconLeftColor**: Allows to change the color of the icon that appears to the left of the text.
    - [x] **iconRight**: Allows you to change the icon that appears to the right of the text.
    - [x] **iconRightColor**: Allows you to change the color of the icon that appears to the right of the text.

### Parameters for string types
- [x] **formatTitle**: Format the text.
- [x] **link**: List of link types, allows: No Link, URL, Email, Tel, WhatsApp.

### Parameters for links
- [x] **linkText**: Text to display in the link. **Important**: if no value is specified, displays the value of the default field.

### Parameters for email type links
- [x] **linkEmailSubject**: Subject of the message by default.
- [x] **linkEmailBody**: Default message body.
- [x] **linkEmailCC**: Default CC of the message.
- [x] **linkEmailBCC**: Default message BCC.

### Parameters for whatsapp type links
- [x] **linkWhatsappText**: Default message text.

2021-11-13 10:06 UTC, alejandro-tss commented
## Some screenshots for numbers

### Without configuration
![simple-numbers](https://user-images.githubusercontent.com/74362408/141614629-a6a189d8-760e-4bea-a79d-f8b955c056cd.png)

### With configuration
![formated-numbers](https://user-images.githubusercontent.com/74362408/141614627-fca9ca7c-bc0c-4d44-aa6d-500ccb17776b.png)

2021-11-13 16:45 UTC, benhaynes commented
Whoa... my oh my! This is quite the PR!! You really went 150% on this one, @alejandro-tss ... thank you!

I'll dive into this on Monday, but in the meantime, it'd be great to see a screenshot of this Display's Options in Settings (are those link options conditional based on the dropdown? 😍 ). I love the flexibility you've included, but I want to make sure it's not overwhelming in the configuration UI. I wonder if some of these options might be a bit beyond our [80/20 rule](https://docs.directus.io/contributing/introduction/#feature-requests). 🤔 

Here are the ones I'm questioning:

* **prefix/suffix** — Any reason not to promote these to common parameters for all data types?
* **iconLeft** — (and all other left icon options) I think we can get more use out of iconRight (and just calling it "icon"). Not sure how many usecases of a left icon can't be solved by the prefix. Removing this one feature would remove four options.
* **linkWhatsappText** — I know it's a popular service, but since it's not a "standard" (eg: email), I worry about starting to include opinionated third-party platforms in Core.
* I'm on the fence about all the specific email/link options. They add value, but I'm unsure about 80/20.

Thoughts on this balance, @rijkvanzanten ?

So excited about this one! 🥳

2021-11-17 14:47 UTC, alejandro-tss commented
@benhaynes, I haven't replied before because I was waiting to see what @rijkvanzanten thought before I started to make the changes, but, I'll answer your points:

* _prefix/suffix — Any reason not to promote these to common parameters for all data types?_ **I thought it only made sense for numeric fields, but, it doesn't cost me anything to leave it in all cases.**
* _iconLeft — (and all other left icon options) I think we can get more use out of iconRight (and just calling it "icon"). Not sure how many usecases of a left icon can't be solved by the prefix. Removing this one feature would remove four options._ **You are right that there are many elements, I thought to put them in a group that was collapsible, but, it seems to me that forcing them to be in a place is a very rigid option, I gave the possibility to choose where to show the icons because, I understand that the numbers in a table should appear aligned to the right and perhaps it makes more sense to add an icon to the left or vice versa, in any case, it seemed more interesting for the user to decide.**
* _linkWhatsappText — I know it's a popular service, but since it's not a "standard" (eg: email), I worry about starting to include opinionated third-party platforms in Core._ **It seems to me well, we can remove it, this can be solved with specific extensions when the marketplace appears.**
* _I'm on the fence about all the specific email/link options. They add value, but I'm unsure about 80/20._  **In this case, I think that if you use email links, it is not superfluous to indicate default values, taking into account that they are fields that only appear when selecting that type of link and are optional.**


Finally, regarding the two fields multiply and divide, what is your opinion? I have some use cases in which it would be very useful, but, I wanted to know your opinion before implementing it.

I will record a short video to show you the configuration options, I will upload it soon.

2021-11-17 15:03 UTC, alejandro-tss commented
@benhaynes here is a sample configuration: https://www.loom.com/share/c4aead6fc636447f8bf26cf774161505

2021-11-18 01:21 UTC, benhaynes commented
Yeah, @rijkvanzanten will be back on Core soon, but has been 100% on our new Cloud for a while now.

Let's make prefix/suffix global, remove the left icon (and rename the right one to just "icon") and remove WhatsApp. We can leave the link stuff in for now, and see what Rijk thinks.

For multiply/divide, I thought it was overkill at first, but then was agreeing that it might be nice for percentages. Again, let's see what @rijkvanzanten thinks on this one.

Lastly, do we have the formatting rule repeater in? I noticed it's checked off but didn't see it in the video. 🤔 

Thank you!! It's looking great!! I'll come up with the Display Option order once we have the options themselves finalized.

2021-11-18 19:18 UTC, Fusseldieb commented
Oh wow! This looks lit ahahaha 🔥

2021-11-22 20:01 UTC, rijkvanzanten requested changes

2021-11-22 20:01 UTC, rijkvanzanten commented on app/src/displays/formatted-value/index.ts
> +							{ text: '$t:displays.formatted-value.link_whatsapp', value: 'whatsapp' },
lets remove this

2021-11-22 20:13 UTC, alejandro-tss commented on app/src/displays/formatted-value/formatted-value.vue
> +		},
How do you want me to check if the link is out of the application, before or after calculating the href?

2021-11-24 22:50 UTC, rijkvanzanten commented on app/src/displays/formatted-value/formatted-value.vue
> +		},
If the whole href is passed in, we can check if it starts with or without a protocol 👍🏻

2021-11-25 20:47 UTC, alejandro-tss commented
@rijkvanzanten I have resolved all change requests

2021-12-05 19:30 UTC, joselcvarela commented
Thank you @alejandro-tss 
I only partially tested it, but I found a weird behaviour.

https://user-images.githubusercontent.com/14039341/144760755-3c170278-bff0-4da1-8884-0e96935a4825.mov

It seems you are modifying the values after they were populated or something like that.
If possible, can you fix that?

2021-12-06 08:55 UTC, alejandro-tss commented
@joselcvarela I'm not sure I understand the error, do you mean that when editing the display settings the indicator appears that the value has been modified? If so, I think that is the default behavior, I have tried on other displays and they work the same, it seems that if the current value is different than the default value that indicator appears, sorry if I am not understanding the problem.

2021-12-06 14:31 UTC, joselcvarela commented
Yeah that was what I intended to describe.
Just checked the main branch also behaves the same. Maybe we can improve that on other PR. 
Until the end of the day I will take another look, but seems great so far 👍

2021-12-07 07:27 UTC, joselcvarela approved these changes
I made a few commits to fix minor issues.
But, I also applied the conditions to strings too. I don't find a reason to limit only to numbers and this way we can be more versatile.

About the translations, @rijkvanzanten should we take advantage of existent translations or it is right like how it is done?

2021-12-07 17:58 UTC, rijkvanzanten commented
> About the translations, @rijkvanzanten should we take advantage of existent translations or it is right like how it is done?

It's fine for now. Ideally, we figure out where else the same strings are used, so we can prevent duplicates, but that's a bit of a bigger cleanup operation not necessarily related to this new feature.

2021-12-09 23:32 UTC, benhaynes commented
Hey @alejandro-tss — we are about to merge this, but noticed a few of my last points weren't finished. Once these are addressed I think we're good:

* Icon Right (and all accompanying options) should be removed
* Icon color should be removed; icon color should match the text color
* Icon Left should be renamed: `icon`
* Is background color still missing? I see it in one of the videos...
* Update the Options Layout to:

```
Format + Copy
Bold + Italic
Font + Align
Prefix + Suffix
Color + Background
Icon
Conditional Formatting (Full Width)
* Operator + Value (these are the conditions)
* Color + Background
* Text + Icon (text would override the text displayed)
----
Type Specific Options
```

Let me know if you want to discuss!!

2021-12-10 22:48 UTC, alejandro-tss commented
I've been making some adjustments regarding your last comment, but, I think at some point we have taken different paths and you have to tell me where to continue, these are some things that I don't know how to solve.

At @rijkvanzanten's request I removed the following options:

- copy: set it to layout level
- background: cannot be applied at cell level.
- align: cannot be applied at cell level.

To note:

- format: this is a conditional option, only appears if the field type is string or text.

The applied changes are:

- I have removed the iconRight, iconRightColor and iconLeftColor.
- I have changed the iconLeft option to icon and the same color as the text is applied.

Therefore the options are as follows: 

Bold + Italic
Font + Color
Prefix + Suffix
Icon [+ Format]
Link [+ LinkTemplate]

Conditional Formatting (Full Width)
Name 
Filter (Full Width)
Color + Icon

Finally, I don't understand the behavior of the conditional text field, could you give me more details?

2021-12-11 03:16 UTC, benhaynes commented
Hey @alejandro-tss, sorry for not posting an update yet, but we just had an internal meeting about this a few hours ago. @joselcvarela can give you an update (GitHub or Discord) for what the strategy is, and/or help get this wrapped up.

2021-12-11 11:25 UTC, joselcvarela commented
Hello @alejandro-tss 

So this is the UI for the display configuration we want:
```
Format + Font
Bold + Italic
Prefix + Suffix
Color + Background
Icon + Border
Conditional Formatting (Full Width)
* Operator + Value (these are the conditions)
* Color + Background
* Text + Icon (text would override the text displayed)
``` 

Description

| Field      	| Label       	| Notes                                                                                                   	|
|------------	|-------------	|---------------------------------------------------------------------------------------------------------	|
| Format     	| Auto format 	| In case of string, uses auto format case. In case of number, adds , or . to numbers depending on locale 	|
| Font       	| Implemented 	|                                                                                                         	|
| Bold       	| Implemented 	|                                                                                                         	|
| Prefix     	| Implemented 	|                                                                                                         	|
| Suffix     	| Implemented 	|                                                                                                         	|
| Color      	| Color       	| Color for text, icon and border                                                                         	|
| Background 	| Background  	| Color for background. Should be rounded see example on image 1                                          	|
| Icon       	| Icon        	| Should be applied to the right of text                                                                  	|
| Border     	| Border      	| Boolean (by default we use 2px). Should                                                                 	|
| Conditions 	|             	|                                                                                                         	|
| Operator   	| Operator    	| Use the same component as shown on image 2                                                              	|
| Value      	| Value       	| Use the same component as shown on image 2                                                              	|
| Color      	| Color       	| Will override the color, if rule matches                                                                	|
| Background 	| Background  	| Will override the background, if rule matches                                                           	|
| Text       	| Text        	| Will override the text / value, if rule matches.                                                        	|
| Icon       	| Icon        	| Will override the icon, if rule matches.                                                                	|

Image 1
![image](https://user-images.githubusercontent.com/14039341/145674633-df7dfb06-7ba4-44b9-86b2-171dca7f9795.png)

Image 2
![image](https://user-images.githubusercontent.com/14039341/145674663-7177f6af-596e-4f75-803e-aa757ac622fa.png)


About Image 2, you can find that component here: https://github.com/directus/directus/blob/ffde89d7e2ff7f21f5d7bcb561dc301e8208658d/app/src/panels/metric/index.ts#L182 (It is being used in Insights > Panel > Metric)

2021-12-11 14:53 UTC, alejandro-tss commented
@joselcvarela I understand that now the conditional formatting reappears only when the field type is numeric, right?

2021-12-11 16:32 UTC, benhaynes commented
No, it would work for strings too — just with limited operators (eq only?).

2021-12-11 17:00 UTC, alejandro-tss commented
I do whatever you tell me, I can include more operators for strings besides eq, such as startswith, endswith or contains, as well as whether they are case sensitive or not. @benhaynes, @rijkvanzanten, @joselcvarela what do you think?

2021-12-11 17:11 UTC, alejandro-tss commented
I have one more doubt, with the text field of the conditions, what is the behavior, does it replace all prefix + value + suffix by text or is it a replacement only of the original value, remaining prefix + text + suffix?

2021-12-11 17:14 UTC, benhaynes commented
I think those operators are all good... though additional options for case insensitive might be too much. For the conditional text, let's have it replace prefix+value+suffix... so you could have `Free!` instead of `$Free!`.

2021-12-11 17:15 UTC, alejandro-tss commented
One more, just to clarify, the icon should appear on the right, right? I say this because in the example image that @joselcvarela has posted the icon appears on the left.

2021-12-11 17:24 UTC, benhaynes commented
Haha, good question! I think let's start with the icon on the **left**... that's where I see it most often.

2021-12-12 13:39 UTC, alejandro-tss commented
I have just added a commit with the last requested changes, I am waiting for your feedback. @benhaynes, @rijkvanzanten, @joselcvarela

2021-12-12 19:56 UTC, benhaynes commented
Awesome, thank you!  We'll take a look as soon as we can...

2021-12-13 06:45 UTC, joselcvarela commented
Thank you @alejandro-tss 
Seems great now 👍

@benhaynes once you don't like "pulling" 😅 here you go:

Number:
https://user-images.githubusercontent.com/14039341/145764867-85818b5a-756a-4a7e-b0dc-fb3743e68179.mov

String:
https://user-images.githubusercontent.com/14039341/145764889-37bf3315-6775-4b50-815c-3950fb980431.mov

2021-12-14 14:15 UTC, benhaynes commented
❤️  Haha, thanks @joselcvarela!! Yup, lazy... but really appreciate these videos. This looks perfect to me, hopefully we can get it merged in! Thank you, @alejandro-tss!!

CC @rijkvanzanten

2021-12-16 22:06 UTC, rijkvanzanten approved these changes

2021-12-16 22:10 UTC, merged

2021-12-17 11:10 UTC, neo7-studio-web commented
Hi, what a great job, thanks !

Maybe I missed something, but I couldn't find any option to make a link from a string field in 9.3.0.
How does it work ?

2021-12-17 14:21 UTC, joselcvarela commented
Hello @neo7-studio-web 
We have decided that link should have their own display.
So, this is not available as of right now.

2022-11-21 20:12 UTC, nervusdm commented
How do I make the value use a column from the same collection ?
In your example I see 9000.
Can I set {{other_field}} ?